using System.Text;
using InfraFlowSculptor.GenerationCore;
using InfraFlowSculptor.GenerationCore.Models;

namespace InfraFlowSculptor.PipelineGeneration.Generators.App;

using static PipelineGenerationEngine;

/// <summary>
/// Emits pipeline headers, environment variable references, and resolves environment variable paths
/// for application CI and release pipelines.
/// </summary>
internal static class AppHeaderEmitter
{
    /// <summary>Artifact name for application metadata.</summary>
    internal const string MetadataArtifactName = "app-metadata";

    /// <summary>Artifact name for the compiled application package.</summary>
    internal const string PackageArtifactName = "application-package";

    /// <summary>Artifact name for supply-chain attestation.</summary>
    internal const string SupplyChainArtifactName = "supply-chain";

    /// <summary>
    /// Resolves the path to environment variable files for use inside an app pipeline template.
    /// Returned path is relative to the template file location (<c>.azuredevops/pipelines/</c>).
    /// </summary>
    /// <param name="envKey">The environment short name (lowercase).</param>
    /// <param name="isMonoRepo">When <c>true</c>, env vars are at <c>.azuredevops/variables/</c>.
    /// When <c>false</c>, env vars are at the standalone artifact root <c>variables/</c>.</param>
    /// <returns>The relative YAML template path to the environment variables file.</returns>
    internal static string GetEnvironmentVariablesPath(string envKey, bool isMonoRepo)
    {
        return isMonoRepo
            ? $"../variables/{envKey}.variables.yml"
            : $"../../variables/{envKey}.yml";
    }

    /// <summary>
    /// Appends the CI pipeline header block with trigger configuration and root-level pool.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="resourceName">The resource name (will be sanitized).</param>
    /// <param name="configName">The configuration name (will be sanitized).</param>
    /// <param name="agentPoolName">Optional custom agent pool name.</param>
    internal static void AppendCiHeader(StringBuilder sb, string resourceName, string configName, string? agentPoolName)
    {
        configName = PathSanitizer.Sanitize(configName);
        resourceName = PathSanitizer.Sanitize(resourceName);

        sb.AppendLine($"# CI Application Pipeline for {resourceName} — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(Date:yyyyMMdd).$(Rev:r)");
        sb.AppendLine();
        sb.AppendLine("trigger:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        sb.AppendLine("      - main");
        sb.AppendLine("      - release/*");
        sb.AppendLine("  paths:");
        sb.AppendLine("    include:");
        sb.AppendLine($"      - {configName}/{resourceName}/*");
        sb.AppendLine();
        AppendPool(sb, agentPoolName, string.Empty);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the release pipeline header block (trigger: none, CI pipeline resource).
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="request">The application pipeline generation request.</param>
    internal static void AppendReleaseHeader(StringBuilder sb, AppPipelineGenerationRequest request)
    {
        var ciPipelineName = AppNamingHelper.EscapeForSingleQuotedYaml(AppNamingHelper.BuildCiPipelineDefinitionName(request));

        sb.AppendLine($"# Release Application Pipeline for {request.ResourceName} — Auto-generated by InfraFlowSculptor");
        sb.AppendLine($"# Expected CI pipeline definition name: {AppNamingHelper.BuildCiPipelineDefinitionName(request)}");
        sb.AppendLine("name: $(Date:yyyyMMdd).$(Rev:r)");
        sb.AppendLine();
        sb.AppendLine("trigger: none");
        sb.AppendLine();
        sb.AppendLine("resources:");
        sb.AppendLine("  pipelines:");
        sb.AppendLine("    - pipeline: ci");
        sb.AppendLine($"      source: '{ciPipelineName}'");
        sb.AppendLine("      trigger:");
        sb.AppendLine("        branches:");
        sb.AppendLine("          include:");
        sb.AppendLine("            - main");
        sb.AppendLine();
        AppendPool(sb, request.AgentPoolName, string.Empty);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends environment variable template references and variable group references.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="envKey">The environment short name (lowercase).</param>
    /// <param name="request">The application pipeline generation request.</param>
    /// <param name="indent">The YAML indentation prefix.</param>
    internal static void AppendEnvironmentVariableReferences(
        StringBuilder sb,
        string envKey,
        AppPipelineGenerationRequest request,
        string indent)
    {
        var variablesPath = GetEnvironmentVariablesPath(envKey, request.IsMonoRepo);
        sb.AppendLine($"{indent}- template: {variablesPath}");

        foreach (var group in request.PipelineVariableGroups)
        {
            var resolvedName = group.GroupName.Replace("{env}", envKey, StringComparison.OrdinalIgnoreCase);
            sb.AppendLine($"{indent}- group: {resolvedName}");
        }
    }
}
