using System.Text;
using InfraFlowSculptor.GenerationCore;
using InfraFlowSculptor.GenerationCore.Models;

namespace InfraFlowSculptor.PipelineGeneration.Generators.App;

/// <summary>
/// Builds thin PR validation pipeline wrapper YAML files that reference shared templates via <c>extends:</c>.
/// Wrappers live under <c>.azuredevops/{configName}/apps/{appName}/</c> and reference templates under
/// <c>.azuredevops/Common/pipelines/</c>.
/// </summary>
internal static class AppPrPipelineBuilder
{
    private const string ContainerTemplatePath = "../../../Common/pipelines/app-pr-container.pipeline.yml";
    private const string CodeTemplatePath = "../../../Common/pipelines/app-pr-code.pipeline.yml";
    private const string DefaultDockerfilePath = "Dockerfile";
    private const string DefaultBuildContext = ".";
    private const string DefaultRuntimeStack = "DOTNETCORE";
    private const string DefaultRuntimeVersion = "8.0";

    private static readonly IReadOnlyList<string> PrTriggerBranches = ["main", "develop", "release/*"];

    internal static string BuildContainerPipeline(AppPipelineGenerationRequest request)
    {
        var sb = new StringBuilder();
        var imageRepository = AppNamingHelper.ResolveImageRepository(request);
        var imageTagPattern = AppNamingHelper.ResolveImageTagPattern(request);
        var dockerfilePath = request.DockerfilePath ?? DefaultDockerfilePath;
        var buildContext = request.SourceCodePath ?? DefaultBuildContext;

        AppendPrHeader(sb, request);

        sb.AppendLine("extends:");
        sb.AppendLine($"  template: {ContainerTemplatePath}");
        sb.AppendLine("  parameters:");
        sb.AppendLine($"    resourceName: '{AppNamingHelper.EscapeForSingleQuotedYaml(request.ResourceName)}'");
        sb.AppendLine($"    configName: '{AppNamingHelper.EscapeForSingleQuotedYaml(request.ConfigName)}'");
        sb.AppendLine($"    resourceType: '{AppNamingHelper.EscapeForSingleQuotedYaml(request.ResourceType)}'");
        sb.AppendLine($"    imageRepository: '{AppNamingHelper.EscapeForSingleQuotedYaml(imageRepository)}'");
        sb.AppendLine($"    imageTagPattern: '{AppNamingHelper.EscapeForSingleQuotedYaml(imageTagPattern)}'");
        sb.AppendLine($"    dockerfilePath: '{AppNamingHelper.EscapeForSingleQuotedYaml(dockerfilePath)}'");
        sb.AppendLine($"    buildContext: '{AppNamingHelper.EscapeForSingleQuotedYaml(buildContext)}'");
        AppendAgentPoolParameter(sb, request.AgentPoolName);

        return sb.ToString();
    }

    internal static string BuildCodePipeline(AppPipelineGenerationRequest request)
    {
        var sb = new StringBuilder();

        AppendPrHeader(sb, request);

        sb.AppendLine("extends:");
        sb.AppendLine($"  template: {CodeTemplatePath}");
        sb.AppendLine("  parameters:");
        sb.AppendLine($"    resourceName: '{AppNamingHelper.EscapeForSingleQuotedYaml(request.ResourceName)}'");
        sb.AppendLine($"    resourceType: '{AppNamingHelper.EscapeForSingleQuotedYaml(request.ResourceType)}'");
        sb.AppendLine($"    runtimeStack: '{AppNamingHelper.EscapeForSingleQuotedYaml(request.RuntimeStack?.ToUpperInvariant() ?? DefaultRuntimeStack)}'");
        sb.AppendLine($"    runtimeVersion: '{AppNamingHelper.EscapeForSingleQuotedYaml(request.RuntimeVersion ?? DefaultRuntimeVersion)}'");
        sb.AppendLine($"    sourcePath: '{AppNamingHelper.EscapeForSingleQuotedYaml(request.SourceCodePath ?? DefaultBuildContext)}'");
        sb.AppendLine($"    testCommand: '{AppNamingHelper.EscapeForSingleQuotedYaml(request.TestCommand ?? string.Empty)}'");
        sb.AppendLine($"    buildCommand: '{AppNamingHelper.EscapeForSingleQuotedYaml(request.BuildCommand ?? string.Empty)}'");
        AppendAgentPoolParameter(sb, request.AgentPoolName);

        return sb.ToString();
    }

    private static void AppendPrHeader(StringBuilder sb, AppPipelineGenerationRequest request)
    {
        var configName = PathSanitizer.Sanitize(request.ConfigName);
        var resourceName = PathSanitizer.Sanitize(request.ResourceName);
        var appFolderName = PathSanitizer.Sanitize(request.ApplicationName ?? request.ResourceName);

        sb.AppendLine($"# PR Application Pipeline for {resourceName} - Auto-generated by InfraFlowSculptor");
        sb.AppendLine($"# Expected PR pipeline definition name: {AppNamingHelper.BuildPrPipelineDefinitionName(request)}");
        sb.AppendLine("name: $(Date:yyyyMMdd).$(Rev:r)");
        sb.AppendLine();
        sb.AppendLine("trigger:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        sb.AppendLine("      - '*'");
        sb.AppendLine("  paths:");
        sb.AppendLine("    include:");
        sb.AppendLine($"      - {configName}/{resourceName}/*");
        sb.AppendLine("      - .azuredevops/Common/*");
        sb.AppendLine($"      - .azuredevops/{configName}/apps/{appFolderName}/*");
        sb.AppendLine();
        sb.AppendLine("pr:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        foreach (var branch in PrTriggerBranches)
        {
            sb.AppendLine($"      - {branch}");
        }

        sb.AppendLine("  paths:");
        sb.AppendLine("    include:");
        sb.AppendLine($"      - {configName}/{resourceName}/*");
        sb.AppendLine("      - .azuredevops/Common/*");
        sb.AppendLine($"      - .azuredevops/{configName}/apps/{appFolderName}/*");
        sb.AppendLine();
    }

    private static void AppendAgentPoolParameter(StringBuilder sb, string? agentPoolName)
    {
        if (!string.IsNullOrWhiteSpace(agentPoolName))
        {
            sb.AppendLine($"    agentPoolName: '{AppNamingHelper.EscapeForSingleQuotedYaml(agentPoolName)}'");
        }
    }
}