namespace InfraFlowSculptor.PipelineGeneration.Generators.App;

/// <summary>
/// Generates the modular Azure DevOps YAML template tree for application CI/CD pipelines.
/// Output is split across <c>.azuredevops/{pipelines,jobs,steps}/</c> following the same
/// layout used for infrastructure pipelines.
/// </summary>
internal static class AppPipelineTemplatesGenerator
{
    /// <summary>
    /// Generates all shared application pipeline template files.
    /// Returned paths are relative to the repository root and prefixed by <c>.azuredevops/</c>.
    /// </summary>
    internal static IReadOnlyDictionary<string, string> GenerateAll()
    {
        return new Dictionary<string, string>
        {
            // ── Atomic step templates ──────────────────────────────────────
            [".azuredevops/steps/app-compute-release-tag.step.yml"] = ComputeReleaseTagStep(),
            [".azuredevops/steps/app-acr-login.step.yml"] = AcrLoginStep(),
            [".azuredevops/steps/app-docker-buildx-push.step.yml"] = DockerBuildxPushStep(),
            [".azuredevops/steps/app-trivy-scan.step.yml"] = TrivyScanStep(),
            [".azuredevops/steps/app-syft-sbom.step.yml"] = SyftSbomStep(),
            [".azuredevops/steps/app-load-metadata.step.yml"] = LoadMetadataStep(),
            [".azuredevops/steps/app-acr-promote.step.yml"] = AcrPromoteStep(),
            [".azuredevops/steps/app-deploy-container.step.yml"] = DeployContainerStep(),
            [".azuredevops/steps/app-deploy-code.step.yml"] = DeployCodeStep(),
            [".azuredevops/steps/app-sdk-setup.step.yml"] = SdkSetupStep(),
            [".azuredevops/steps/app-build-code.step.yml"] = BuildCodeStep(),

            // ── Job templates ──────────────────────────────────────────────
            [".azuredevops/jobs/app-ci-container.job.yml"] = CiContainerJob(),
            [".azuredevops/jobs/app-ci-code.job.yml"] = CiCodeJob(),
            [".azuredevops/jobs/app-release-container.job.yml"] = ReleaseContainerJob(),
            [".azuredevops/jobs/app-release-code.job.yml"] = ReleaseCodeJob(),

            // ── Pipeline templates (extends: targets) ──────────────────────
            [".azuredevops/pipelines/app-ci-container.pipeline.yml"] = CiContainerPipeline(),
            [".azuredevops/pipelines/app-ci-code.pipeline.yml"] = CiCodePipeline(),
            [".azuredevops/pipelines/app-release-container.pipeline.yml"] = ReleaseContainerPipeline(),
            [".azuredevops/pipelines/app-release-code.pipeline.yml"] = ReleaseCodePipeline(),
        };
    }

    // ═══════════════════════════════════════════════════════════════════════
    // STEPS
    // ═══════════════════════════════════════════════════════════════════════

    private static string ComputeReleaseTagStep() => """
        # Compute immutable release tag and write metadata.json — Auto-generated by InfraFlowSculptor

        parameters:
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: imageRepository
            type: string
          - name: configName
            type: string
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: containerRegistryName
            type: string
            default: ''
          - name: includeRegistryMetadata
            type: boolean
            default: false

        steps:
          - bash: |
              set -euo pipefail
              sourceVersion="$(Build.SourceVersion)"
              shortSha=$(echo "$sourceVersion" | cut -c1-7)
              branchName="$(Build.SourceBranchName)"
              sanitizedBranch=$(echo "$branchName" | tr '/_' '-' | tr '[:upper:]' '[:lower:]')
              releaseTagPattern="${{ parameters.imageTagPattern }}"
              releaseTag=${releaseTagPattern//\{buildNumber\}/$(Build.BuildNumber)}
              releaseTag=${releaseTag//\{shortSha\}/$shortSha}
              releaseTag=${releaseTag//\{branch\}/$sanitizedBranch}
              releaseTag=$(echo "$releaseTag" | tr '[:upper:]' '[:lower:]')
              ${{ if parameters.includeRegistryMetadata }}:
                sourceRegistryName="$(containerRegistryName)"
                if [ -z "$sourceRegistryName" ] || [ "$sourceRegistryName" = '$(containerRegistryName)' ]; then sourceRegistryName="${{ parameters.containerRegistryName }}"; fi
                sourceRegistryLoginServer="$(containerRegistryLoginServer)"
                if [ -z "$sourceRegistryLoginServer" ] || [ "$sourceRegistryLoginServer" = '$(containerRegistryLoginServer)' ]; then sourceRegistryLoginServer="${{ parameters.containerRegistryName }}.azurecr.io"; fi
              ${{ if not(parameters.includeRegistryMetadata) }}:
                sourceRegistryName=""
                sourceRegistryLoginServer=""
              mkdir -p "$(Build.ArtifactStagingDirectory)/app-metadata"
              cat > "$(Build.ArtifactStagingDirectory)/app-metadata/metadata.json" <<EOF
              {
                "releaseTag": "$releaseTag",
                "shortSha": "$shortSha",
                "imageRepository": "${{ parameters.imageRepository }}",
                "sourceRegistryName": "$sourceRegistryName",
                "sourceRegistryLoginServer": "$sourceRegistryLoginServer",
                "configName": "${{ parameters.configName }}",
                "resourceName": "${{ parameters.resourceName }}",
                "resourceType": "${{ parameters.resourceType }}",
                "promotionStrategy": "${{ parameters.promotionStrategy }}"
              }
              EOF
              echo "##vso[task.setvariable variable=ReleaseTag]$releaseTag"
              echo "##vso[task.setvariable variable=ShortSha]$shortSha"
            displayName: 'Compute immutable release tag'
        """;

    private static string AcrLoginStep() => """
        # Authenticate to Azure Container Registry — Auto-generated by InfraFlowSculptor

        parameters:
          - name: acrAuthMode
            type: string
            default: 'ServiceConnection'

        steps:
          - ${{ if eq(parameters.acrAuthMode, 'AdminCredentials') }}:
            - bash: |
                set -euo pipefail
                echo "$(containerRegistryPassword)" | docker login "$(containerRegistryLoginServer)" --username "$(containerRegistryUsername)" --password-stdin
              displayName: 'Authenticate to ACR with admin credentials'

          - ${{ if ne(parameters.acrAuthMode, 'AdminCredentials') }}:
            - task: Docker@2
              displayName: 'Authenticate to ACR'
              inputs:
                command: login
                containerRegistry: $(containerRegistryServiceConnection)
        """;

    private static string DockerBuildxPushStep() => """
        # Build and push immutable Docker image tags — Auto-generated by InfraFlowSculptor

        parameters:
          - name: dockerfilePath
            type: string
            default: 'Dockerfile'
          - name: buildContext
            type: string
            default: '.'
          - name: imageRepository
            type: string
          - name: containerRegistryName
            type: string
            default: ''

        steps:
          - bash: |
              set -euo pipefail
              registryLoginServer="$(containerRegistryLoginServer)"
              if [ -z "$registryLoginServer" ] || [ "$registryLoginServer" = '$(containerRegistryLoginServer)' ]; then registryLoginServer="${{ parameters.containerRegistryName }}.azurecr.io"; fi
              docker buildx inspect ifs-builder >/dev/null 2>&1 || docker buildx create --name ifs-builder --use >/dev/null
              docker buildx use ifs-builder >/dev/null
              docker buildx build \
                --file "${{ parameters.dockerfilePath }}" \
                --label "org.opencontainers.image.revision=$(Build.SourceVersion)" \
                --label "org.opencontainers.image.version=$(ReleaseTag)" \
                --label "org.opencontainers.image.source=$(Build.Repository.Uri)" \
                --label "org.opencontainers.image.created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
                --tag "${registryLoginServer}/${{ parameters.imageRepository }}:$(ReleaseTag)" \
                --tag "${registryLoginServer}/${{ parameters.imageRepository }}:sha-$(ShortSha)" \
                --push \
                "${{ parameters.buildContext }}"
            displayName: 'Build and push immutable image tags'
        """;

    private static string TrivyScanStep() => """
        # Scan container image with Trivy — Auto-generated by InfraFlowSculptor

        parameters:
          - name: imageRepository
            type: string
          - name: containerRegistryName
            type: string
            default: ''
          - name: severity
            type: string
            default: 'HIGH,CRITICAL'

        steps:
          - bash: |
              set -euo pipefail
              toolDir="$(Agent.TempDirectory)/supply-chain-tools"
              mkdir -p "$toolDir"
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b "$toolDir"
              echo "##vso[task.prependpath]$toolDir"
            displayName: 'Install Trivy'

          - bash: |
              set -euo pipefail
              registryLoginServer="$(containerRegistryLoginServer)"
              if [ -z "$registryLoginServer" ] || [ "$registryLoginServer" = '$(containerRegistryLoginServer)' ]; then registryLoginServer="${{ parameters.containerRegistryName }}.azurecr.io"; fi
              mkdir -p "$(Build.ArtifactStagingDirectory)/supply-chain"
              trivy image --scanners vuln --severity ${{ parameters.severity }} --ignore-unfixed --format json --output "$(Build.ArtifactStagingDirectory)/supply-chain/trivy-report.json" --exit-code 1 "${registryLoginServer}/${{ parameters.imageRepository }}:$(ReleaseTag)"
            displayName: 'Scan image with Trivy'
        """;

    private static string SyftSbomStep() => """
        # Generate CycloneDX SBOM with Syft — Auto-generated by InfraFlowSculptor

        parameters:
          - name: imageRepository
            type: string
          - name: containerRegistryName
            type: string
            default: ''

        steps:
          - bash: |
              set -euo pipefail
              toolDir="$(Agent.TempDirectory)/supply-chain-tools"
              mkdir -p "$toolDir"
              curl -sfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b "$toolDir"
              echo "##vso[task.prependpath]$toolDir"
              registryLoginServer="$(containerRegistryLoginServer)"
              if [ -z "$registryLoginServer" ] || [ "$registryLoginServer" = '$(containerRegistryLoginServer)' ]; then registryLoginServer="${{ parameters.containerRegistryName }}.azurecr.io"; fi
              mkdir -p "$(Build.ArtifactStagingDirectory)/supply-chain"
              syft "${registryLoginServer}/${{ parameters.imageRepository }}:$(ReleaseTag)" -o cyclonedx-json > "$(Build.ArtifactStagingDirectory)/supply-chain/sbom.cyclonedx.json"
            displayName: 'Generate SBOM'
        """;

    private static string LoadMetadataStep() => """
        # Load CI release metadata from artifact — Auto-generated by InfraFlowSculptor

        steps:
          - download: ci
            artifact: app-metadata
            displayName: 'Download CI metadata'

          - pwsh: |
              $metadataPath = '$(Pipeline.Workspace)/app-metadata/metadata.json'
              if (-not (Test-Path -LiteralPath $metadataPath)) {
                  throw "Metadata artifact not found: $metadataPath"
              }
              $metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json
              Write-Host "##vso[task.setvariable variable=ReleaseTag]$($metadata.releaseTag)"
              Write-Host "##vso[task.setvariable variable=ImageRepository]$($metadata.imageRepository)"
              Write-Host "##vso[task.setvariable variable=SourceRegistryName]$($metadata.sourceRegistryName)"
              Write-Host "##vso[task.setvariable variable=SourceRegistryLoginServer]$($metadata.sourceRegistryLoginServer)"
            displayName: 'Load release metadata'
        """;

    private static string AcrPromoteStep() => """
        # Promote container image between ACR registries — Auto-generated by InfraFlowSculptor

        parameters:
          - name: imageRepository
            type: string
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: envShortName
            type: string

        steps:
          - task: AzureCLI@2
            displayName: 'Promote image in ACR'
            inputs:
              azureSubscription: $(azureResourceManagerConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -euo pipefail
                imageRepository="$(ImageRepository)"
                if [ -z "$imageRepository" ] || [ "$imageRepository" = '$(ImageRepository)' ]; then imageRepository="${{ parameters.imageRepository }}"; fi
                if [ "${{ parameters.promotionStrategy }}" = "AcrImport" ] && [ "$(containerRegistryLoginServer)" != "$(SourceRegistryLoginServer)" ]; then
                  az acr import --name "$(containerRegistryName)" --source "$(SourceRegistryLoginServer)/${imageRepository}:$(ReleaseTag)" --image "${imageRepository}:$(ReleaseTag)" --force
                fi
                az acr import --name "$(containerRegistryName)" --source "$(containerRegistryLoginServer)/${imageRepository}:$(ReleaseTag)" --image "${imageRepository}:env-${{ parameters.envShortName }}" --force
        """;

    private static string DeployContainerStep() => """
        # Deploy container image to compute resource — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceType
            type: string
          - name: imageRepository
            type: string

        steps:
          - ${{ if eq(parameters.resourceType, 'ContainerApp') }}:
            - task: AzureCLI@2
              displayName: 'Deploy image to Container App'
              inputs:
                azureSubscription: $(azureResourceManagerConnection)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  set -euo pipefail
                  imageRepository="$(ImageRepository)"
                  if [ -z "$imageRepository" ] || [ "$imageRepository" = '$(ImageRepository)' ]; then imageRepository="${{ parameters.imageRepository }}"; fi
                  az containerapp update --name "$(containerAppName)" --resource-group "$(resourceGroupName)" --image "$(containerRegistryLoginServer)/${imageRepository}:$(ReleaseTag)"

          - ${{ if eq(parameters.resourceType, 'WebApp') }}:
            - task: AzureWebApp@1
              displayName: 'Deploy container image to Web App'
              inputs:
                azureSubscription: $(azureResourceManagerConnection)
                appType: webAppContainer
                appName: $(webAppName)
                containers: $(containerRegistryLoginServer)/$(ImageRepository):$(ReleaseTag)

          - ${{ if eq(parameters.resourceType, 'FunctionApp') }}:
            - task: AzureFunctionApp@2
              displayName: 'Deploy container image to Function App'
              inputs:
                azureSubscription: $(azureResourceManagerConnection)
                appType: functionAppContainer
                appName: $(functionAppName)
                containers: $(containerRegistryLoginServer)/$(ImageRepository):$(ReleaseTag)
        """;

    private static string DeployCodeStep() => """
        # Deploy application package to compute resource — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceType
            type: string

        steps:
          - download: ci
            artifact: application-package
            displayName: 'Download application package'

          - ${{ if eq(parameters.resourceType, 'WebApp') }}:
            - task: AzureWebApp@1
              displayName: 'Deploy package to Web App'
              inputs:
                azureSubscription: $(azureResourceManagerConnection)
                appType: webApp
                appName: $(webAppName)
                package: $(Pipeline.Workspace)/application-package

          - ${{ if eq(parameters.resourceType, 'FunctionApp') }}:
            - task: AzureFunctionApp@2
              displayName: 'Deploy package to Function App'
              inputs:
                azureSubscription: $(azureResourceManagerConnection)
                appType: functionApp
                appName: $(functionAppName)
                package: $(Pipeline.Workspace)/application-package
        """;

    private static string SdkSetupStep() => """
        # Install runtime SDK based on stack — Auto-generated by InfraFlowSculptor

        parameters:
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: runtimeVersion
            type: string
            default: '8.0'

        steps:
          - ${{ if or(eq(parameters.runtimeStack, 'DOTNETCORE'), eq(parameters.runtimeStack, 'DOTNET')) }}:
            - task: UseDotNet@2
              displayName: 'Setup .NET SDK'
              inputs:
                packageType: sdk
                version: ${{ parameters.runtimeVersion }}.x

          - ${{ if or(eq(parameters.runtimeStack, 'NODE'), eq(parameters.runtimeStack, 'NODEJS')) }}:
            - task: UseNode@1
              displayName: 'Setup Node.js'
              inputs:
                version: ${{ parameters.runtimeVersion }}.x

          - ${{ if eq(parameters.runtimeStack, 'PYTHON') }}:
            - task: UsePythonVersion@0
              displayName: 'Setup Python'
              inputs:
                versionSpec: ${{ parameters.runtimeVersion }}

          - ${{ if eq(parameters.runtimeStack, 'JAVA') }}:
            - task: JavaToolInstaller@0
              displayName: 'Setup Java'
              inputs:
                versionSpec: ${{ parameters.runtimeVersion }}
                jdkArchitectureOption: x64
                jdkSourceOption: PreInstalled
        """;

    private static string BuildCodeStep() => """
        # Build, test and package application source — Auto-generated by InfraFlowSculptor

        parameters:
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: sourcePath
            type: string
            default: '.'
          - name: testCommand
            type: string
            default: ''
          - name: buildCommand
            type: string
            default: ''

        steps:
          # ── Test (custom command, runs before build) ─────────────────
          - ${{ if ne(parameters.testCommand, '') }}:
            - pwsh: |
                ${{ parameters.testCommand }}
              displayName: 'Run application tests'
              workingDirectory: ${{ parameters.sourcePath }}

          # ── Build (custom command — overrides defaults) ──────────────
          - ${{ if ne(parameters.buildCommand, '') }}:
            - pwsh: |
                ${{ parameters.buildCommand }}
              displayName: 'Build and package application'
              workingDirectory: ${{ parameters.sourcePath }}

          # ── Build (.NET default) ─────────────────────────────────────
          - ${{ if and(eq(parameters.buildCommand, ''), or(eq(parameters.runtimeStack, 'DOTNETCORE'), eq(parameters.runtimeStack, 'DOTNET'))) }}:
            - pwsh: |
                dotnet restore
                dotnet build --configuration Release --no-restore
              displayName: 'Restore and build .NET application'
              workingDirectory: ${{ parameters.sourcePath }}

            - pwsh: |
                dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --results-directory "$(Common.TestResultsDirectory)" --collect "XPlat Code Coverage"
              displayName: 'Run automated tests'
              workingDirectory: ${{ parameters.sourcePath }}

            - task: PublishTestResults@2
              displayName: 'Publish test results'
              inputs:
                testResultsFormat: VSTest
                testResultsFiles: '$(Common.TestResultsDirectory)/**/*.trx'
                failTaskOnFailedTests: true

            - task: PublishCodeCoverageResults@2
              displayName: 'Publish code coverage'
              inputs:
                codeCoverageTool: Cobertura
                summaryFileLocation: '$(Common.TestResultsDirectory)/**/coverage.cobertura.xml'
                failIfCoverageEmpty: false

            - pwsh: |
                dotnet publish --configuration Release --no-build --output "$(Build.ArtifactStagingDirectory)/application-package"
              displayName: 'Publish application package'
              workingDirectory: ${{ parameters.sourcePath }}

          # ── Build (Node.js default) ──────────────────────────────────
          - ${{ if and(eq(parameters.buildCommand, ''), or(eq(parameters.runtimeStack, 'NODE'), eq(parameters.runtimeStack, 'NODEJS'))) }}:
            - bash: |
                set -euo pipefail
                npm ci
                ${{ if eq(parameters.testCommand, '') }}:
                  npm run test --if-present
                npm run build
                mkdir -p "$(Build.ArtifactStagingDirectory)/application-package"
                if [ -d dist ]; then cp -R dist/. "$(Build.ArtifactStagingDirectory)/application-package"; elif [ -d build ]; then cp -R build/. "$(Build.ArtifactStagingDirectory)/application-package"; else cp -R . "$(Build.ArtifactStagingDirectory)/application-package"; fi
              displayName: 'Build and package Node.js application'
              workingDirectory: ${{ parameters.sourcePath }}

          # ── Build (Python default) ───────────────────────────────────
          - ${{ if and(eq(parameters.buildCommand, ''), eq(parameters.runtimeStack, 'PYTHON')) }}:
            - bash: |
                set -euo pipefail
                python -m pip install -r requirements.txt
                mkdir -p "$(Build.ArtifactStagingDirectory)/application-package"
                cp -R . "$(Build.ArtifactStagingDirectory)/application-package"
              displayName: 'Build and package Python application'
              workingDirectory: ${{ parameters.sourcePath }}
        """;

    // ═══════════════════════════════════════════════════════════════════════
    // JOBS
    // ═══════════════════════════════════════════════════════════════════════

    private static string CiContainerJob() => """
        # CI job for container-mode applications — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceName
            type: string
          - name: configName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: dockerfilePath
            type: string
            default: 'Dockerfile'
          - name: buildContext
            type: string
            default: '.'
          - name: containerRegistryName
            type: string
            default: ''
          - name: acrAuthMode
            type: string
            default: 'ServiceConnection'
          - name: enableSecurityScans
            type: boolean
            default: true
          - name: promotionStrategy
            type: string
            default: 'AcrImport'

        jobs:
          - job: BuildAndPush
            displayName: 'Build and push immutable image'
            steps:
              - checkout: self
                fetchDepth: 0

              - template: ../steps/app-compute-release-tag.step.yml
                parameters:
                  imageTagPattern: ${{ parameters.imageTagPattern }}
                  imageRepository: ${{ parameters.imageRepository }}
                  configName: ${{ parameters.configName }}
                  resourceName: ${{ parameters.resourceName }}
                  resourceType: ${{ parameters.resourceType }}
                  promotionStrategy: ${{ parameters.promotionStrategy }}
                  containerRegistryName: ${{ parameters.containerRegistryName }}
                  includeRegistryMetadata: true

              - template: ../steps/app-acr-login.step.yml
                parameters:
                  acrAuthMode: ${{ parameters.acrAuthMode }}

              - template: ../steps/app-docker-buildx-push.step.yml
                parameters:
                  dockerfilePath: ${{ parameters.dockerfilePath }}
                  buildContext: ${{ parameters.buildContext }}
                  imageRepository: ${{ parameters.imageRepository }}
                  containerRegistryName: ${{ parameters.containerRegistryName }}

              - ${{ if parameters.enableSecurityScans }}:
                - template: ../steps/app-trivy-scan.step.yml
                  parameters:
                    imageRepository: ${{ parameters.imageRepository }}
                    containerRegistryName: ${{ parameters.containerRegistryName }}

                - template: ../steps/app-syft-sbom.step.yml
                  parameters:
                    imageRepository: ${{ parameters.imageRepository }}
                    containerRegistryName: ${{ parameters.containerRegistryName }}

              - task: PublishPipelineArtifact@1
                displayName: 'Publish app metadata'
                inputs:
                  targetPath: '$(Build.ArtifactStagingDirectory)/app-metadata'
                  artifact: 'app-metadata'

              - ${{ if parameters.enableSecurityScans }}:
                - task: PublishPipelineArtifact@1
                  displayName: 'Publish supply chain reports'
                  inputs:
                    targetPath: '$(Build.ArtifactStagingDirectory)/supply-chain'
                    artifact: 'supply-chain'
        """;

    private static string CiCodeJob() => """
        # CI job for code-mode applications — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceName
            type: string
          - name: configName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: runtimeVersion
            type: string
            default: '8.0'
          - name: sourcePath
            type: string
            default: '.'
          - name: testCommand
            type: string
            default: ''
          - name: buildCommand
            type: string
            default: ''
          - name: promotionStrategy
            type: string
            default: 'AcrImport'

        jobs:
          - job: BuildAndPublish
            displayName: 'Build application package'
            steps:
              - checkout: self
                fetchDepth: 0

              - template: ../steps/app-compute-release-tag.step.yml
                parameters:
                  imageTagPattern: ${{ parameters.imageTagPattern }}
                  imageRepository: ${{ parameters.imageRepository }}
                  configName: ${{ parameters.configName }}
                  resourceName: ${{ parameters.resourceName }}
                  resourceType: ${{ parameters.resourceType }}
                  promotionStrategy: ${{ parameters.promotionStrategy }}
                  includeRegistryMetadata: false

              - template: ../steps/app-sdk-setup.step.yml
                parameters:
                  runtimeStack: ${{ parameters.runtimeStack }}
                  runtimeVersion: ${{ parameters.runtimeVersion }}

              - template: ../steps/app-build-code.step.yml
                parameters:
                  runtimeStack: ${{ parameters.runtimeStack }}
                  sourcePath: ${{ parameters.sourcePath }}
                  testCommand: ${{ parameters.testCommand }}
                  buildCommand: ${{ parameters.buildCommand }}

              - task: PublishPipelineArtifact@1
                displayName: 'Publish app metadata'
                inputs:
                  targetPath: '$(Build.ArtifactStagingDirectory)/app-metadata'
                  artifact: 'app-metadata'

              - task: PublishPipelineArtifact@1
                displayName: 'Publish application package'
                inputs:
                  targetPath: '$(Build.ArtifactStagingDirectory)/application-package'
                  artifact: 'application-package'
        """;

    private static string ReleaseContainerJob() => """
        # Release deployment job (per environment) for container-mode apps — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: envShortName
            type: string
          - name: envName
            type: string

        jobs:
          - deployment: Deploy_${{ parameters.envShortName }}
            displayName: 'Deploy ${{ parameters.resourceName }} to ${{ parameters.envName }}'
            environment: ${{ parameters.envName }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: none

                    - template: ../steps/app-load-metadata.step.yml

                    - template: ../steps/app-acr-promote.step.yml
                      parameters:
                        imageRepository: ${{ parameters.imageRepository }}
                        promotionStrategy: ${{ parameters.promotionStrategy }}
                        envShortName: ${{ parameters.envShortName }}

                    - template: ../steps/app-deploy-container.step.yml
                      parameters:
                        resourceType: ${{ parameters.resourceType }}
                        imageRepository: ${{ parameters.imageRepository }}
        """;

    private static string ReleaseCodeJob() => """
        # Release deployment job (per environment) for code-mode apps — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: envShortName
            type: string
          - name: envName
            type: string

        jobs:
          - deployment: Deploy_${{ parameters.envShortName }}
            displayName: 'Deploy ${{ parameters.resourceName }} to ${{ parameters.envName }}'
            environment: ${{ parameters.envName }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: none

                    - template: ../steps/app-load-metadata.step.yml

                    - template: ../steps/app-deploy-code.step.yml
                      parameters:
                        resourceType: ${{ parameters.resourceType }}
        """;

    // ═══════════════════════════════════════════════════════════════════════
    // PIPELINES (extends: targets)
    // ═══════════════════════════════════════════════════════════════════════

    private static string CiContainerPipeline() => """
        # CI pipeline template for container-mode apps — Auto-generated by InfraFlowSculptor
        # Usage: extends: template: ../../.azuredevops/pipelines/app-ci-container.pipeline.yml

        parameters:
          - name: resourceName
            type: string
          - name: configName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: dockerfilePath
            type: string
            default: 'Dockerfile'
          - name: buildContext
            type: string
            default: '.'
          - name: containerRegistryName
            type: string
            default: ''
          - name: acrAuthMode
            type: string
            default: 'ServiceConnection'
          - name: enableSecurityScans
            type: boolean
            default: true
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: buildSourceEnvVariablesPath
            type: string
            default: ''
          - name: variableGroups
            type: object
            default: []
          - name: agentPoolName
            type: string
            default: ''

        pool:
          ${{ if eq(parameters.agentPoolName, '') }}:
            vmImage: 'ubuntu-latest'
          ${{ if ne(parameters.agentPoolName, '') }}:
            name: '${{ parameters.agentPoolName }}'

        stages:
          - stage: Build
            displayName: 'Build, scan and publish image'
            ${{ if ne(parameters.buildSourceEnvVariablesPath, '') }}:
              variables:
                - template: ${{ parameters.buildSourceEnvVariablesPath }}
                - ${{ each group in parameters.variableGroups }}:
                  - group: ${{ group }}
            jobs:
              - template: ../jobs/app-ci-container.job.yml
                parameters:
                  resourceName: ${{ parameters.resourceName }}
                  configName: ${{ parameters.configName }}
                  resourceType: ${{ parameters.resourceType }}
                  imageRepository: ${{ parameters.imageRepository }}
                  imageTagPattern: ${{ parameters.imageTagPattern }}
                  dockerfilePath: ${{ parameters.dockerfilePath }}
                  buildContext: ${{ parameters.buildContext }}
                  containerRegistryName: ${{ parameters.containerRegistryName }}
                  acrAuthMode: ${{ parameters.acrAuthMode }}
                  enableSecurityScans: ${{ parameters.enableSecurityScans }}
                  promotionStrategy: ${{ parameters.promotionStrategy }}
        """;

    private static string CiCodePipeline() => """
        # CI pipeline template for code-mode apps — Auto-generated by InfraFlowSculptor
        # Usage: extends: template: ../../.azuredevops/pipelines/app-ci-code.pipeline.yml

        parameters:
          - name: resourceName
            type: string
          - name: configName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: runtimeVersion
            type: string
            default: '8.0'
          - name: sourcePath
            type: string
            default: '.'
          - name: testCommand
            type: string
            default: ''
          - name: buildCommand
            type: string
            default: ''
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: agentPoolName
            type: string
            default: ''

        pool:
          ${{ if eq(parameters.agentPoolName, '') }}:
            vmImage: 'ubuntu-latest'
          ${{ if ne(parameters.agentPoolName, '') }}:
            name: '${{ parameters.agentPoolName }}'

        stages:
          - stage: Build
            displayName: 'Build, test and publish package'
            jobs:
              - template: ../jobs/app-ci-code.job.yml
                parameters:
                  resourceName: ${{ parameters.resourceName }}
                  configName: ${{ parameters.configName }}
                  resourceType: ${{ parameters.resourceType }}
                  imageRepository: ${{ parameters.imageRepository }}
                  imageTagPattern: ${{ parameters.imageTagPattern }}
                  runtimeStack: ${{ parameters.runtimeStack }}
                  runtimeVersion: ${{ parameters.runtimeVersion }}
                  sourcePath: ${{ parameters.sourcePath }}
                  testCommand: ${{ parameters.testCommand }}
                  buildCommand: ${{ parameters.buildCommand }}
                  promotionStrategy: ${{ parameters.promotionStrategy }}
        """;

    private static string ReleaseContainerPipeline() => """
        # Release pipeline template for container-mode apps — Auto-generated by InfraFlowSculptor
        # Usage: extends: template: ../../.azuredevops/pipelines/app-release-container.pipeline.yml
        #
        # Each environment object must contain:
        #   shortName, name, variablesPath, variableGroups (list of strings)

        parameters:
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: agentPoolName
            type: string
            default: ''
          - name: environments
            type: object
            default: []

        pool:
          ${{ if eq(parameters.agentPoolName, '') }}:
            vmImage: 'ubuntu-latest'
          ${{ if ne(parameters.agentPoolName, '') }}:
            name: '${{ parameters.agentPoolName }}'

        stages:
          - ${{ each env in parameters.environments }}:
            - stage: Deploy_${{ env.shortName }}
              displayName: 'Promote and deploy to ${{ env.name }}'
              lockBehavior: sequential
              variables:
                - template: ${{ env.variablesPath }}
                - ${{ each group in env.variableGroups }}:
                  - group: ${{ group }}
              jobs:
                - template: ../jobs/app-release-container.job.yml
                  parameters:
                    resourceName: ${{ parameters.resourceName }}
                    resourceType: ${{ parameters.resourceType }}
                    imageRepository: ${{ parameters.imageRepository }}
                    promotionStrategy: ${{ parameters.promotionStrategy }}
                    envShortName: ${{ env.shortName }}
                    envName: ${{ env.name }}
        """;

    private static string ReleaseCodePipeline() => """
        # Release pipeline template for code-mode apps — Auto-generated by InfraFlowSculptor
        # Usage: extends: template: ../../.azuredevops/pipelines/app-release-code.pipeline.yml

        parameters:
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: agentPoolName
            type: string
            default: ''
          - name: environments
            type: object
            default: []

        pool:
          ${{ if eq(parameters.agentPoolName, '') }}:
            vmImage: 'ubuntu-latest'
          ${{ if ne(parameters.agentPoolName, '') }}:
            name: '${{ parameters.agentPoolName }}'

        stages:
          - ${{ each env in parameters.environments }}:
            - stage: Deploy_${{ env.shortName }}
              displayName: 'Deploy to ${{ env.name }}'
              lockBehavior: sequential
              variables:
                - template: ${{ env.variablesPath }}
                - ${{ each group in env.variableGroups }}:
                  - group: ${{ group }}
              jobs:
                - template: ../jobs/app-release-code.job.yml
                  parameters:
                    resourceName: ${{ parameters.resourceName }}
                    resourceType: ${{ parameters.resourceType }}
                    envShortName: ${{ env.shortName }}
                    envName: ${{ env.name }}
        """;
}
