using System.Text;
using InfraFlowSculptor.Domain.Common.ValueObjects;
using InfraFlowSculptor.GenerationCore;
using InfraFlowSculptor.GenerationCore.Models;

namespace InfraFlowSculptor.PipelineGeneration.Generators.App;

using static PipelineGenerationEngine;

/// <summary>
/// Shared helper methods for application pipeline generators.
/// Provides reusable YAML building blocks for CI and release pipelines.
/// </summary>
internal static class AppPipelineYamlHelper
{
    /// <summary>
    /// Resolves the path to environment variable files based on mono-repo or single-config mode.
    /// </summary>
    /// <param name="envKey">The environment short name (lowercase).</param>
    /// <param name="isMonoRepo">Whether the project uses mono-repo structure.</param>
    /// <returns>The YAML template path for the environment variables file.</returns>
    public static string GetEnvironmentVariablesPath(string envKey, bool isMonoRepo)
    {
        return isMonoRepo
            ? $"../.azuredevops/variables/{envKey}.variables.yml"
            : $"variables/{envKey}.yml";
    }

    /// <summary>
    /// Appends the CI pipeline header with trigger configuration and root-level pool.
    /// </summary>
    public static void AppendCiHeader(StringBuilder sb, string resourceName, string configName, string? agentPoolName = null)
    {
        configName = PathSanitizer.Sanitize(configName);
        resourceName = PathSanitizer.Sanitize(resourceName);

        sb.AppendLine($"# CI Application Pipeline for {resourceName} — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(date:yyyyMMdd).$(Rev:r)");
        sb.AppendLine();
        sb.AppendLine("trigger:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        sb.AppendLine("      - main");
        sb.AppendLine("      - develop");
        sb.AppendLine("  paths:");
        sb.AppendLine("    include:");
        sb.AppendLine($"      - {configName}/{resourceName}/*");
        sb.AppendLine();
        AppendPool(sb, agentPoolName, "");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the release pipeline header (trigger: none, manually triggered) with root-level pool.
    /// </summary>
    public static void AppendReleaseHeader(StringBuilder sb, string resourceName, string? agentPoolName = null)
    {
        sb.AppendLine($"# Release Application Pipeline for {resourceName} — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(date:yyyyMMdd).$(Rev:r)");
        sb.AppendLine();
        sb.AppendLine("trigger: none");
        sb.AppendLine();
        AppendPool(sb, agentPoolName, "");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends a Build stage for container-based pipelines (Docker build + push to ACR).
    /// </summary>
    public static void AppendContainerBuildStage(
        StringBuilder sb,
        AppPipelineGenerationRequest request)
    {
        var dockerfile = request.DockerfilePath ?? "Dockerfile";
        var imageName = request.DockerImageName ?? request.ResourceName.ToLowerInvariant();
        var loginServer = !string.IsNullOrWhiteSpace(request.ContainerRegistryName)
            ? $"{request.ContainerRegistryName}.azurecr.io"
            : "$(containerRegistryLoginServer)";
        var fullImageName = $"{loginServer}/{imageName}";
        var usesAdminCredentials = string.Equals(
            request.AcrAuthMode,
            AcrAuthMode.AcrAuthModeType.AdminCredentials.ToString(),
            StringComparison.OrdinalIgnoreCase);

        sb.AppendLine("stages:");
        sb.AppendLine("  - stage: Build");
        sb.AppendLine($"    displayName: 'Build & Push {request.ResourceName} Image'");
        sb.AppendLine("    jobs:");
        sb.AppendLine("      - job: BuildAndPush");
        sb.AppendLine("        displayName: 'Build Docker Image'");
        sb.AppendLine("        steps:");
        sb.AppendLine("          - checkout: self");
        sb.AppendLine("            fetchDepth: 1");
        sb.AppendLine();

        if (usesAdminCredentials)
        {
            sb.AppendLine("          - script: |");
            sb.AppendLine($"              echo \"$(containerRegistryPassword)\" | docker login {loginServer} --username \"$(containerRegistryUsername)\" --password-stdin");
            sb.AppendLine("            displayName: 'Login to ACR with Admin Credentials'");
            sb.AppendLine();
            sb.AppendLine("          - script: |");
            sb.AppendLine($"              docker build --file \"{dockerfile}\" --tag {fullImageName}:$(Build.BuildId) --tag {fullImageName}:latest .");
            sb.AppendLine($"              docker push {fullImageName}:$(Build.BuildId)");
            sb.AppendLine($"              docker push {fullImageName}:latest");
            sb.AppendLine("            displayName: 'Build & Push Docker Image'");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("          - task: Docker@2");
        sb.AppendLine("            displayName: 'Build Docker Image'");
        sb.AppendLine("            inputs:");
        sb.AppendLine("              containerRegistry: $(containerRegistryServiceConnection)");
        sb.AppendLine($"              repository: {imageName}");
        sb.AppendLine("              command: buildAndPush");
        sb.AppendLine($"              Dockerfile: {dockerfile}");
        sb.AppendLine("              tags: |");
        sb.AppendLine("                $(Build.BuildId)");
        sb.AppendLine("                latest");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends a Build stage for code-based pipelines (restore, build, publish, artifact).
    /// </summary>
    public static void AppendCodeBuildStage(
        StringBuilder sb,
        string resourceName,
        string? runtimeStack,
        string? runtimeVersion,
        string? sourceCodePath,
        string? buildCommand)
    {
        var srcPath = sourceCodePath ?? ".";

        sb.AppendLine("stages:");
        sb.AppendLine("  - stage: Build");
        sb.AppendLine($"    displayName: 'Build {resourceName}'");
        sb.AppendLine("    jobs:");
        sb.AppendLine("      - job: BuildAndPublish");
        sb.AppendLine("        displayName: 'Build & Publish Artifact'");
        sb.AppendLine("        steps:");
        sb.AppendLine("          - checkout: self");
        sb.AppendLine("            fetchDepth: 1");
        sb.AppendLine();

        // SDK setup based on runtime stack
        AppendSdkSetupStep(sb, runtimeStack, runtimeVersion);

        if (!string.IsNullOrEmpty(buildCommand))
        {
            sb.AppendLine("          - script: |");
            sb.AppendLine($"              {buildCommand}");
            sb.AppendLine("            displayName: 'Custom Build Command'");
            sb.AppendLine($"            workingDirectory: {srcPath}");
            sb.AppendLine();
        }
        else
        {
            AppendDefaultBuildSteps(sb, runtimeStack, srcPath);
        }

        sb.AppendLine("          - task: PublishPipelineArtifact@1");
        sb.AppendLine("            displayName: 'Publish Build Artifact'");
        sb.AppendLine("            inputs:");
        sb.AppendLine($"              targetPath: $(Build.ArtifactStagingDirectory)/drop");
        sb.AppendLine($"              artifactName: drop-{resourceName}");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends per-environment deployment stages for container-based Azure Container App.
    /// </summary>
    public static void AppendContainerAppDeployStages(
        StringBuilder sb,
        AppPipelineGenerationRequest request)
    {
        var imageName = request.DockerImageName ?? request.ResourceName.ToLowerInvariant();

        for (var i = 0; i < request.Environments.Count; i++)
        {
            var env = request.Environments[i];
            var envKey = env.ShortName.ToLowerInvariant();
            var dependsOn = i == 0 ? "Build" : $"Deploy_{request.Environments[i - 1].ShortName.ToLowerInvariant()}";

            sb.AppendLine($"  - stage: Deploy_{envKey}");
            sb.AppendLine($"    displayName: 'Deploy to {env.Name}'");
            sb.AppendLine($"    dependsOn: {dependsOn}");
            sb.AppendLine("    variables:");
            AppendEnvironmentVariables(sb, env, request);
            sb.AppendLine("    jobs:");
            sb.AppendLine($"      - deployment: Deploy_{envKey}");
            sb.AppendLine($"        displayName: 'Deploy {request.ResourceName} to {env.Name}'");
            sb.AppendLine($"        environment: {env.Name}");
            sb.AppendLine("        strategy:");
            sb.AppendLine("          runOnce:");
            sb.AppendLine("            deploy:");
            sb.AppendLine("              steps:");
            sb.AppendLine("                - task: AzureCLI@2");
            sb.AppendLine($"                  displayName: 'Update Container App Revision'");
            sb.AppendLine("                  inputs:");
            sb.AppendLine("                    azureSubscription: $(azureResourceManagerConnection)");
            sb.AppendLine("                    scriptType: bash");
            sb.AppendLine("                    scriptLocation: inlineScript");
            sb.AppendLine("                    inlineScript: |");
            sb.AppendLine($"                      az containerapp update \\");
            sb.AppendLine($"                        --name $(containerAppName) \\");
            sb.AppendLine($"                        --resource-group $(resourceGroupName) \\");
            sb.AppendLine($"                        --image $(containerRegistryLoginServer)/{imageName}:$(Build.BuildId)");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Appends per-environment deployment stages for container-based Web App.
    /// </summary>
    public static void AppendWebAppContainerDeployStages(
        StringBuilder sb,
        AppPipelineGenerationRequest request)
    {
        var imageName = request.DockerImageName ?? request.ResourceName.ToLowerInvariant();

        for (var i = 0; i < request.Environments.Count; i++)
        {
            var env = request.Environments[i];
            var envKey = env.ShortName.ToLowerInvariant();
            var dependsOn = i == 0 ? "Build" : $"Deploy_{request.Environments[i - 1].ShortName.ToLowerInvariant()}";

            sb.AppendLine($"  - stage: Deploy_{envKey}");
            sb.AppendLine($"    displayName: 'Deploy to {env.Name}'");
            sb.AppendLine($"    dependsOn: {dependsOn}");
            sb.AppendLine("    variables:");
            AppendEnvironmentVariables(sb, env, request);
            sb.AppendLine("    jobs:");
            sb.AppendLine($"      - deployment: Deploy_{envKey}");
            sb.AppendLine($"        displayName: 'Deploy {request.ResourceName} to {env.Name}'");
            sb.AppendLine($"        environment: {env.Name}");
            sb.AppendLine("        strategy:");
            sb.AppendLine("          runOnce:");
            sb.AppendLine("            deploy:");
            sb.AppendLine("              steps:");
            sb.AppendLine("                - task: AzureWebApp@1");
            sb.AppendLine($"                  displayName: 'Deploy Container to Web App'");
            sb.AppendLine("                  inputs:");
            sb.AppendLine("                    azureSubscription: $(azureResourceManagerConnection)");
            sb.AppendLine("                    appType: webAppContainer");
            sb.AppendLine("                    appName: $(webAppName)");
            sb.AppendLine($"                    containers: $(containerRegistryLoginServer)/{imageName}:$(Build.BuildId)");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Appends per-environment deployment stages for code-based Web App.
    /// </summary>
    public static void AppendWebAppCodeDeployStages(
        StringBuilder sb,
        AppPipelineGenerationRequest request)
    {
        for (var i = 0; i < request.Environments.Count; i++)
        {
            var env = request.Environments[i];
            var envKey = env.ShortName.ToLowerInvariant();
            var dependsOn = i == 0 ? "Build" : $"Deploy_{request.Environments[i - 1].ShortName.ToLowerInvariant()}";

            sb.AppendLine($"  - stage: Deploy_{envKey}");
            sb.AppendLine($"    displayName: 'Deploy to {env.Name}'");
            sb.AppendLine($"    dependsOn: {dependsOn}");
            sb.AppendLine("    variables:");
            AppendEnvironmentVariables(sb, env, request);
            sb.AppendLine("    jobs:");
            sb.AppendLine($"      - deployment: Deploy_{envKey}");
            sb.AppendLine($"        displayName: 'Deploy {request.ResourceName} to {env.Name}'");
            sb.AppendLine($"        environment: {env.Name}");
            sb.AppendLine("        strategy:");
            sb.AppendLine("          runOnce:");
            sb.AppendLine("            deploy:");
            sb.AppendLine("              steps:");
            sb.AppendLine("                - task: DownloadPipelineArtifact@2");
            sb.AppendLine("                  displayName: 'Download Build Artifact'");
            sb.AppendLine("                  inputs:");
            sb.AppendLine($"                    artifactName: drop-{request.ResourceName}");
            sb.AppendLine("                    targetPath: $(Pipeline.Workspace)/drop");
            sb.AppendLine();
            sb.AppendLine("                - task: AzureWebApp@1");
            sb.AppendLine($"                  displayName: 'Deploy to Web App'");
            sb.AppendLine("                  inputs:");
            sb.AppendLine("                    azureSubscription: $(azureResourceManagerConnection)");
            sb.AppendLine("                    appType: webApp");
            sb.AppendLine("                    appName: $(webAppName)");
            sb.AppendLine("                    package: $(Pipeline.Workspace)/drop");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Appends per-environment deployment stages for container-based Function App.
    /// </summary>
    public static void AppendFunctionAppContainerDeployStages(
        StringBuilder sb,
        AppPipelineGenerationRequest request)
    {
        var imageName = request.DockerImageName ?? request.ResourceName.ToLowerInvariant();

        for (var i = 0; i < request.Environments.Count; i++)
        {
            var env = request.Environments[i];
            var envKey = env.ShortName.ToLowerInvariant();
            var dependsOn = i == 0 ? "Build" : $"Deploy_{request.Environments[i - 1].ShortName.ToLowerInvariant()}";

            sb.AppendLine($"  - stage: Deploy_{envKey}");
            sb.AppendLine($"    displayName: 'Deploy to {env.Name}'");
            sb.AppendLine($"    dependsOn: {dependsOn}");
            sb.AppendLine("    variables:");
            AppendEnvironmentVariables(sb, env, request);
            sb.AppendLine("    jobs:");
            sb.AppendLine($"      - deployment: Deploy_{envKey}");
            sb.AppendLine($"        displayName: 'Deploy {request.ResourceName} to {env.Name}'");
            sb.AppendLine($"        environment: {env.Name}");
            sb.AppendLine("        strategy:");
            sb.AppendLine("          runOnce:");
            sb.AppendLine("            deploy:");
            sb.AppendLine("              steps:");
            sb.AppendLine("                - task: AzureFunctionApp@2");
            sb.AppendLine($"                  displayName: 'Deploy Container to Function App'");
            sb.AppendLine("                  inputs:");
            sb.AppendLine("                    azureSubscription: $(azureResourceManagerConnection)");
            sb.AppendLine("                    appType: functionAppContainer");
            sb.AppendLine("                    appName: $(functionAppName)");
            sb.AppendLine($"                    containers: $(containerRegistryLoginServer)/{imageName}:$(Build.BuildId)");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Appends per-environment deployment stages for code-based Function App.
    /// </summary>
    public static void AppendFunctionAppCodeDeployStages(
        StringBuilder sb,
        AppPipelineGenerationRequest request)
    {
        for (var i = 0; i < request.Environments.Count; i++)
        {
            var env = request.Environments[i];
            var envKey = env.ShortName.ToLowerInvariant();
            var dependsOn = i == 0 ? "Build" : $"Deploy_{request.Environments[i - 1].ShortName.ToLowerInvariant()}";

            sb.AppendLine($"  - stage: Deploy_{envKey}");
            sb.AppendLine($"    displayName: 'Deploy to {env.Name}'");
            sb.AppendLine($"    dependsOn: {dependsOn}");
            sb.AppendLine("    variables:");
            AppendEnvironmentVariables(sb, env, request);
            sb.AppendLine("    jobs:");
            sb.AppendLine($"      - deployment: Deploy_{envKey}");
            sb.AppendLine($"        displayName: 'Deploy {request.ResourceName} to {env.Name}'");
            sb.AppendLine($"        environment: {env.Name}");
            sb.AppendLine("        strategy:");
            sb.AppendLine("          runOnce:");
            sb.AppendLine("            deploy:");
            sb.AppendLine("              steps:");
            sb.AppendLine("                - task: DownloadPipelineArtifact@2");
            sb.AppendLine("                  displayName: 'Download Build Artifact'");
            sb.AppendLine("                  inputs:");
            sb.AppendLine($"                    artifactName: drop-{request.ResourceName}");
            sb.AppendLine("                    targetPath: $(Pipeline.Workspace)/drop");
            sb.AppendLine();
            sb.AppendLine("                - task: AzureFunctionApp@2");
            sb.AppendLine($"                  displayName: 'Deploy to Function App'");
            sb.AppendLine("                  inputs:");
            sb.AppendLine("                    azureSubscription: $(azureResourceManagerConnection)");
            sb.AppendLine("                    appType: functionApp");
            sb.AppendLine("                    appName: $(functionAppName)");
            sb.AppendLine("                    package: $(Pipeline.Workspace)/drop");
            sb.AppendLine();
        }
    }

    private static void AppendEnvironmentVariables(
        StringBuilder sb,
        EnvironmentDefinition env,
        AppPipelineGenerationRequest request)
    {
        var envKey = env.ShortName.ToLowerInvariant();
        var variablesPath = GetEnvironmentVariablesPath(envKey, request.IsMonoRepo);

        sb.AppendLine($"      - template: {variablesPath}");

        foreach (var group in request.PipelineVariableGroups)
        {
            var resolvedName = group.GroupName.Replace(
                "{env}", envKey, StringComparison.OrdinalIgnoreCase);
            sb.AppendLine($"      - group: {resolvedName}");
        }
    }

    private static void AppendSdkSetupStep(StringBuilder sb, string? runtimeStack, string? runtimeVersion)
    {
        var stack = runtimeStack?.ToUpperInvariant() ?? "DOTNETCORE";
        var version = runtimeVersion ?? "8.0";

        switch (stack)
        {
            case "DOTNETCORE" or "DOTNET":
                sb.AppendLine("          - task: UseDotNet@2");
                sb.AppendLine("            displayName: 'Setup .NET SDK'");
                sb.AppendLine("            inputs:");
                sb.AppendLine($"              packageType: sdk");
                sb.AppendLine($"              version: {version}.x");
                sb.AppendLine();
                break;

            case "NODE" or "NODEJS":
                sb.AppendLine("          - task: UseNode@1");
                sb.AppendLine("            displayName: 'Setup Node.js'");
                sb.AppendLine("            inputs:");
                sb.AppendLine($"              version: {version}.x");
                sb.AppendLine();
                break;

            case "PYTHON":
                sb.AppendLine("          - task: UsePythonVersion@0");
                sb.AppendLine("            displayName: 'Setup Python'");
                sb.AppendLine("            inputs:");
                sb.AppendLine($"              versionSpec: {version}");
                sb.AppendLine();
                break;

            case "JAVA":
                sb.AppendLine("          - task: JavaToolInstaller@0");
                sb.AppendLine("            displayName: 'Setup Java'");
                sb.AppendLine("            inputs:");
                sb.AppendLine($"              versionSpec: {version}");
                sb.AppendLine("              jdkArchitectureOption: x64");
                sb.AppendLine("              jdkSourceOption: PreInstalled");
                sb.AppendLine();
                break;

            default:
                sb.AppendLine($"          # Runtime setup: {stack} {version} — configure SDK manually");
                sb.AppendLine();
                break;
        }
    }

    private static void AppendDefaultBuildSteps(StringBuilder sb, string? runtimeStack, string srcPath)
    {
        var stack = runtimeStack?.ToUpperInvariant() ?? "DOTNETCORE";

        switch (stack)
        {
            case "DOTNETCORE" or "DOTNET":
                sb.AppendLine("          - script: |");
                sb.AppendLine($"              dotnet restore");
                sb.AppendLine($"              dotnet build --configuration Release --no-restore");
                sb.AppendLine($"              dotnet test --configuration Release --no-build --verbosity normal");
                sb.AppendLine($"              dotnet publish --configuration Release --no-build --output $(Build.ArtifactStagingDirectory)/drop");
                sb.AppendLine("            displayName: 'Restore, Build, Test & Publish'");
                sb.AppendLine($"            workingDirectory: {srcPath}");
                sb.AppendLine();
                break;

            case "NODE" or "NODEJS":
                sb.AppendLine("          - script: |");
                sb.AppendLine("              npm ci");
                sb.AppendLine("              npm run build");
                sb.AppendLine("              npm run test -- --ci || true");
                sb.AppendLine("            displayName: 'Install, Build & Test'");
                sb.AppendLine($"            workingDirectory: {srcPath}");
                sb.AppendLine();
                sb.AppendLine("          - script: |");
                sb.AppendLine($"              cp -r {srcPath}/dist $(Build.ArtifactStagingDirectory)/drop || cp -r {srcPath}/build $(Build.ArtifactStagingDirectory)/drop");
                sb.AppendLine("            displayName: 'Copy Build Output'");
                sb.AppendLine();
                break;

            case "PYTHON":
                sb.AppendLine("          - script: |");
                sb.AppendLine("              pip install -r requirements.txt");
                sb.AppendLine("              python -m pytest || true");
                sb.AppendLine($"              cp -r . $(Build.ArtifactStagingDirectory)/drop");
                sb.AppendLine("            displayName: 'Install, Test & Package'");
                sb.AppendLine($"            workingDirectory: {srcPath}");
                sb.AppendLine();
                break;

            default:
                sb.AppendLine("          - script: |");
                sb.AppendLine("              echo 'Build steps not configured — add custom build command'");
                sb.AppendLine("            displayName: 'Build (manual configuration required)'");
                sb.AppendLine($"            workingDirectory: {srcPath}");
                sb.AppendLine();
                break;
        }
    }
}
