namespace InfraFlowSculptor.PipelineGeneration.Generators.App;

/// <summary>
/// Generates shared Azure DevOps YAML pipeline templates for application CI/CD.
/// These templates are parameterised and referenced via <c>extends:</c> from per-resource wrappers.
/// Output paths are relative to the <c>.templates/</c> folder.
/// </summary>
internal static class AppPipelineSharedTemplateGenerator
{
    /// <summary>
    /// Generates all shared application pipeline template files.
    /// </summary>
    /// <returns>Dictionary of relative path → YAML content (paths relative to <c>.templates/</c>).</returns>
    internal static IReadOnlyDictionary<string, string> GenerateAll()
    {
        return new Dictionary<string, string>
        {
            ["pipelines/app-ci-container.pipeline.yml"] = GenerateCiContainerTemplate(),
            ["pipelines/app-ci-code.pipeline.yml"] = GenerateCiCodeTemplate(),
            ["pipelines/app-release-container.pipeline.yml"] = GenerateReleaseContainerTemplate(),
            ["pipelines/app-release-code.pipeline.yml"] = GenerateReleaseCodeTemplate(),
        };
    }

    /// <summary>
    /// Generates the shared CI pipeline template for container-mode applications.
    /// Handles Docker build, ACR push, Trivy scanning, and SBOM generation.
    /// </summary>
    private static string GenerateCiContainerTemplate()
    {
        return """
               # Shared CI Pipeline Template for Container-mode apps — Auto-generated by InfraFlowSculptor
               # Usage: extends: template: ../.templates/pipelines/app-ci-container.pipeline.yml

               parameters:
                 - name: resourceName
                   type: string
                 - name: configName
                   type: string
                 - name: imageRepository
                   type: string
                 - name: imageTagPattern
                   type: string
                   default: '{buildNumber}-{shortSha}'
                 - name: dockerfilePath
                   type: string
                   default: 'Dockerfile'
                 - name: buildContext
                   type: string
                   default: '.'
                 - name: containerRegistryName
                   type: string
                   default: ''
                 - name: acrAuthMode
                   type: string
                   default: 'ServiceConnection'
                 - name: enableSecurityScans
                   type: boolean
                   default: true
                 - name: promotionStrategy
                   type: string
                   default: 'AcrImport'
                 - name: resourceType
                   type: string
                 - name: buildSourceEnvKey
                   type: string
                   default: ''
                 - name: envVariablesPath
                   type: string
                   default: ''
                 - name: variableGroups
                   type: object
                   default: []
                 - name: agentPoolName
                   type: string
                   default: ''

               pool:
                 ${{ if eq(parameters.agentPoolName, '') }}:
                   vmImage: 'ubuntu-latest'
                 ${{ if ne(parameters.agentPoolName, '') }}:
                   name: '${{ parameters.agentPoolName }}'

               stages:
                 - stage: Build
                   displayName: 'Build, scan and publish image'
                   ${{ if ne(parameters.buildSourceEnvKey, '') }}:
                     variables:
                       - template: ${{ parameters.envVariablesPath }}
                       - ${{ each group in parameters.variableGroups }}:
                         - group: ${{ group }}
                   jobs:
                     - job: BuildAndPush
                       displayName: 'Build and push immutable image'
                       steps:
                         - checkout: self
                           fetchDepth: 0

                         - bash: |
                             set -euo pipefail
                             sourceVersion="$(Build.SourceVersion)"
                             shortSha=$(echo "$sourceVersion" | cut -c1-7)
                             branchName="$(Build.SourceBranchName)"
                             sanitizedBranch=$(echo "$branchName" | tr '/_' '-' | tr '[:upper:]' '[:lower:]')
                             releaseTagPattern="${{ parameters.imageTagPattern }}"
                             releaseTag=${releaseTagPattern//\{buildNumber\}/$(Build.BuildNumber)}
                             releaseTag=${releaseTag//\{shortSha\}/$shortSha}
                             releaseTag=${releaseTag//\{branch\}/$sanitizedBranch}
                             releaseTag=$(echo "$releaseTag" | tr '[:upper:]' '[:lower:]')
                             sourceRegistryName="$(containerRegistryName)"
                             if [ -z "$sourceRegistryName" ] || [ "$sourceRegistryName" = '$(containerRegistryName)' ]; then sourceRegistryName="${{ parameters.containerRegistryName }}"; fi
                             sourceRegistryLoginServer="$(containerRegistryLoginServer)"
                             if [ -z "$sourceRegistryLoginServer" ] || [ "$sourceRegistryLoginServer" = '$(containerRegistryLoginServer)' ]; then sourceRegistryLoginServer="${{ parameters.containerRegistryName }}.azurecr.io"; fi
                             mkdir -p "$(Build.ArtifactStagingDirectory)/app-metadata"
                             cat > "$(Build.ArtifactStagingDirectory)/app-metadata/metadata.json" <<EOF
                             {
                               "releaseTag": "$releaseTag",
                               "shortSha": "$shortSha",
                               "imageRepository": "${{ parameters.imageRepository }}",
                               "sourceRegistryName": "$sourceRegistryName",
                               "sourceRegistryLoginServer": "$sourceRegistryLoginServer",
                               "configName": "${{ parameters.configName }}",
                               "resourceName": "${{ parameters.resourceName }}",
                               "resourceType": "${{ parameters.resourceType }}",
                               "promotionStrategy": "${{ parameters.promotionStrategy }}"
                             }
                             EOF
                             echo "##vso[task.setvariable variable=ReleaseTag]$releaseTag"
                             echo "##vso[task.setvariable variable=ShortSha]$shortSha"
                           displayName: 'Compute immutable release tag'

                         - ${{ if eq(parameters.acrAuthMode, 'AdminCredentials') }}:
                           - bash: |
                               set -euo pipefail
                               echo "$(containerRegistryPassword)" | docker login "$(containerRegistryLoginServer)" --username "$(containerRegistryUsername)" --password-stdin
                             displayName: 'Authenticate to build ACR with admin credentials'

                         - ${{ if ne(parameters.acrAuthMode, 'AdminCredentials') }}:
                           - task: Docker@2
                             displayName: 'Authenticate to build ACR'
                             inputs:
                               command: login
                               containerRegistry: $(containerRegistryServiceConnection)

                         - bash: |
                             set -euo pipefail
                             registryLoginServer="$(containerRegistryLoginServer)"
                             if [ -z "$registryLoginServer" ] || [ "$registryLoginServer" = '$(containerRegistryLoginServer)' ]; then registryLoginServer="${{ parameters.containerRegistryName }}.azurecr.io"; fi
                             docker buildx inspect ifs-builder >/dev/null 2>&1 || docker buildx create --name ifs-builder --use >/dev/null
                             docker buildx use ifs-builder >/dev/null
                             docker buildx build \
                               --file "${{ parameters.dockerfilePath }}" \
                               --label "org.opencontainers.image.revision=$(Build.SourceVersion)" \
                               --label "org.opencontainers.image.version=$(ReleaseTag)" \
                               --label "org.opencontainers.image.source=$(Build.Repository.Uri)" \
                               --label "org.opencontainers.image.created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
                               --tag "${registryLoginServer}/${{ parameters.imageRepository }}:$(ReleaseTag)" \
                               --tag "${registryLoginServer}/${{ parameters.imageRepository }}:sha-$(ShortSha)" \
                               --push \
                               "${{ parameters.buildContext }}"
                           displayName: 'Build and push immutable image tags'

                         - ${{ if parameters.enableSecurityScans }}:
                           - bash: |
                               set -euo pipefail
                               toolDir="$(Agent.TempDirectory)/supply-chain-tools"
                               mkdir -p "$toolDir"
                               curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b "$toolDir"
                               echo "##vso[task.prependpath]$toolDir"
                             displayName: 'Install Trivy'

                           - bash: |
                               set -euo pipefail
                               registryLoginServer="$(containerRegistryLoginServer)"
                               if [ -z "$registryLoginServer" ] || [ "$registryLoginServer" = '$(containerRegistryLoginServer)' ]; then registryLoginServer="${{ parameters.containerRegistryName }}.azurecr.io"; fi
                               mkdir -p "$(Build.ArtifactStagingDirectory)/supply-chain"
                               trivy image --scanners vuln --severity HIGH,CRITICAL --ignore-unfixed --format json --output "$(Build.ArtifactStagingDirectory)/supply-chain/trivy-report.json" --exit-code 1 "${registryLoginServer}/${{ parameters.imageRepository }}:$(ReleaseTag)"
                             displayName: 'Scan image with Trivy'

                           - bash: |
                               set -euo pipefail
                               toolDir="$(Agent.TempDirectory)/supply-chain-tools"
                               mkdir -p "$toolDir"
                               curl -sfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b "$toolDir"
                               echo "##vso[task.prependpath]$toolDir"
                               registryLoginServer="$(containerRegistryLoginServer)"
                               if [ -z "$registryLoginServer" ] || [ "$registryLoginServer" = '$(containerRegistryLoginServer)' ]; then registryLoginServer="${{ parameters.containerRegistryName }}.azurecr.io"; fi
                               mkdir -p "$(Build.ArtifactStagingDirectory)/supply-chain"
                               syft "${registryLoginServer}/${{ parameters.imageRepository }}:$(ReleaseTag)" -o cyclonedx-json > "$(Build.ArtifactStagingDirectory)/supply-chain/sbom.cyclonedx.json"
                             displayName: 'Generate SBOM'

                         - task: PublishPipelineArtifact@1
                           displayName: 'Publish app metadata'
                           inputs:
                             targetPath: '$(Build.ArtifactStagingDirectory)/app-metadata'
                             artifact: 'app-metadata'

                         - ${{ if parameters.enableSecurityScans }}:
                           - task: PublishPipelineArtifact@1
                             displayName: 'Publish supply chain reports'
                             inputs:
                               targetPath: '$(Build.ArtifactStagingDirectory)/supply-chain'
                               artifact: 'supply-chain'
               """;
    }

    /// <summary>
    /// Generates the shared CI pipeline template for code-mode applications.
    /// Handles SDK setup, build, test, and artifact publishing across runtime stacks.
    /// </summary>
    private static string GenerateCiCodeTemplate()
    {
        return """
               # Shared CI Pipeline Template for Code-mode apps — Auto-generated by InfraFlowSculptor
               # Usage: extends: template: ../.templates/pipelines/app-ci-code.pipeline.yml

               parameters:
                 - name: resourceName
                   type: string
                 - name: configName
                   type: string
                 - name: imageRepository
                   type: string
                 - name: imageTagPattern
                   type: string
                   default: '{buildNumber}-{shortSha}'
                 - name: runtimeStack
                   type: string
                   default: 'DOTNETCORE'
                 - name: runtimeVersion
                   type: string
                   default: '8.0'
                 - name: sourcePath
                   type: string
                   default: '.'
                 - name: testCommand
                   type: string
                   default: ''
                 - name: buildCommand
                   type: string
                   default: ''
                 - name: promotionStrategy
                   type: string
                   default: 'AcrImport'
                 - name: resourceType
                   type: string
                 - name: agentPoolName
                   type: string
                   default: ''

               pool:
                 ${{ if eq(parameters.agentPoolName, '') }}:
                   vmImage: 'ubuntu-latest'
                 ${{ if ne(parameters.agentPoolName, '') }}:
                   name: '${{ parameters.agentPoolName }}'

               stages:
                 - stage: Build
                   displayName: 'Build, test and publish package'
                   jobs:
                     - job: BuildAndPublish
                       displayName: 'Build application package'
                       steps:
                         - checkout: self
                           fetchDepth: 0

                         - bash: |
                             set -euo pipefail
                             sourceVersion="$(Build.SourceVersion)"
                             shortSha=$(echo "$sourceVersion" | cut -c1-7)
                             branchName="$(Build.SourceBranchName)"
                             sanitizedBranch=$(echo "$branchName" | tr '/_' '-' | tr '[:upper:]' '[:lower:]')
                             releaseTagPattern="${{ parameters.imageTagPattern }}"
                             releaseTag=${releaseTagPattern//\{buildNumber\}/$(Build.BuildNumber)}
                             releaseTag=${releaseTag//\{shortSha\}/$shortSha}
                             releaseTag=${releaseTag//\{branch\}/$sanitizedBranch}
                             releaseTag=$(echo "$releaseTag" | tr '[:upper:]' '[:lower:]')
                             sourceRegistryName=""
                             sourceRegistryLoginServer=""
                             mkdir -p "$(Build.ArtifactStagingDirectory)/app-metadata"
                             cat > "$(Build.ArtifactStagingDirectory)/app-metadata/metadata.json" <<EOF
                             {
                               "releaseTag": "$releaseTag",
                               "shortSha": "$shortSha",
                               "imageRepository": "${{ parameters.imageRepository }}",
                               "sourceRegistryName": "$sourceRegistryName",
                               "sourceRegistryLoginServer": "$sourceRegistryLoginServer",
                               "configName": "${{ parameters.configName }}",
                               "resourceName": "${{ parameters.resourceName }}",
                               "resourceType": "${{ parameters.resourceType }}",
                               "promotionStrategy": "${{ parameters.promotionStrategy }}"
                             }
                             EOF
                             echo "##vso[task.setvariable variable=ReleaseTag]$releaseTag"
                             echo "##vso[task.setvariable variable=ShortSha]$shortSha"
                           displayName: 'Compute immutable release tag'

                         # ── SDK setup ──────────────────────────────────────────────
                         - ${{ if or(eq(parameters.runtimeStack, 'DOTNETCORE'), eq(parameters.runtimeStack, 'DOTNET')) }}:
                           - task: UseDotNet@2
                             displayName: 'Setup .NET SDK'
                             inputs:
                               packageType: sdk
                               version: ${{ parameters.runtimeVersion }}.x

                         - ${{ if or(eq(parameters.runtimeStack, 'NODE'), eq(parameters.runtimeStack, 'NODEJS')) }}:
                           - task: UseNode@1
                             displayName: 'Setup Node.js'
                             inputs:
                               version: ${{ parameters.runtimeVersion }}.x

                         - ${{ if eq(parameters.runtimeStack, 'PYTHON') }}:
                           - task: UsePythonVersion@0
                             displayName: 'Setup Python'
                             inputs:
                               versionSpec: ${{ parameters.runtimeVersion }}

                         - ${{ if eq(parameters.runtimeStack, 'JAVA') }}:
                           - task: JavaToolInstaller@0
                             displayName: 'Setup Java'
                             inputs:
                               versionSpec: ${{ parameters.runtimeVersion }}
                               jdkArchitectureOption: x64
                               jdkSourceOption: PreInstalled

                         # ── Test (custom command) ──────────────────────────────────
                         - ${{ if ne(parameters.testCommand, '') }}:
                           - pwsh: |
                               ${{ parameters.testCommand }}
                             displayName: 'Run application tests'
                             workingDirectory: ${{ parameters.sourcePath }}

                         # ── Build (custom command — overrides all default build logic) ─
                         - ${{ if ne(parameters.buildCommand, '') }}:
                           - pwsh: |
                               ${{ parameters.buildCommand }}
                             displayName: 'Build and package application'
                             workingDirectory: ${{ parameters.sourcePath }}

                         # ── Build (.NET default) ───────────────────────────────────
                         - ${{ if and(eq(parameters.buildCommand, ''), or(eq(parameters.runtimeStack, 'DOTNETCORE'), eq(parameters.runtimeStack, 'DOTNET'))) }}:
                           - pwsh: |
                               dotnet restore
                               dotnet build --configuration Release --no-restore
                             displayName: 'Restore and build .NET application'
                             workingDirectory: ${{ parameters.sourcePath }}

                           - pwsh: |
                               dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --results-directory "$(Common.TestResultsDirectory)" --collect "XPlat Code Coverage"
                             displayName: 'Run automated tests'
                             workingDirectory: ${{ parameters.sourcePath }}

                           - task: PublishTestResults@2
                             displayName: 'Publish test results'
                             inputs:
                               testResultsFormat: VSTest
                               testResultsFiles: '$(Common.TestResultsDirectory)/**/*.trx'
                               failTaskOnFailedTests: true

                           - task: PublishCodeCoverageResults@2
                             displayName: 'Publish code coverage'
                             inputs:
                               codeCoverageTool: Cobertura
                               summaryFileLocation: '$(Common.TestResultsDirectory)/**/coverage.cobertura.xml'
                               failIfCoverageEmpty: false

                           - pwsh: |
                               dotnet publish --configuration Release --no-build --output "$(Build.ArtifactStagingDirectory)/application-package"
                             displayName: 'Publish application package'
                             workingDirectory: ${{ parameters.sourcePath }}

                         # ── Build (Node.js default) ────────────────────────────────
                         - ${{ if and(eq(parameters.buildCommand, ''), or(eq(parameters.runtimeStack, 'NODE'), eq(parameters.runtimeStack, 'NODEJS'))) }}:
                           - bash: |
                               set -euo pipefail
                               npm ci
                               ${{ if eq(parameters.testCommand, '') }}:
                                 npm run test --if-present
                               npm run build
                               mkdir -p "$(Build.ArtifactStagingDirectory)/application-package"
                               if [ -d dist ]; then cp -R dist/. "$(Build.ArtifactStagingDirectory)/application-package"; elif [ -d build ]; then cp -R build/. "$(Build.ArtifactStagingDirectory)/application-package"; else cp -R . "$(Build.ArtifactStagingDirectory)/application-package"; fi
                             displayName: 'Build and package application'
                             workingDirectory: ${{ parameters.sourcePath }}

                         # ── Build (Python default) ─────────────────────────────────
                         - ${{ if and(eq(parameters.buildCommand, ''), eq(parameters.runtimeStack, 'PYTHON')) }}:
                           - bash: |
                               set -euo pipefail
                               python -m pip install -r requirements.txt
                               mkdir -p "$(Build.ArtifactStagingDirectory)/application-package"
                               cp -R . "$(Build.ArtifactStagingDirectory)/application-package"
                             displayName: 'Build and package application'
                             workingDirectory: ${{ parameters.sourcePath }}

                         # ── Publish artifacts ──────────────────────────────────────
                         - task: PublishPipelineArtifact@1
                           displayName: 'Publish app metadata'
                           inputs:
                             targetPath: '$(Build.ArtifactStagingDirectory)/app-metadata'
                             artifact: 'app-metadata'

                         - task: PublishPipelineArtifact@1
                           displayName: 'Publish application package'
                           inputs:
                             targetPath: '$(Build.ArtifactStagingDirectory)/application-package'
                             artifact: 'application-package'
               """;
    }

    /// <summary>
    /// Generates the shared release pipeline template for container-mode applications.
    /// Handles ACR promotion and container deployment across environments.
    /// </summary>
    private static string GenerateReleaseContainerTemplate()
    {
        return """
               # Shared Release Pipeline Template for Container-mode apps — Auto-generated by InfraFlowSculptor
               # Usage: extends: template: ../.templates/pipelines/app-release-container.pipeline.yml

               parameters:
                 - name: resourceName
                   type: string
                 - name: resourceType
                   type: string
                 - name: imageRepository
                   type: string
                 - name: promotionStrategy
                   type: string
                   default: 'AcrImport'
                 - name: agentPoolName
                   type: string
                   default: ''
                 - name: environments
                   type: object
                   # Expected format:
                   # - shortName: dev
                   #   name: Development
                   #   variablesPath: variables/dev.yml
                   #   variableGroups:
                   #     - my-group-dev

               pool:
                 ${{ if eq(parameters.agentPoolName, '') }}:
                   vmImage: 'ubuntu-latest'
                 ${{ if ne(parameters.agentPoolName, '') }}:
                   name: '${{ parameters.agentPoolName }}'

               stages:
                 - ${{ each env in parameters.environments }}:
                   - stage: Deploy_${{ env.shortName }}
                     displayName: 'Promote and deploy to ${{ env.name }}'
                     lockBehavior: sequential
                     variables:
                       - template: ${{ env.variablesPath }}
                       - ${{ each group in env.variableGroups }}:
                         - group: ${{ group }}
                     jobs:
                       - deployment: Deploy_${{ env.shortName }}
                         displayName: 'Deploy ${{ parameters.resourceName }} to ${{ env.name }}'
                         environment: ${{ env.name }}
                         strategy:
                           runOnce:
                             deploy:
                               steps:
                                 - checkout: none
                                 - download: ci
                                   artifact: app-metadata
                                   displayName: 'Download CI metadata'

                                 - pwsh: |
                                     $metadataPath = '$(Pipeline.Workspace)/app-metadata/metadata.json'
                                     if (-not (Test-Path -LiteralPath $metadataPath)) {
                                         throw "Metadata artifact not found: $metadataPath"
                                     }
                                     $metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json
                                     Write-Host "##vso[task.setvariable variable=ReleaseTag]$($metadata.releaseTag)"
                                     Write-Host "##vso[task.setvariable variable=ImageRepository]$($metadata.imageRepository)"
                                     Write-Host "##vso[task.setvariable variable=SourceRegistryName]$($metadata.sourceRegistryName)"
                                     Write-Host "##vso[task.setvariable variable=SourceRegistryLoginServer]$($metadata.sourceRegistryLoginServer)"
                                   displayName: 'Load release metadata'

                                 - task: AzureCLI@2
                                   displayName: 'Promote image in ACR'
                                   inputs:
                                     azureSubscription: $(azureResourceManagerConnection)
                                     scriptType: bash
                                     scriptLocation: inlineScript
                                     inlineScript: |
                                       set -euo pipefail
                                       imageRepository="$(ImageRepository)"
                                       if [ -z "$imageRepository" ] || [ "$imageRepository" = '$(ImageRepository)' ]; then imageRepository="${{ parameters.imageRepository }}"; fi
                                       if [ "${{ parameters.promotionStrategy }}" = "AcrImport" ] && [ "$(containerRegistryLoginServer)" != "$(SourceRegistryLoginServer)" ]; then
                                         az acr import --name "$(containerRegistryName)" --source "$(SourceRegistryLoginServer)/${imageRepository}:$(ReleaseTag)" --image "${imageRepository}:$(ReleaseTag)" --force
                                       fi
                                       az acr import --name "$(containerRegistryName)" --source "$(containerRegistryLoginServer)/${imageRepository}:$(ReleaseTag)" --image "${imageRepository}:env-${{ env.shortName }}" --force

                                 # ── Container App deploy ─────────────────────────
                                 - ${{ if eq(parameters.resourceType, 'ContainerApp') }}:
                                   - task: AzureCLI@2
                                     displayName: 'Deploy image to Container App'
                                     inputs:
                                       azureSubscription: $(azureResourceManagerConnection)
                                       scriptType: bash
                                       scriptLocation: inlineScript
                                       inlineScript: |
                                         set -euo pipefail
                                         imageRepository="$(ImageRepository)"
                                         if [ -z "$imageRepository" ] || [ "$imageRepository" = '$(ImageRepository)' ]; then imageRepository="${{ parameters.imageRepository }}"; fi
                                         az containerapp update --name "$(containerAppName)" --resource-group "$(resourceGroupName)" --image "$(containerRegistryLoginServer)/${imageRepository}:$(ReleaseTag)"

                                 # ── Web App container deploy ─────────────────────
                                 - ${{ if eq(parameters.resourceType, 'WebApp') }}:
                                   - task: AzureWebApp@1
                                     displayName: 'Deploy container image'
                                     inputs:
                                       azureSubscription: $(azureResourceManagerConnection)
                                       appType: webAppContainer
                                       appName: $(webAppName)
                                       containers: $(containerRegistryLoginServer)/$(ImageRepository):$(ReleaseTag)

                                 # ── Function App container deploy ────────────────
                                 - ${{ if eq(parameters.resourceType, 'FunctionApp') }}:
                                   - task: AzureFunctionApp@2
                                     displayName: 'Deploy container image'
                                     inputs:
                                       azureSubscription: $(azureResourceManagerConnection)
                                       appType: functionAppContainer
                                       appName: $(functionAppName)
                                       containers: $(containerRegistryLoginServer)/$(ImageRepository):$(ReleaseTag)
               """;
    }

    /// <summary>
    /// Generates the shared release pipeline template for code-mode applications.
    /// Handles package download and deployment across environments.
    /// </summary>
    private static string GenerateReleaseCodeTemplate()
    {
        return """
               # Shared Release Pipeline Template for Code-mode apps — Auto-generated by InfraFlowSculptor
               # Usage: extends: template: ../.templates/pipelines/app-release-code.pipeline.yml

               parameters:
                 - name: resourceName
                   type: string
                 - name: resourceType
                   type: string
                 - name: agentPoolName
                   type: string
                   default: ''
                 - name: environments
                   type: object
                   # Expected format:
                   # - shortName: dev
                   #   name: Development
                   #   variablesPath: variables/dev.yml
                   #   variableGroups:
                   #     - my-group-dev

               pool:
                 ${{ if eq(parameters.agentPoolName, '') }}:
                   vmImage: 'ubuntu-latest'
                 ${{ if ne(parameters.agentPoolName, '') }}:
                   name: '${{ parameters.agentPoolName }}'

               stages:
                 - ${{ each env in parameters.environments }}:
                   - stage: Deploy_${{ env.shortName }}
                     displayName: 'Deploy to ${{ env.name }}'
                     lockBehavior: sequential
                     variables:
                       - template: ${{ env.variablesPath }}
                       - ${{ each group in env.variableGroups }}:
                         - group: ${{ group }}
                     jobs:
                       - deployment: Deploy_${{ env.shortName }}
                         displayName: 'Deploy ${{ parameters.resourceName }} to ${{ env.name }}'
                         environment: ${{ env.name }}
                         strategy:
                           runOnce:
                             deploy:
                               steps:
                                 - checkout: none
                                 - download: ci
                                   artifact: app-metadata
                                   displayName: 'Download CI metadata'
                                 - download: ci
                                   artifact: application-package
                                   displayName: 'Download application package'

                                 - pwsh: |
                                     $metadataPath = '$(Pipeline.Workspace)/app-metadata/metadata.json'
                                     if (-not (Test-Path -LiteralPath $metadataPath)) {
                                         throw "Metadata artifact not found: $metadataPath"
                                     }
                                     $metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json
                                     Write-Host "##vso[task.setvariable variable=ReleaseTag]$($metadata.releaseTag)"
                                     Write-Host "##vso[task.setvariable variable=ImageRepository]$($metadata.imageRepository)"
                                     Write-Host "##vso[task.setvariable variable=SourceRegistryName]$($metadata.sourceRegistryName)"
                                     Write-Host "##vso[task.setvariable variable=SourceRegistryLoginServer]$($metadata.sourceRegistryLoginServer)"
                                   displayName: 'Load release metadata'

                                 # ── Web App code deploy ──────────────────────────
                                 - ${{ if eq(parameters.resourceType, 'WebApp') }}:
                                   - task: AzureWebApp@1
                                     displayName: 'Deploy application package'
                                     inputs:
                                       azureSubscription: $(azureResourceManagerConnection)
                                       appType: webApp
                                       appName: $(webAppName)
                                       package: $(Pipeline.Workspace)/application-package

                                 # ── Function App code deploy ─────────────────────
                                 - ${{ if eq(parameters.resourceType, 'FunctionApp') }}:
                                   - task: AzureFunctionApp@2
                                     displayName: 'Deploy application package'
                                     inputs:
                                       azureSubscription: $(azureResourceManagerConnection)
                                       appType: functionApp
                                       appName: $(functionAppName)
                                       package: $(Pipeline.Workspace)/application-package
               """;
    }
}
