using System.Text;
using InfraFlowSculptor.Domain.Common.ValueObjects;
using InfraFlowSculptor.GenerationCore;
using InfraFlowSculptor.GenerationCore.Models;

namespace InfraFlowSculptor.PipelineGeneration.Generators.App;

using static PipelineGenerationEngine;

/// <summary>
/// Provides shared YAML building blocks for application CI and release pipelines.
/// </summary>
internal static class AppPipelineBuilderCommon
{
    internal const string MetadataArtifactName = "app-metadata";
    internal const string PackageArtifactName = "application-package";
    internal const string SupplyChainArtifactName = "supply-chain";

    private const string DefaultImageTagPattern = "{buildNumber}-{shortSha}";

    internal static string GetEnvironmentVariablesPath(string envKey, bool isMonoRepo)
    {
        return isMonoRepo
            ? $"../.azuredevops/variables/{envKey}.variables.yml"
            : $"variables/{envKey}.yml";
    }

    internal static EnvironmentDefinition? GetBuildSourceEnvironment(AppPipelineGenerationRequest request)
    {
        return request.Environments.FirstOrDefault();
    }

    internal static string BuildCiPipelineDefinitionName(AppPipelineGenerationRequest request)
    {
        return $"{request.ConfigName} - {request.ResourceName} - CI";
    }

    internal static string ResolveImageRepository(AppPipelineGenerationRequest request)
    {
        return request.DockerImageName ?? request.ResourceName.ToLowerInvariant();
    }

    internal static string ResolveImageTagPattern(AppPipelineGenerationRequest request)
    {
        return string.IsNullOrWhiteSpace(request.ImageTagPattern)
            ? DefaultImageTagPattern
            : request.ImageTagPattern;
    }

    internal static bool UsesAdminCredentials(AppPipelineGenerationRequest request)
    {
        return string.Equals(
            request.AcrAuthMode,
            AcrAuthMode.AcrAuthModeType.AdminCredentials.ToString(),
            StringComparison.OrdinalIgnoreCase);
    }

    internal static void AppendCiHeader(StringBuilder sb, string resourceName, string configName, string? agentPoolName)
    {
        configName = PathSanitizer.Sanitize(configName);
        resourceName = PathSanitizer.Sanitize(resourceName);

        sb.AppendLine($"# CI Application Pipeline for {resourceName} — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(Date:yyyyMMdd).$(Rev:r)");
        sb.AppendLine();
        sb.AppendLine("trigger:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        sb.AppendLine("      - main");
        sb.AppendLine("      - release/*");
        sb.AppendLine("  paths:");
        sb.AppendLine("    include:");
        sb.AppendLine($"      - {configName}/{resourceName}/*");
        sb.AppendLine();
        AppendPool(sb, agentPoolName, string.Empty);
        sb.AppendLine();
    }

    internal static void AppendReleaseHeader(StringBuilder sb, AppPipelineGenerationRequest request)
    {
        var ciPipelineName = EscapeForSingleQuotedYaml(BuildCiPipelineDefinitionName(request));

        sb.AppendLine($"# Release Application Pipeline for {request.ResourceName} — Auto-generated by InfraFlowSculptor");
        sb.AppendLine($"# Expected CI pipeline definition name: {BuildCiPipelineDefinitionName(request)}");
        sb.AppendLine("name: $(Date:yyyyMMdd).$(Rev:r)");
        sb.AppendLine();
        sb.AppendLine("trigger: none");
        sb.AppendLine();
        sb.AppendLine("resources:");
        sb.AppendLine("  pipelines:");
        sb.AppendLine("    - pipeline: ci");
        sb.AppendLine($"      source: '{ciPipelineName}'");
        sb.AppendLine("      trigger:");
        sb.AppendLine("        branches:");
        sb.AppendLine("          include:");
        sb.AppendLine("            - main");
        sb.AppendLine();
        AppendPool(sb, request.AgentPoolName, string.Empty);
        sb.AppendLine();
    }

    internal static void AppendEnvironmentVariableReferences(
        StringBuilder sb,
        string envKey,
        AppPipelineGenerationRequest request,
        string indent)
    {
        var variablesPath = GetEnvironmentVariablesPath(envKey, request.IsMonoRepo);
        sb.AppendLine($"{indent}- template: {variablesPath}");

        foreach (var group in request.PipelineVariableGroups)
        {
            var resolvedName = group.GroupName.Replace("{env}", envKey, StringComparison.OrdinalIgnoreCase);
            sb.AppendLine($"{indent}- group: {resolvedName}");
        }
    }

    internal static void AppendSdkSetupStep(StringBuilder sb, string? runtimeStack, string? runtimeVersion)
    {
        var stack = runtimeStack?.ToUpperInvariant() ?? "DOTNETCORE";
        var version = runtimeVersion ?? "8.0";

        switch (stack)
        {
            case "DOTNETCORE" or "DOTNET":
                sb.AppendLine("          - task: UseDotNet@2");
                sb.AppendLine("            displayName: 'Setup .NET SDK'");
                sb.AppendLine("            inputs:");
                sb.AppendLine("              packageType: sdk");
                sb.AppendLine($"              version: {version}.x");
                sb.AppendLine();
                break;

            case "NODE" or "NODEJS":
                sb.AppendLine("          - task: UseNode@1");
                sb.AppendLine("            displayName: 'Setup Node.js'");
                sb.AppendLine("            inputs:");
                sb.AppendLine($"              version: {version}.x");
                sb.AppendLine();
                break;

            case "PYTHON":
                sb.AppendLine("          - task: UsePythonVersion@0");
                sb.AppendLine("            displayName: 'Setup Python'");
                sb.AppendLine("            inputs:");
                sb.AppendLine($"              versionSpec: {version}");
                sb.AppendLine();
                break;

            case "JAVA":
                sb.AppendLine("          - task: JavaToolInstaller@0");
                sb.AppendLine("            displayName: 'Setup Java'");
                sb.AppendLine("            inputs:");
                sb.AppendLine($"              versionSpec: {version}");
                sb.AppendLine("              jdkArchitectureOption: x64");
                sb.AppendLine("              jdkSourceOption: PreInstalled");
                sb.AppendLine();
                break;
        }
    }

    internal static void AppendCodeBuildSteps(StringBuilder sb, AppPipelineGenerationRequest request)
    {
        var runtimeStack = request.RuntimeStack?.ToUpperInvariant() ?? "DOTNETCORE";
        var sourcePath = request.SourceCodePath ?? ".";
        var packagePath = $"$(Build.ArtifactStagingDirectory)/{PackageArtifactName}";

        if (!string.IsNullOrWhiteSpace(request.TestCommand))
        {
            sb.AppendLine("          - pwsh: |");
            sb.AppendLine($"              {request.TestCommand}");
            sb.AppendLine("            displayName: 'Run application tests'");
            sb.AppendLine($"            workingDirectory: {sourcePath}");
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(request.BuildCommand))
        {
            sb.AppendLine("          - pwsh: |");
            sb.AppendLine($"              {request.BuildCommand}");
            sb.AppendLine("            displayName: 'Build and package application'");
            sb.AppendLine($"            workingDirectory: {sourcePath}");
            sb.AppendLine();
            return;
        }

        if (runtimeStack is "DOTNETCORE" or "DOTNET")
        {
            AppendDotNetCodeBuildSteps(sb, sourcePath, packagePath);
            return;
        }

        AppendGenericCodeBuildSteps(sb, runtimeStack, sourcePath, packagePath, request.TestCommand);
    }

    internal static string GetDeploymentResourceNameVariable(string resourceType)
    {
        return resourceType switch
        {
            AzureResourceTypes.ContainerApp => "containerAppName",
            AzureResourceTypes.WebApp => "webAppName",
            AzureResourceTypes.FunctionApp => "functionAppName",
            _ => throw new InvalidOperationException($"Unsupported app deployment resource type '{resourceType}'."),
        };
    }

    internal static string GetAppServiceTaskName(string resourceType)
    {
        return resourceType switch
        {
            AzureResourceTypes.WebApp => "AzureWebApp@1",
            AzureResourceTypes.FunctionApp => "AzureFunctionApp@2",
            _ => throw new InvalidOperationException($"Unsupported App Service resource type '{resourceType}'."),
        };
    }

    internal static string GetAppServiceContainerType(string resourceType)
    {
        return resourceType switch
        {
            AzureResourceTypes.WebApp => "webAppContainer",
            AzureResourceTypes.FunctionApp => "functionAppContainer",
            _ => throw new InvalidOperationException($"Unsupported container App Service resource type '{resourceType}'."),
        };
    }

    internal static string GetAppServiceCodeType(string resourceType)
    {
        return resourceType switch
        {
            AzureResourceTypes.WebApp => "webApp",
            AzureResourceTypes.FunctionApp => "functionApp",
            _ => throw new InvalidOperationException($"Unsupported code App Service resource type '{resourceType}'."),
        };
    }

    internal static string EscapeForSingleQuotedYaml(string value)
    {
        return value.Replace("'", "''", StringComparison.Ordinal);
    }

    internal static string EscapeForDoubleQuotedBash(string value)
    {
        return value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private static void AppendDotNetCodeBuildSteps(StringBuilder sb, string sourcePath, string packagePath)
    {
        sb.AppendLine("          - pwsh: |");
        sb.AppendLine("              dotnet restore");
        sb.AppendLine("              dotnet build --configuration Release --no-restore");
        sb.AppendLine("            displayName: 'Restore and build .NET application'");
        sb.AppendLine($"            workingDirectory: {sourcePath}");
        sb.AppendLine();

        sb.AppendLine("          - pwsh: |");
        sb.AppendLine("              dotnet test --configuration Release --no-build --logger \"trx;LogFileName=test-results.trx\" --results-directory \"$(Common.TestResultsDirectory)\" --collect \"XPlat Code Coverage\"");
        sb.AppendLine("            displayName: 'Run automated tests'");
        sb.AppendLine($"            workingDirectory: {sourcePath}");
        sb.AppendLine();

        sb.AppendLine("          - task: PublishTestResults@2");
        sb.AppendLine("            displayName: 'Publish test results'");
        sb.AppendLine("            inputs:");
        sb.AppendLine("              testResultsFormat: VSTest");
        sb.AppendLine("              testResultsFiles: '$(Common.TestResultsDirectory)/**/*.trx'");
        sb.AppendLine("              failTaskOnFailedTests: true");
        sb.AppendLine();

        sb.AppendLine("          - task: PublishCodeCoverageResults@2");
        sb.AppendLine("            displayName: 'Publish code coverage'");
        sb.AppendLine("            inputs:");
        sb.AppendLine("              codeCoverageTool: Cobertura");
        sb.AppendLine("              summaryFileLocation: '$(Common.TestResultsDirectory)/**/coverage.cobertura.xml'");
        sb.AppendLine("              failIfCoverageEmpty: false");
        sb.AppendLine();

        sb.AppendLine("          - pwsh: |");
        sb.AppendLine($"              dotnet publish --configuration Release --no-build --output \"{packagePath}\"");
        sb.AppendLine("            displayName: 'Publish application package'");
        sb.AppendLine($"            workingDirectory: {sourcePath}");
        sb.AppendLine();
    }

    private static void AppendGenericCodeBuildSteps(
        StringBuilder sb,
        string runtimeStack,
        string sourcePath,
        string packagePath,
        string? testCommand)
    {
        sb.AppendLine("          - bash: |");
        sb.AppendLine("              set -euo pipefail");

        switch (runtimeStack)
        {
            case "NODE" or "NODEJS":
                sb.AppendLine("              npm ci");
                if (!string.IsNullOrWhiteSpace(testCommand))
                {
                    sb.AppendLine($"              {testCommand}");
                }
                else
                {
                    sb.AppendLine("              npm run test --if-present");
                }
                sb.AppendLine("              npm run build");
                sb.AppendLine($"              mkdir -p \"{packagePath}\"");
                sb.AppendLine("              if [ -d dist ]; then cp -R dist/. \"$(Build.ArtifactStagingDirectory)/application-package\"; elif [ -d build ]; then cp -R build/. \"$(Build.ArtifactStagingDirectory)/application-package\"; else cp -R . \"$(Build.ArtifactStagingDirectory)/application-package\"; fi");
                break;

            case "PYTHON":
                sb.AppendLine("              python -m pip install -r requirements.txt");
                if (!string.IsNullOrWhiteSpace(testCommand))
                {
                    sb.AppendLine($"              {testCommand}");
                }
                sb.AppendLine($"              mkdir -p \"{packagePath}\"");
                sb.AppendLine("              cp -R . \"$(Build.ArtifactStagingDirectory)/application-package\"");
                break;

            default:
                sb.AppendLine($"              mkdir -p \"{packagePath}\"");
                sb.AppendLine("              cp -R . \"$(Build.ArtifactStagingDirectory)/application-package\"");
                break;
        }

        sb.AppendLine("            displayName: 'Build and package application'");
        sb.AppendLine($"            workingDirectory: {sourcePath}");
        sb.AppendLine();
    }
}