using System.Text;
using InfraFlowSculptor.GenerationCore;
using InfraFlowSculptor.GenerationCore.Models;

namespace InfraFlowSculptor.PipelineGeneration.Generators.App;

/// <summary>
/// Builds thin release pipeline wrapper YAML files that reference shared templates via <c>extends:</c>.
/// </summary>
internal static class AppReleasePipelineBuilder
{
    private const string ContainerTemplatePath = "../.templates/pipelines/app-release-container.pipeline.yml";
    private const string CodeTemplatePath = "../.templates/pipelines/app-release-code.pipeline.yml";

    internal static string BuildContainerPipeline(AppPipelineGenerationRequest request)
    {
        var sb = new StringBuilder();
        var imageRepository = AppPipelineBuilderCommon.ResolveImageRepository(request);

        AppendReleaseHeader(sb, request);

        sb.AppendLine("extends:");
        sb.AppendLine($"  template: {ContainerTemplatePath}");
        sb.AppendLine("  parameters:");
        sb.AppendLine($"    resourceName: '{AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(request.ResourceName)}'");
        sb.AppendLine($"    resourceType: '{AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(request.ResourceType)}'");
        sb.AppendLine($"    imageRepository: '{AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(imageRepository)}'");
        sb.AppendLine($"    promotionStrategy: '{request.PromotionStrategy}'");
        AppendAgentPoolParameter(sb, request.AgentPoolName);
        AppendEnvironmentsParameter(sb, request);

        return sb.ToString();
    }

    internal static string BuildCodePipeline(AppPipelineGenerationRequest request)
    {
        var sb = new StringBuilder();

        AppendReleaseHeader(sb, request);

        sb.AppendLine("extends:");
        sb.AppendLine($"  template: {CodeTemplatePath}");
        sb.AppendLine("  parameters:");
        sb.AppendLine($"    resourceName: '{AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(request.ResourceName)}'");
        sb.AppendLine($"    resourceType: '{AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(request.ResourceType)}'");
        AppendAgentPoolParameter(sb, request.AgentPoolName);
        AppendEnvironmentsParameter(sb, request);

        return sb.ToString();
    }

    private static void AppendReleaseHeader(StringBuilder sb, AppPipelineGenerationRequest request)
    {
        var ciPipelineName = AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(
            AppPipelineBuilderCommon.BuildCiPipelineDefinitionName(request));

        sb.AppendLine($"# Release Application Pipeline for {request.ResourceName} — Auto-generated by InfraFlowSculptor");
        sb.AppendLine($"# Expected CI pipeline definition name: {AppPipelineBuilderCommon.BuildCiPipelineDefinitionName(request)}");
        sb.AppendLine("name: $(Date:yyyyMMdd).$(Rev:r)");
        sb.AppendLine();
        sb.AppendLine("trigger: none");
        sb.AppendLine();
        sb.AppendLine("resources:");
        sb.AppendLine("  pipelines:");
        sb.AppendLine("    - pipeline: ci");
        sb.AppendLine($"      source: '{ciPipelineName}'");
        sb.AppendLine("      trigger:");
        sb.AppendLine("        branches:");
        sb.AppendLine("          include:");
        sb.AppendLine("            - main");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits the <c>environments</c> parameter as a YAML object array.
    /// Each environment includes shortName, name, variablesPath, and resolved variable groups.
    /// </summary>
    private static void AppendEnvironmentsParameter(
        StringBuilder sb,
        AppPipelineGenerationRequest request)
    {
        sb.AppendLine("    environments:");
        foreach (var env in request.Environments)
        {
            var envKey = env.ShortName.ToLowerInvariant();
            var variablesPath = AppPipelineBuilderCommon.GetEnvironmentVariablesPath(envKey, request.IsMonoRepo);

            sb.AppendLine($"      - shortName: '{AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(envKey)}'");
            sb.AppendLine($"        name: '{AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(env.Name)}'");
            sb.AppendLine($"        variablesPath: '{AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(variablesPath)}'");

            if (request.PipelineVariableGroups.Count > 0)
            {
                sb.AppendLine("        variableGroups:");
                foreach (var group in request.PipelineVariableGroups)
                {
                    var resolvedName = group.GroupName.Replace("{env}", envKey, StringComparison.OrdinalIgnoreCase);
                    sb.AppendLine($"          - '{AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(resolvedName)}'");
                }
            }
            else
            {
                sb.AppendLine("        variableGroups: []");
            }
        }
    }

    private static void AppendAgentPoolParameter(StringBuilder sb, string? agentPoolName)
    {
        if (!string.IsNullOrWhiteSpace(agentPoolName))
        {
            sb.AppendLine($"    agentPoolName: '{AppPipelineBuilderCommon.EscapeForSingleQuotedYaml(agentPoolName)}'");
        }
    }
}