using InfraFlowSculptor.PipelineGeneration.Bootstrap;
using InfraFlowSculptor.PipelineGeneration.Bootstrap.Stages;
using InfraFlowSculptor.PipelineGeneration.Models;

namespace InfraFlowSculptor.PipelineGeneration.Tests.Bootstrap.Stages;

/// <summary>
/// Unit tests for <see cref="HeaderEmissionStage"/>.
/// </summary>
public sealed class HeaderEmissionStageTests
{
    private readonly HeaderEmissionStage _sut = new();

    [Fact]
    public void Given_FullOwnerRequest_When_Execute_Then_AppendsFullOwnerBanner()
    {
        // Arrange
        var context = CreateContext(BootstrapMode.FullOwner);

        // Act
        _sut.Execute(context);

        // Assert
        var output = context.Builder.ToString();
        output.Should().Contain("# Bootstrap Pipeline — generated by InfraFlowSculptor");
        output.Should().Contain("Infrastructure-side / standalone bootstrap");
        output.Should().Contain("stages:");
        output.Should().Contain("jobs:");
    }

    [Fact]
    public void Given_ApplicationOnlyRequest_When_Execute_Then_AppendsApplicationOnlyBanner()
    {
        // Arrange
        var context = CreateContext(BootstrapMode.ApplicationOnly);

        // Act
        _sut.Execute(context);

        // Assert
        var output = context.Builder.ToString();
        output.Should().Contain("Application-side bootstrap (SplitInfraCode)");
        output.Should().Contain("Environments and variable groups must have been provisioned by the infra bootstrap first");
    }

    [Fact]
    public void Order_Is_100()
    {
        _sut.Order.Should().Be(100);
    }

    private static BootstrapPipelineContext CreateContext(BootstrapMode mode) => new()
    {
        Request = new BootstrapGenerationRequest
        {
            OrganizationName = "contoso",
            ProjectName = "ifs",
            RepositoryName = "ifs",
            DefaultBranch = "main",
            Mode = mode,
        },
    };
}
