namespace InfraFlowSculptor.PipelineGeneration.Generators.App.SharedTemplates;

/// <summary>
/// Provides the shared application pipeline job templates.
/// </summary>
internal static class AppPipelineJobTemplates
{
    internal const string CiContainerJob = """
        # CI job for container-mode applications — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceName
            type: string
          - name: configName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: dockerfilePath
            type: string
            default: 'Dockerfile'
          - name: buildContext
            type: string
            default: '.'
          - name: containerRegistryName
            type: string
            default: ''
          - name: containerRegistryServiceConnection
            type: string
            default: '$(containerRegistryServiceConnection)'
          - name: acrAuthMode
            type: string
            default: 'ServiceConnection'
          - name: enableSecurityScans
            type: boolean
            default: true
          - name: promotionStrategy
            type: string
            default: 'AcrImport'

        jobs:
          - job: BuildAndPush
            displayName: 'Build and push immutable image'
            steps:
              - checkout: self
                fetchDepth: 0

              - template: ../steps/app-compute-release-tag.step.yml
                parameters:
                  imageTagPattern: ${{ parameters.imageTagPattern }}
                  imageRepository: ${{ parameters.imageRepository }}
                  configName: ${{ parameters.configName }}
                  resourceName: ${{ parameters.resourceName }}
                  resourceType: ${{ parameters.resourceType }}
                  promotionStrategy: ${{ parameters.promotionStrategy }}
                  containerRegistryName: ${{ parameters.containerRegistryName }}
                  includeRegistryMetadata: true

              - template: ../steps/app-acr-login.step.yml
                parameters:
                  acrAuthMode: ${{ parameters.acrAuthMode }}
                  containerRegistryServiceConnection: ${{ parameters.containerRegistryServiceConnection }}

              - template: ../steps/app-docker-buildx-push.step.yml
                parameters:
                  dockerfilePath: ${{ parameters.dockerfilePath }}
                  buildContext: ${{ parameters.buildContext }}
                  imageRepository: ${{ parameters.imageRepository }}
                  containerRegistryName: ${{ parameters.containerRegistryName }}

              - ${{ if parameters.enableSecurityScans }}:
                - template: ../steps/app-trivy-scan.step.yml
                  parameters:
                    imageRepository: ${{ parameters.imageRepository }}
                    containerRegistryName: ${{ parameters.containerRegistryName }}

                - template: ../steps/app-syft-sbom.step.yml
                  parameters:
                    imageRepository: ${{ parameters.imageRepository }}
                    containerRegistryName: ${{ parameters.containerRegistryName }}

              - task: PublishPipelineArtifact@1
                displayName: 'Publish app metadata'
                inputs:
                  targetPath: '$(Build.ArtifactStagingDirectory)/app-metadata'
                  artifact: 'app-metadata'

              - ${{ if parameters.enableSecurityScans }}:
                - task: PublishPipelineArtifact@1
                  displayName: 'Publish supply chain reports'
                  inputs:
                    targetPath: '$(Build.ArtifactStagingDirectory)/supply-chain'
                    artifact: 'supply-chain'
        """;

    internal const string CiCodeJob = """
        # CI job for code-mode applications — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceName
            type: string
          - name: configName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: runtimeVersion
            type: string
            default: '8.0'
          - name: sourcePath
            type: string
            default: '.'
          - name: testCommand
            type: string
            default: ''
          - name: buildCommand
            type: string
            default: ''
          - name: runUnitTests
            type: boolean
            default: false
          - name: testFramework
            type: string
            default: ''
          - name: testResultsFormat
            type: string
            default: 'VSTest'
          - name: testResultsPath
            type: string
            default: '$(Common.TestResultsDirectory)/**/*.trx'
          - name: publishTestResults
            type: boolean
            default: false
          - name: publishCodeCoverage
            type: boolean
            default: false
          - name: coverageTool
            type: string
            default: 'Cobertura'
          - name: coverageReportPath
            type: string
            default: '$(Common.TestResultsDirectory)/**/coverage.cobertura.xml'
          - name: promotionStrategy
            type: string
            default: 'AcrImport'

        jobs:
          - job: BuildAndPublish
            displayName: 'Build application package'
            steps:
              - checkout: self
                fetchDepth: 0

              - template: ../steps/app-compute-release-tag.step.yml
                parameters:
                  imageTagPattern: ${{ parameters.imageTagPattern }}
                  imageRepository: ${{ parameters.imageRepository }}
                  configName: ${{ parameters.configName }}
                  resourceName: ${{ parameters.resourceName }}
                  resourceType: ${{ parameters.resourceType }}
                  promotionStrategy: ${{ parameters.promotionStrategy }}
                  includeRegistryMetadata: false

              - template: ../steps/app-sdk-setup.step.yml
                parameters:
                  runtimeStack: ${{ parameters.runtimeStack }}
                  runtimeVersion: ${{ parameters.runtimeVersion }}

              - template: ../steps/app-build-code.step.yml
                parameters:
                  runtimeStack: ${{ parameters.runtimeStack }}
                  sourcePath: ${{ parameters.sourcePath }}
                  testCommand: ${{ parameters.testCommand }}
                  buildCommand: ${{ parameters.buildCommand }}
                  runUnitTests: ${{ parameters.runUnitTests }}
                  testFramework: ${{ parameters.testFramework }}
                  testResultsFormat: ${{ parameters.testResultsFormat }}
                  testResultsPath: ${{ parameters.testResultsPath }}
                  publishTestResults: ${{ parameters.publishTestResults }}
                  publishCodeCoverage: ${{ parameters.publishCodeCoverage }}
                  coverageTool: ${{ parameters.coverageTool }}
                  coverageReportPath: ${{ parameters.coverageReportPath }}

              - task: PublishPipelineArtifact@1
                displayName: 'Publish app metadata'
                inputs:
                  targetPath: '$(Build.ArtifactStagingDirectory)/app-metadata'
                  artifact: 'app-metadata'

              - task: PublishPipelineArtifact@1
                displayName: 'Publish application package'
                inputs:
                  targetPath: '$(Build.ArtifactStagingDirectory)/application-package'
                  artifact: 'application-package'
        """;

    internal const string PrContainerJob = """
        # PR validation job for container-mode applications - Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceName
            type: string
          - name: configName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: dockerfilePath
            type: string
            default: 'Dockerfile'
          - name: buildContext
            type: string
            default: '.'

        jobs:
          - job: ValidateImageBuild
            displayName: 'Validate pull request image build'
            steps:
              - checkout: self
                fetchDepth: 0

              - template: ../steps/app-compute-release-tag.step.yml
                parameters:
                  imageTagPattern: ${{ parameters.imageTagPattern }}
                  imageRepository: ${{ parameters.imageRepository }}
                  configName: ${{ parameters.configName }}
                  resourceName: ${{ parameters.resourceName }}
                  resourceType: ${{ parameters.resourceType }}
                  includeRegistryMetadata: false

              - template: ../steps/app-docker-buildx-validate.step.yml
                parameters:
                  dockerfilePath: ${{ parameters.dockerfilePath }}
                  buildContext: ${{ parameters.buildContext }}
                  imageRepository: ${{ parameters.imageRepository }}
        """;

    internal const string PrCodeJob = """
        # PR validation job for code-mode applications - Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: runtimeVersion
            type: string
            default: '8.0'
          - name: sourcePath
            type: string
            default: '.'
          - name: testCommand
            type: string
            default: ''
          - name: buildCommand
            type: string
            default: ''
          - name: runUnitTests
            type: boolean
            default: false
          - name: testFramework
            type: string
            default: ''
          - name: testResultsFormat
            type: string
            default: 'VSTest'
          - name: testResultsPath
            type: string
            default: '$(Common.TestResultsDirectory)/**/*.trx'
          - name: publishTestResults
            type: boolean
            default: false
          - name: publishCodeCoverage
            type: boolean
            default: false
          - name: coverageTool
            type: string
            default: 'Cobertura'
          - name: coverageReportPath
            type: string
            default: '$(Common.TestResultsDirectory)/**/coverage.cobertura.xml'

        jobs:
          - job: ValidateApplicationCode
            displayName: 'Validate pull request application code'
            steps:
              - checkout: self
                fetchDepth: 0

              - template: ../steps/app-sdk-setup.step.yml
                parameters:
                  runtimeStack: ${{ parameters.runtimeStack }}
                  runtimeVersion: ${{ parameters.runtimeVersion }}

              - template: ../steps/app-build-code.step.yml
                parameters:
                  runtimeStack: ${{ parameters.runtimeStack }}
                  sourcePath: ${{ parameters.sourcePath }}
                  testCommand: ${{ parameters.testCommand }}
                  buildCommand: ${{ parameters.buildCommand }}
                  runUnitTests: ${{ parameters.runUnitTests }}
                  testFramework: ${{ parameters.testFramework }}
                  testResultsFormat: ${{ parameters.testResultsFormat }}
                  testResultsPath: ${{ parameters.testResultsPath }}
                  publishTestResults: ${{ parameters.publishTestResults }}
                  publishCodeCoverage: ${{ parameters.publishCodeCoverage }}
                  coverageTool: ${{ parameters.coverageTool }}
                  coverageReportPath: ${{ parameters.coverageReportPath }}
        """;

    internal const string ReleaseContainerJob = """
        # Release deployment job (per environment) for container-mode apps — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: envShortName
            type: string
          - name: envName
            type: string

        jobs:
          - deployment: Deploy_${{ parameters.envShortName }}
            displayName: 'Deploy ${{ parameters.resourceName }} to ${{ parameters.envName }}'
            environment: ${{ parameters.envShortName }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: none

                    - template: ../steps/app-load-metadata.step.yml

                    - template: ../steps/app-acr-promote.step.yml
                      parameters:
                        imageRepository: ${{ parameters.imageRepository }}
                        promotionStrategy: ${{ parameters.promotionStrategy }}
                        envShortName: ${{ parameters.envShortName }}

                    - template: ../steps/app-deploy-container.step.yml
                      parameters:
                        resourceType: ${{ parameters.resourceType }}
                        imageRepository: ${{ parameters.imageRepository }}
        """;

    internal const string ReleaseCodeJob = """
        # Release deployment job (per environment) for code-mode apps — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: envShortName
            type: string
          - name: envName
            type: string

        jobs:
          - deployment: Deploy_${{ parameters.envShortName }}
            displayName: 'Deploy ${{ parameters.resourceName }} to ${{ parameters.envName }}'
            environment: ${{ parameters.envShortName }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: none

                    - template: ../steps/app-load-metadata.step.yml

                    - template: ../steps/app-deploy-code.step.yml
                      parameters:
                        resourceType: ${{ parameters.resourceType }}
        """;
}
