namespace InfraFlowSculptor.PipelineGeneration.Generators.App.SharedTemplates;

/// <summary>
/// Provides the shared application pipeline step templates.
/// </summary>
internal static class AppPipelineStepTemplates
{
    internal const string ComputeReleaseTagStep = """
        # Compute immutable release tag and write metadata.json — Auto-generated by InfraFlowSculptor

        parameters:
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: imageRepository
            type: string
          - name: configName
            type: string
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: containerRegistryName
            type: string
            default: ''
          - name: includeRegistryMetadata
            type: boolean
            default: false

        steps:
          - powershell: |
              $sourceVersion = '$(Build.SourceVersion)'
              $shortShaLength = [Math]::Min(7, $sourceVersion.Length)
              $shortSha = $sourceVersion.Substring(0, $shortShaLength)
              $branchName = '$(Build.SourceBranchName)'
              $sanitizedBranch = $branchName.Replace('/', '-').Replace('_', '-').ToLowerInvariant()
              $releaseTag = '${{ parameters.imageTagPattern }}'
              $releaseTag = $releaseTag.Replace('{buildNumber}', '$(Build.BuildNumber)')
              $releaseTag = $releaseTag.Replace('{shortSha}', $shortSha)
              $releaseTag = $releaseTag.Replace('{branch}', $sanitizedBranch)
              $releaseTag = $releaseTag.ToLowerInvariant()

              if ('${{ parameters.includeRegistryMetadata }}' -eq 'True') {
                  $sourceRegistryName = '$(containerRegistryName)'
                  if ([string]::IsNullOrWhiteSpace($sourceRegistryName) -or $sourceRegistryName -eq '$(containerRegistryName)') {
                      $sourceRegistryName = '${{ parameters.containerRegistryName }}'
                  }

                  $sourceRegistryLoginServer = '$(containerRegistryLoginServer)'
                  if ([string]::IsNullOrWhiteSpace($sourceRegistryLoginServer) -or $sourceRegistryLoginServer -eq '$(containerRegistryLoginServer)') {
                      $sourceRegistryLoginServer = '${{ parameters.containerRegistryName }}.azurecr.io'
                  }
              }
              else {
                  $sourceRegistryName = ''
                  $sourceRegistryLoginServer = ''
              }

              $metadataDirectory = '$(Build.ArtifactStagingDirectory)/app-metadata'
              New-Item -ItemType Directory -Path $metadataDirectory -Force | Out-Null

              $metadata = [ordered]@{
                  releaseTag = $releaseTag
                  shortSha = $shortSha
                  imageRepository = '${{ parameters.imageRepository }}'
                  sourceRegistryName = $sourceRegistryName
                  sourceRegistryLoginServer = $sourceRegistryLoginServer
                  configName = '${{ parameters.configName }}'
                  resourceName = '${{ parameters.resourceName }}'
                  resourceType = '${{ parameters.resourceType }}'
                  promotionStrategy = '${{ parameters.promotionStrategy }}'
              }

              $metadata | ConvertTo-Json | Set-Content -LiteralPath "$metadataDirectory/metadata.json" -Encoding utf8
              Write-Host "##vso[task.setvariable variable=ReleaseTag]$releaseTag"
              Write-Host "##vso[task.setvariable variable=ShortSha]$shortSha"
            displayName: 'Compute immutable release tag'
        """;

    internal const string AcrLoginStep = """
        # Authenticate to Azure Container Registry — Auto-generated by InfraFlowSculptor

        parameters:
          - name: acrAuthMode
            type: string
            default: 'ServiceConnection'
          - name: containerRegistryServiceConnection
            type: string
            default: '$(containerRegistryServiceConnection)'

        steps:
          - ${{ if eq(parameters.acrAuthMode, 'AdminCredentials') }}:
            - powershell: |
                $password = '$(containerRegistryPassword)'
                $password | docker login "$(containerRegistryLoginServer)" --username "$(containerRegistryUsername)" --password-stdin
                if ($LASTEXITCODE -ne 0) {
                    throw 'Docker login failed.'
                }
              displayName: 'Authenticate to ACR with admin credentials'

          - ${{ if ne(parameters.acrAuthMode, 'AdminCredentials') }}:
            - task: Docker@2
              displayName: 'Authenticate to ACR'
              inputs:
                command: login
                containerRegistry: ${{ parameters.containerRegistryServiceConnection }}
        """;

    internal const string DockerBuildxPushStep = """
        # Build and push immutable Docker image tags — Auto-generated by InfraFlowSculptor

        parameters:
          - name: dockerfilePath
            type: string
            default: 'Dockerfile'
          - name: buildContext
            type: string
            default: '.'
          - name: imageRepository
            type: string
          - name: containerRegistryName
            type: string
            default: ''

        steps:
          - powershell: |
              $registryLoginServer = '$(containerRegistryLoginServer)'
              if ([string]::IsNullOrWhiteSpace($registryLoginServer) -or $registryLoginServer -eq '$(containerRegistryLoginServer)') {
                  $registryLoginServer = '${{ parameters.containerRegistryName }}.azurecr.io'
              }

              docker buildx inspect ifs-builder *> $null
              if ($LASTEXITCODE -ne 0) {
                  docker buildx create --name ifs-builder --use | Out-Null
                  if ($LASTEXITCODE -ne 0) {
                      throw 'Docker buildx create failed.'
                  }
              }

              docker buildx use ifs-builder | Out-Null
              if ($LASTEXITCODE -ne 0) {
                  throw 'Docker buildx use failed.'
              }

              $createdAt = [DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')
              docker buildx build `
                --file "${{ parameters.dockerfilePath }}" `
                --label "org.opencontainers.image.revision=$(Build.SourceVersion)" `
                --label "org.opencontainers.image.version=$(ReleaseTag)" `
                --label "org.opencontainers.image.source=$(Build.Repository.Uri)" `
                --label "org.opencontainers.image.created=$createdAt" `
                --tag "$registryLoginServer/${{ parameters.imageRepository }}:$(ReleaseTag)" `
                --tag "$registryLoginServer/${{ parameters.imageRepository }}:sha-$(ShortSha)" `
                --push `
                "${{ parameters.buildContext }}"
              if ($LASTEXITCODE -ne 0) {
                  throw 'Docker buildx build failed.'
              }
            displayName: 'Build and push immutable image tags'
        """;

    internal const string DockerBuildxValidateStep = """
        # Validate Docker image build without publishing tags - Auto-generated by InfraFlowSculptor

        parameters:
          - name: dockerfilePath
            type: string
            default: 'Dockerfile'
          - name: buildContext
            type: string
            default: '.'
          - name: imageRepository
            type: string

        steps:
          - powershell: |
              $imageTag = '${{ parameters.imageRepository }}:pr-$(Build.BuildId)'
              docker build `
                --file "${{ parameters.dockerfilePath }}" `
                --label "org.opencontainers.image.revision=$(Build.SourceVersion)" `
                --label "org.opencontainers.image.source=$(Build.Repository.Uri)" `
                --tag "$imageTag" `
                "${{ parameters.buildContext }}"
              if ($LASTEXITCODE -ne 0) {
                  throw 'Docker build validation failed.'
              }
            displayName: 'Validate Docker image build'
        """;

    internal const string TrivyScanStep = """
        # Scan container image with Trivy — Auto-generated by InfraFlowSculptor

        parameters:
          - name: imageRepository
            type: string
          - name: containerRegistryName
            type: string
            default: ''
          - name: severity
            type: string
            default: 'HIGH,CRITICAL'

        steps:
          - powershell: |
              $toolDirectory = '$(Agent.TempDirectory)/supply-chain-tools'
              New-Item -ItemType Directory -Path $toolDirectory -Force | Out-Null

              $release = Invoke-RestMethod -Uri 'https://api.github.com/repos/aquasecurity/trivy/releases/latest'
              $asset = $release.assets | Where-Object { $_.name -match 'windows.*(64bit|amd64|x86_64).*\.zip$' } | Select-Object -First 1
              if ($null -eq $asset) {
                  throw 'Could not resolve a Trivy Windows zip asset.'
              }

              $archivePath = Join-Path $toolDirectory $asset.name
              Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $archivePath
              Expand-Archive -Path $archivePath -DestinationPath $toolDirectory -Force
              Write-Host "##vso[task.prependpath]$toolDirectory"
            displayName: 'Install Trivy'

          - powershell: |
              $registryLoginServer = '$(containerRegistryLoginServer)'
              if ([string]::IsNullOrWhiteSpace($registryLoginServer) -or $registryLoginServer -eq '$(containerRegistryLoginServer)') {
                  $registryLoginServer = '${{ parameters.containerRegistryName }}.azurecr.io'
              }

              $artifactDirectory = '$(Build.ArtifactStagingDirectory)/supply-chain'
              New-Item -ItemType Directory -Path $artifactDirectory -Force | Out-Null
              trivy image --scanners vuln --severity ${{ parameters.severity }} --ignore-unfixed --format json --output "$artifactDirectory/trivy-report.json" --exit-code 1 "$registryLoginServer/${{ parameters.imageRepository }}:$(ReleaseTag)"
              if ($LASTEXITCODE -ne 0) {
                  throw 'Trivy scan failed.'
              }
            displayName: 'Scan image with Trivy'
        """;

    internal const string SyftSbomStep = """
        # Generate CycloneDX SBOM with Syft — Auto-generated by InfraFlowSculptor

        parameters:
          - name: imageRepository
            type: string
          - name: containerRegistryName
            type: string
            default: ''

        steps:
          - powershell: |
              $toolDirectory = '$(Agent.TempDirectory)/supply-chain-tools'
              New-Item -ItemType Directory -Path $toolDirectory -Force | Out-Null

              $release = Invoke-RestMethod -Uri 'https://api.github.com/repos/anchore/syft/releases/latest'
              $asset = $release.assets | Where-Object { $_.name -match 'windows.*(amd64|x86_64).*\.zip$' } | Select-Object -First 1
              if ($null -eq $asset) {
                  throw 'Could not resolve a Syft Windows zip asset.'
              }

              $archivePath = Join-Path $toolDirectory $asset.name
              Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $archivePath
              Expand-Archive -Path $archivePath -DestinationPath $toolDirectory -Force
              Write-Host "##vso[task.prependpath]$toolDirectory"

              $registryLoginServer = '$(containerRegistryLoginServer)'
              if ([string]::IsNullOrWhiteSpace($registryLoginServer) -or $registryLoginServer -eq '$(containerRegistryLoginServer)') {
                  $registryLoginServer = '${{ parameters.containerRegistryName }}.azurecr.io'
              }

              $artifactDirectory = '$(Build.ArtifactStagingDirectory)/supply-chain'
              New-Item -ItemType Directory -Path $artifactDirectory -Force | Out-Null
              syft "$registryLoginServer/${{ parameters.imageRepository }}:$(ReleaseTag)" -o cyclonedx-json | Set-Content -LiteralPath "$artifactDirectory/sbom.cyclonedx.json" -Encoding utf8
              if ($LASTEXITCODE -ne 0) {
                  throw 'Syft SBOM generation failed.'
              }
            displayName: 'Generate SBOM'
        """;

    internal const string LoadMetadataStep = """
        # Load CI release metadata from artifact — Auto-generated by InfraFlowSculptor

        steps:
          - download: ci
            artifact: app-metadata
            displayName: 'Download CI metadata'

          - powershell: |
              $metadataPath = '$(Pipeline.Workspace)/app-metadata/metadata.json'
              if (-not (Test-Path -LiteralPath $metadataPath)) {
                  throw "Metadata artifact not found: $metadataPath"
              }
              $metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json
              Write-Host "##vso[task.setvariable variable=ReleaseTag]$($metadata.releaseTag)"
              Write-Host "##vso[task.setvariable variable=ImageRepository]$($metadata.imageRepository)"
              Write-Host "##vso[task.setvariable variable=SourceRegistryName]$($metadata.sourceRegistryName)"
              Write-Host "##vso[task.setvariable variable=SourceRegistryLoginServer]$($metadata.sourceRegistryLoginServer)"
            displayName: 'Load release metadata'
        """;

    internal const string AcrPromoteStep = """
        # Promote container image between ACR registries — Auto-generated by InfraFlowSculptor

        parameters:
          - name: imageRepository
            type: string
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: envShortName
            type: string

        steps:
          - task: AzureCLI@2
            displayName: 'Promote image in ACR'
            inputs:
              azureSubscription: $(azureResourceManagerConnection)
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                $imageRepository = '$(ImageRepository)'
                if ([string]::IsNullOrWhiteSpace($imageRepository) -or $imageRepository -eq '$(ImageRepository)') {
                    $imageRepository = '${{ parameters.imageRepository }}'
                }

                if ('${{ parameters.promotionStrategy }}' -eq 'AcrImport' -and '$(containerRegistryLoginServer)' -ne '$(SourceRegistryLoginServer)') {
                    az acr import --name "$(containerRegistryName)" --source "$(SourceRegistryLoginServer)/$imageRepository:$(ReleaseTag)" --image "$imageRepository:$(ReleaseTag)" --force
                    if ($LASTEXITCODE -ne 0) {
                        throw 'ACR immutable tag promotion failed.'
                    }
                }

                az acr import --name "$(containerRegistryName)" --source "$(containerRegistryLoginServer)/$imageRepository:$(ReleaseTag)" --image "$imageRepository:env-${{ parameters.envShortName }}" --force
                if ($LASTEXITCODE -ne 0) {
                    throw 'ACR environment tag promotion failed.'
                }
        """;

    internal const string DeployContainerStep = """
        # Deploy container image to compute resource — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceType
            type: string
          - name: imageRepository
            type: string

        steps:
          - ${{ if eq(parameters.resourceType, 'ContainerApp') }}:
            - task: AzureCLI@2
              displayName: 'Deploy image to Container App'
              inputs:
                azureSubscription: $(azureResourceManagerConnection)
                scriptType: ps
                scriptLocation: inlineScript
                inlineScript: |
                  $imageRepository = '$(ImageRepository)'
                  if ([string]::IsNullOrWhiteSpace($imageRepository) -or $imageRepository -eq '$(ImageRepository)') {
                      $imageRepository = '${{ parameters.imageRepository }}'
                  }

                  az containerapp update --name "$(containerAppName)" --resource-group "$(resourceGroupName)" --image "$(containerRegistryLoginServer)/$imageRepository:$(ReleaseTag)"
                  if ($LASTEXITCODE -ne 0) {
                      throw 'Container App image deployment failed.'
                  }

          - ${{ if eq(parameters.resourceType, 'WebApp') }}:
            - task: AzureWebApp@1
              displayName: 'Deploy container image to Web App'
              inputs:
                azureSubscription: $(azureResourceManagerConnection)
                appType: webAppContainer
                appName: $(webAppName)
                containers: $(containerRegistryLoginServer)/$(ImageRepository):$(ReleaseTag)

          - ${{ if eq(parameters.resourceType, 'FunctionApp') }}:
            - task: AzureFunctionApp@2
              displayName: 'Deploy container image to Function App'
              inputs:
                azureSubscription: $(azureResourceManagerConnection)
                appType: functionAppContainer
                appName: $(functionAppName)
                containers: $(containerRegistryLoginServer)/$(ImageRepository):$(ReleaseTag)
        """;

    internal const string DeployCodeStep = """
        # Deploy application package to compute resource — Auto-generated by InfraFlowSculptor

        parameters:
          - name: resourceType
            type: string

        steps:
          - download: ci
            artifact: application-package
            displayName: 'Download application package'

          - ${{ if eq(parameters.resourceType, 'WebApp') }}:
            - task: AzureWebApp@1
              displayName: 'Deploy package to Web App'
              inputs:
                azureSubscription: $(azureResourceManagerConnection)
                appType: webApp
                appName: $(webAppName)
                package: $(Pipeline.Workspace)/application-package

          - ${{ if eq(parameters.resourceType, 'FunctionApp') }}:
            - task: AzureFunctionApp@2
              displayName: 'Deploy package to Function App'
              inputs:
                azureSubscription: $(azureResourceManagerConnection)
                appType: functionApp
                appName: $(functionAppName)
                package: $(Pipeline.Workspace)/application-package
        """;

    internal const string SdkSetupStep = """
        # Install runtime SDK based on stack — Auto-generated by InfraFlowSculptor

        parameters:
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: runtimeVersion
            type: string
            default: '8.0'

        steps:
          - ${{ if or(eq(parameters.runtimeStack, 'DOTNETCORE'), eq(parameters.runtimeStack, 'DOTNET')) }}:
            - task: UseDotNet@2
              displayName: 'Setup .NET SDK'
              inputs:
                packageType: sdk
                version: ${{ parameters.runtimeVersion }}.x

          - ${{ if or(eq(parameters.runtimeStack, 'NODE'), eq(parameters.runtimeStack, 'NODEJS')) }}:
            - task: UseNode@1
              displayName: 'Setup Node.js'
              inputs:
                version: ${{ parameters.runtimeVersion }}.x

          - ${{ if eq(parameters.runtimeStack, 'PYTHON') }}:
            - task: UsePythonVersion@0
              displayName: 'Setup Python'
              inputs:
                versionSpec: ${{ parameters.runtimeVersion }}

          - ${{ if eq(parameters.runtimeStack, 'JAVA') }}:
            - task: JavaToolInstaller@0
              displayName: 'Setup Java'
              inputs:
                versionSpec: ${{ parameters.runtimeVersion }}
                jdkArchitectureOption: x64
                jdkSourceOption: PreInstalled
        """;

    internal const string DependencyScanStep = """
        # Scan dependencies for known vulnerabilities - Auto-generated by InfraFlowSculptor

        parameters:
          - name: dependencyScanTool
            type: string
            default: 'OWASPDependencyCheck'
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: sourcePath
            type: string
            default: '.'

        steps:
          - ${{ if eq(parameters.dependencyScanTool, 'OWASPDependencyCheck') }}:
            - powershell: |
                $toolDirectory = '$(Agent.TempDirectory)/dependency-check'
                New-Item -ItemType Directory -Path $toolDirectory -Force | Out-Null

                $release = Invoke-RestMethod -Uri 'https://api.github.com/repos/jeremylong/DependencyCheck/releases/latest'
                $asset = $release.assets | Where-Object { $_.name -match '\.zip$' -and $_.name -notmatch 'ant' } | Select-Object -First 1
                if ($null -eq $asset) {
                    throw 'Could not resolve an OWASP Dependency-Check release asset.'
                }

                $archivePath = Join-Path $toolDirectory $asset.name
                Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $archivePath
                Expand-Archive -Path $archivePath -DestinationPath $toolDirectory -Force

                $dcScript = Get-ChildItem -Path $toolDirectory -Filter 'dependency-check.bat' -Recurse | Select-Object -First 1
                if ($null -eq $dcScript) {
                    throw 'dependency-check.bat not found after extraction.'
                }

                & $dcScript.FullName --project "$(Build.Repository.Name)" --scan "${{ parameters.sourcePath }}" --format JSON --out "$(Build.ArtifactStagingDirectory)/dependency-scan"
                if ($LASTEXITCODE -ne 0) {
                    Write-Warning 'OWASP Dependency-Check reported vulnerabilities.'
                }
              displayName: 'OWASP Dependency-Check scan'
              workingDirectory: ${{ parameters.sourcePath }}

          - ${{ if eq(parameters.dependencyScanTool, 'NpmAudit') }}:
            - powershell: |
                $reportPath = '$(Build.ArtifactStagingDirectory)/dependency-scan'
                New-Item -ItemType Directory -Path $reportPath -Force | Out-Null
                npm audit --json > "$reportPath/npm-audit-report.json"
                if ($LASTEXITCODE -gt 0) {
                    Write-Warning 'npm audit reported vulnerabilities.'
                }
              displayName: 'npm audit scan'
              workingDirectory: ${{ parameters.sourcePath }}

          - ${{ if eq(parameters.dependencyScanTool, 'PipAudit') }}:
            - powershell: |
                pip install pip-audit --quiet
                $reportPath = '$(Build.ArtifactStagingDirectory)/dependency-scan'
                New-Item -ItemType Directory -Path $reportPath -Force | Out-Null
                pip-audit --format json --output "$reportPath/pip-audit-report.json"
                if ($LASTEXITCODE -ne 0) {
                    Write-Warning 'pip-audit reported vulnerabilities.'
                }
              displayName: 'pip-audit scan'
              workingDirectory: ${{ parameters.sourcePath }}

          - task: PublishPipelineArtifact@1
            displayName: 'Publish dependency scan report'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/dependency-scan'
              artifact: 'dependency-scan'
            condition: succeededOrFailed()
        """;

    internal const string DependencyCacheStep = """
        # Cache dependencies for faster builds - Auto-generated by InfraFlowSculptor

        parameters:
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'

        steps:
          - ${{ if or(eq(parameters.runtimeStack, 'DOTNETCORE'), eq(parameters.runtimeStack, 'DOTNET')) }}:
            - task: Cache@2
              displayName: 'Cache NuGet packages'
              inputs:
                key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
                restoreKeys: |
                  nuget | "$(Agent.OS)"
                path: $(NUGET_PACKAGES)

          - ${{ if or(eq(parameters.runtimeStack, 'NODE'), eq(parameters.runtimeStack, 'NODEJS')) }}:
            - task: Cache@2
              displayName: 'Cache npm packages'
              inputs:
                key: 'npm | "$(Agent.OS)" | **/package-lock.json'
                restoreKeys: |
                  npm | "$(Agent.OS)"
                path: $(npm_config_cache)

          - ${{ if eq(parameters.runtimeStack, 'PYTHON') }}:
            - task: Cache@2
              displayName: 'Cache pip packages'
              inputs:
                key: 'pip | "$(Agent.OS)" | **/requirements.txt'
                restoreKeys: |
                  pip | "$(Agent.OS)"
                path: $(PIP_CACHE_DIR)

          - ${{ if eq(parameters.runtimeStack, 'JAVA') }}:
            - task: Cache@2
              displayName: 'Cache Maven packages'
              inputs:
                key: 'maven | "$(Agent.OS)" | **/pom.xml'
                restoreKeys: |
                  maven | "$(Agent.OS)"
                path: $(MAVEN_REPO_LOCAL)
        """;

    internal const string SmokeTestStep = """
        # Run smoke tests after deployment - Auto-generated by InfraFlowSculptor

        parameters:
          - name: smokeTestCommand
            type: string
            default: ''

        steps:
          - powershell: |
              $command = '${{ parameters.smokeTestCommand }}'
              if ([string]::IsNullOrWhiteSpace($command)) {
                  Write-Host 'No smoke test command configured - skipping.'
                  exit 0
              }

              Write-Host "Running smoke test: $command"
              Invoke-Expression $command
              if ($LASTEXITCODE -ne 0) {
                  throw "Smoke test failed with exit code $LASTEXITCODE"
              }
            displayName: 'Run smoke tests'
        """;

    internal const string BuildCodeStep = """
        # Build, test and package application source — Auto-generated by InfraFlowSculptor

        parameters:
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: sourcePath
            type: string
            default: '.'
          - name: testCommand
            type: string
            default: ''
          - name: buildCommand
            type: string
            default: ''
          - name: runUnitTests
            type: boolean
            default: false
          - name: testFramework
            type: string
            default: ''
          - name: testResultsFormat
            type: string
            default: 'VSTest'
          - name: testResultsPath
            type: string
            default: '$(Common.TestResultsDirectory)/**/*.trx'
          - name: publishTestResults
            type: boolean
            default: false
          - name: publishCodeCoverage
            type: boolean
            default: false
          - name: coverageTool
            type: string
            default: 'Cobertura'
          - name: coverageReportPath
            type: string
            default: '$(Common.TestResultsDirectory)/**/coverage.cobertura.xml'

        steps:
          # ── Test (custom command, runs before build) ─────────────────
          - ${{ if and(eq(parameters.runUnitTests, true), ne(parameters.testCommand, '')) }}:
            - powershell: |
                ${{ parameters.testCommand }}
              displayName: 'Run application tests'
              workingDirectory: ${{ parameters.sourcePath }}

          # ── Build (custom command — overrides defaults) ──────────────
          - ${{ if ne(parameters.buildCommand, '') }}:
            - powershell: |
                ${{ parameters.buildCommand }}
              displayName: 'Build and package application'
              workingDirectory: ${{ parameters.sourcePath }}

          # ── Build (.NET default) ─────────────────────────────────────
          - ${{ if and(eq(parameters.buildCommand, ''), or(eq(parameters.runtimeStack, 'DOTNETCORE'), eq(parameters.runtimeStack, 'DOTNET'))) }}:
            - powershell: |
                dotnet restore
                dotnet build --configuration Release --no-restore
              displayName: 'Restore and build .NET application'
              workingDirectory: ${{ parameters.sourcePath }}

            - ${{ if and(eq(parameters.runUnitTests, true), eq(parameters.testCommand, '')) }}:
              - ${{ if eq(parameters.publishCodeCoverage, true) }}:
                - powershell: |
                    dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --results-directory "$(Common.TestResultsDirectory)" --collect "XPlat Code Coverage"
                  displayName: 'Run automated tests'
                  workingDirectory: ${{ parameters.sourcePath }}

              - ${{ if ne(parameters.publishCodeCoverage, true) }}:
                - powershell: |
                    dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --results-directory "$(Common.TestResultsDirectory)"
                  displayName: 'Run automated tests'
                  workingDirectory: ${{ parameters.sourcePath }}

            - ${{ if and(eq(parameters.runUnitTests, true), eq(parameters.publishTestResults, true)) }}:
              - task: PublishTestResults@2
                displayName: 'Publish test results'
                inputs:
                  testResultsFormat: ${{ parameters.testResultsFormat }}
                  testResultsFiles: ${{ parameters.testResultsPath }}
                  failTaskOnFailedTests: true

            - ${{ if and(eq(parameters.runUnitTests, true), eq(parameters.publishCodeCoverage, true)) }}:
              - task: PublishCodeCoverageResults@2
                displayName: 'Publish code coverage'
                inputs:
                  codeCoverageTool: ${{ parameters.coverageTool }}
                  summaryFileLocation: ${{ parameters.coverageReportPath }}
                  failIfCoverageEmpty: false

            - powershell: |
                dotnet publish --configuration Release --no-build --output "$(Build.ArtifactStagingDirectory)/application-package"
              displayName: 'Publish application package'
              workingDirectory: ${{ parameters.sourcePath }}

          # ── Build (Node.js default) ──────────────────────────────────
          - ${{ if and(eq(parameters.buildCommand, ''), or(eq(parameters.runtimeStack, 'NODE'), eq(parameters.runtimeStack, 'NODEJS'))) }}:
            - powershell: |
                npm ci
                if ($LASTEXITCODE -ne 0) {
                    throw 'npm ci failed.'
                }

                if ('${{ eq(parameters.runUnitTests, true) }}' -eq 'True' -and '${{ eq(parameters.testCommand, '') }}' -eq 'True') {
                    npm run test --if-present
                    if ($LASTEXITCODE -ne 0) {
                        throw 'npm run test failed.'
                    }
                }

                npm run build
                if ($LASTEXITCODE -ne 0) {
                    throw 'npm run build failed.'
                }

                $packagePath = '$(Build.ArtifactStagingDirectory)/application-package'
                New-Item -ItemType Directory -Path $packagePath -Force | Out-Null
                if (Test-Path -LiteralPath 'dist') {
                    Copy-Item -Path 'dist/*' -Destination $packagePath -Recurse -Force
                }
                elseif (Test-Path -LiteralPath 'build') {
                    Copy-Item -Path 'build/*' -Destination $packagePath -Recurse -Force
                }
                else {
                    Get-ChildItem -Force | Copy-Item -Destination $packagePath -Recurse -Force
                }
              displayName: 'Build and package Node.js application'
              workingDirectory: ${{ parameters.sourcePath }}

          # ── Build (Python default) ───────────────────────────────────
          - ${{ if and(eq(parameters.buildCommand, ''), eq(parameters.runtimeStack, 'PYTHON')) }}:
            - powershell: |
                python -m pip install -r requirements.txt
                if ($LASTEXITCODE -ne 0) {
                    throw 'python -m pip install failed.'
                }

                $packagePath = '$(Build.ArtifactStagingDirectory)/application-package'
                New-Item -ItemType Directory -Path $packagePath -Force | Out-Null
                Get-ChildItem -Force | Copy-Item -Destination $packagePath -Recurse -Force
              displayName: 'Build and package Python application'
              workingDirectory: ${{ parameters.sourcePath }}
        """;
}
