namespace InfraFlowSculptor.PipelineGeneration.Generators.App.SharedTemplates;

/// <summary>
/// Provides the shared application pipeline wrapper templates.
/// </summary>
internal static class AppPipelinePipelineTemplates
{
    internal const string CiContainerPipeline = """
        # CI pipeline template for container-mode apps — Auto-generated by InfraFlowSculptor
        # Usage: extends: template: ../../.azuredevops/pipelines/app-ci-container.pipeline.yml

        parameters:
          - name: resourceName
            type: string
          - name: configName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: dockerfilePath
            type: string
            default: 'Dockerfile'
          - name: buildContext
            type: string
            default: '.'
          - name: containerRegistryName
            type: string
            default: ''
          - name: containerRegistryServiceConnection
            type: string
            default: '$(containerRegistryServiceConnection)'
          - name: acrAuthMode
            type: string
            default: 'ServiceConnection'
          - name: enableSecurityScans
            type: boolean
            default: true
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: buildSourceEnvVariablesPath
            type: string
            default: ''
          - name: variableGroups
            type: object
            default: []
          - name: agentPoolName
            type: string
            default: ''

        stages:
          - stage: Build
            displayName: 'Build, scan and publish image'
            pool:
              ${{ if eq(parameters.agentPoolName, '') }}:
                vmImage: 'ubuntu-latest'
              ${{ if ne(parameters.agentPoolName, '') }}:
                name: '${{ parameters.agentPoolName }}'
            ${{ if ne(parameters.buildSourceEnvVariablesPath, '') }}:
              variables:
                - template: ${{ parameters.buildSourceEnvVariablesPath }}
                - ${{ each group in parameters.variableGroups }}:
                  - group: ${{ group }}
            jobs:
              - template: ../jobs/app-ci-container.job.yml
                parameters:
                  resourceName: ${{ parameters.resourceName }}
                  configName: ${{ parameters.configName }}
                  resourceType: ${{ parameters.resourceType }}
                  imageRepository: ${{ parameters.imageRepository }}
                  imageTagPattern: ${{ parameters.imageTagPattern }}
                  dockerfilePath: ${{ parameters.dockerfilePath }}
                  buildContext: ${{ parameters.buildContext }}
                  containerRegistryName: ${{ parameters.containerRegistryName }}
                  containerRegistryServiceConnection: ${{ parameters.containerRegistryServiceConnection }}
                  acrAuthMode: ${{ parameters.acrAuthMode }}
                  enableSecurityScans: ${{ parameters.enableSecurityScans }}
                  promotionStrategy: ${{ parameters.promotionStrategy }}
        """;

    internal const string CiCodePipeline = """
        # CI pipeline template for code-mode apps — Auto-generated by InfraFlowSculptor
        # Usage: extends: template: ../../.azuredevops/pipelines/app-ci-code.pipeline.yml

        parameters:
          - name: resourceName
            type: string
          - name: configName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: runtimeVersion
            type: string
            default: '8.0'
          - name: sourcePath
            type: string
            default: '.'
          - name: testCommand
            type: string
            default: ''
          - name: buildCommand
            type: string
            default: ''
          - name: runUnitTests
            type: boolean
            default: false
          - name: testFramework
            type: string
            default: ''
          - name: testResultsFormat
            type: string
            default: 'VSTest'
          - name: testResultsPath
            type: string
            default: '$(Common.TestResultsDirectory)/**/*.trx'
          - name: publishTestResults
            type: boolean
            default: false
          - name: publishCodeCoverage
            type: boolean
            default: false
          - name: coverageTool
            type: string
            default: 'Cobertura'
          - name: coverageReportPath
            type: string
            default: '$(Common.TestResultsDirectory)/**/coverage.cobertura.xml'
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: enableDependencyCache
            type: boolean
            default: false
          - name: runDependencyScan
            type: boolean
            default: false
          - name: dependencyScanTool
            type: string
            default: 'OWASPDependencyCheck'
          - name: agentPoolName
            type: string
            default: ''

        stages:
          - stage: Build
            displayName: 'Build, test and publish package'
            pool:
              ${{ if eq(parameters.agentPoolName, '') }}:
                vmImage: 'ubuntu-latest'
              ${{ if ne(parameters.agentPoolName, '') }}:
                name: '${{ parameters.agentPoolName }}'
            jobs:
              - template: ../jobs/app-ci-code.job.yml
                parameters:
                  resourceName: ${{ parameters.resourceName }}
                  configName: ${{ parameters.configName }}
                  resourceType: ${{ parameters.resourceType }}
                  imageRepository: ${{ parameters.imageRepository }}
                  imageTagPattern: ${{ parameters.imageTagPattern }}
                  runtimeStack: ${{ parameters.runtimeStack }}
                  runtimeVersion: ${{ parameters.runtimeVersion }}
                  sourcePath: ${{ parameters.sourcePath }}
                  testCommand: ${{ parameters.testCommand }}
                  buildCommand: ${{ parameters.buildCommand }}
                  runUnitTests: ${{ parameters.runUnitTests }}
                  testFramework: ${{ parameters.testFramework }}
                  testResultsFormat: ${{ parameters.testResultsFormat }}
                  testResultsPath: ${{ parameters.testResultsPath }}
                  publishTestResults: ${{ parameters.publishTestResults }}
                  publishCodeCoverage: ${{ parameters.publishCodeCoverage }}
                  coverageTool: ${{ parameters.coverageTool }}
                  coverageReportPath: ${{ parameters.coverageReportPath }}
                  promotionStrategy: ${{ parameters.promotionStrategy }}
                  enableDependencyCache: ${{ parameters.enableDependencyCache }}
                  runDependencyScan: ${{ parameters.runDependencyScan }}
                  dependencyScanTool: ${{ parameters.dependencyScanTool }}
        """;

    internal const string PrContainerPipeline = """
        # PR validation pipeline template for container-mode apps - Auto-generated by InfraFlowSculptor
        # Usage: extends: template: ../../.azuredevops/pipelines/app-pr-container.pipeline.yml

        parameters:
          - name: resourceName
            type: string
          - name: configName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: imageTagPattern
            type: string
            default: '{buildNumber}-{shortSha}'
          - name: dockerfilePath
            type: string
            default: 'Dockerfile'
          - name: buildContext
            type: string
            default: '.'
          - name: agentPoolName
            type: string
            default: ''

        stages:
          - stage: Validate
            displayName: 'Validate pull request image build'
            pool:
              ${{ if eq(parameters.agentPoolName, '') }}:
                vmImage: 'ubuntu-latest'
              ${{ if ne(parameters.agentPoolName, '') }}:
                name: '${{ parameters.agentPoolName }}'
            jobs:
              - template: ../jobs/app-pr-container.job.yml
                parameters:
                  resourceName: ${{ parameters.resourceName }}
                  configName: ${{ parameters.configName }}
                  resourceType: ${{ parameters.resourceType }}
                  imageRepository: ${{ parameters.imageRepository }}
                  imageTagPattern: ${{ parameters.imageTagPattern }}
                  dockerfilePath: ${{ parameters.dockerfilePath }}
                  buildContext: ${{ parameters.buildContext }}
        """;

    internal const string PrCodePipeline = """
        # PR validation pipeline template for code-mode apps - Auto-generated by InfraFlowSculptor
        # Usage: extends: template: ../../.azuredevops/pipelines/app-pr-code.pipeline.yml

        parameters:
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: runtimeStack
            type: string
            default: 'DOTNETCORE'
          - name: runtimeVersion
            type: string
            default: '8.0'
          - name: sourcePath
            type: string
            default: '.'
          - name: testCommand
            type: string
            default: ''
          - name: buildCommand
            type: string
            default: ''
          - name: runUnitTests
            type: boolean
            default: false
          - name: testFramework
            type: string
            default: ''
          - name: testResultsFormat
            type: string
            default: 'VSTest'
          - name: testResultsPath
            type: string
            default: '$(Common.TestResultsDirectory)/**/*.trx'
          - name: publishTestResults
            type: boolean
            default: false
          - name: publishCodeCoverage
            type: boolean
            default: false
          - name: coverageTool
            type: string
            default: 'Cobertura'
          - name: coverageReportPath
            type: string
            default: '$(Common.TestResultsDirectory)/**/coverage.cobertura.xml'
          - name: agentPoolName
            type: string
            default: ''

        stages:
          - stage: Validate
            displayName: 'Validate pull request application code'
            pool:
              ${{ if eq(parameters.agentPoolName, '') }}:
                vmImage: 'ubuntu-latest'
              ${{ if ne(parameters.agentPoolName, '') }}:
                name: '${{ parameters.agentPoolName }}'
            jobs:
              - template: ../jobs/app-pr-code.job.yml
                parameters:
                  resourceName: ${{ parameters.resourceName }}
                  resourceType: ${{ parameters.resourceType }}
                  runtimeStack: ${{ parameters.runtimeStack }}
                  runtimeVersion: ${{ parameters.runtimeVersion }}
                  sourcePath: ${{ parameters.sourcePath }}
                  testCommand: ${{ parameters.testCommand }}
                  buildCommand: ${{ parameters.buildCommand }}
                  runUnitTests: ${{ parameters.runUnitTests }}
                  testFramework: ${{ parameters.testFramework }}
                  testResultsFormat: ${{ parameters.testResultsFormat }}
                  testResultsPath: ${{ parameters.testResultsPath }}
                  publishTestResults: ${{ parameters.publishTestResults }}
                  publishCodeCoverage: ${{ parameters.publishCodeCoverage }}
                  coverageTool: ${{ parameters.coverageTool }}
                  coverageReportPath: ${{ parameters.coverageReportPath }}
        """;

    internal const string ReleaseContainerPipeline = """
        # Release pipeline template for container-mode apps — Auto-generated by InfraFlowSculptor
        # Usage: extends: template: ../../.azuredevops/pipelines/app-release-container.pipeline.yml
        #
        # Each environment object must contain:
        #   shortName, name, variablesPath, variableGroups (list of strings)

        parameters:
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: imageRepository
            type: string
          - name: promotionStrategy
            type: string
            default: 'AcrImport'
          - name: agentPoolName
            type: string
            default: ''
          - name: runSmokeTests
            type: boolean
            default: false
          - name: smokeTestCommand
            type: string
            default: ''
          - name: environments
            type: object
            default: []

        stages:
          - ${{ each env in parameters.environments }}:
            - stage: Deploy_${{ env.shortName }}
              displayName: 'Promote and deploy to ${{ env.name }}'
              pool:
                ${{ if eq(parameters.agentPoolName, '') }}:
                  vmImage: 'ubuntu-latest'
                ${{ if ne(parameters.agentPoolName, '') }}:
                  name: '${{ parameters.agentPoolName }}'
              lockBehavior: sequential
              variables:
                - template: ${{ env.variablesPath }}
                - ${{ each group in env.variableGroups }}:
                  - group: ${{ group }}
              jobs:
                - template: ../jobs/app-release-container.job.yml
                  parameters:
                    resourceName: ${{ parameters.resourceName }}
                    resourceType: ${{ parameters.resourceType }}
                    imageRepository: ${{ parameters.imageRepository }}
                    promotionStrategy: ${{ parameters.promotionStrategy }}
                    envShortName: ${{ env.shortName }}
                    envName: ${{ env.name }}
                    runSmokeTests: ${{ parameters.runSmokeTests }}
                    smokeTestCommand: ${{ parameters.smokeTestCommand }}
        """;

    internal const string ReleaseCodePipeline = """
        # Release pipeline template for code-mode apps — Auto-generated by InfraFlowSculptor
        # Usage: extends: template: ../../.azuredevops/pipelines/app-release-code.pipeline.yml

        parameters:
          - name: resourceName
            type: string
          - name: resourceType
            type: string
          - name: agentPoolName
            type: string
            default: ''
          - name: runSmokeTests
            type: boolean
            default: false
          - name: smokeTestCommand
            type: string
            default: ''
          - name: environments
            type: object
            default: []

        stages:
          - ${{ each env in parameters.environments }}:
            - stage: Deploy_${{ env.shortName }}
              displayName: 'Deploy to ${{ env.name }}'
              pool:
                ${{ if eq(parameters.agentPoolName, '') }}:
                  vmImage: 'ubuntu-latest'
                ${{ if ne(parameters.agentPoolName, '') }}:
                  name: '${{ parameters.agentPoolName }}'
              lockBehavior: sequential
              variables:
                - template: ${{ env.variablesPath }}
                - ${{ each group in env.variableGroups }}:
                  - group: ${{ group }}
              jobs:
                - template: ../jobs/app-release-code.job.yml
                  parameters:
                    resourceName: ${{ parameters.resourceName }}
                    resourceType: ${{ parameters.resourceType }}
                    envShortName: ${{ env.shortName }}
                    envName: ${{ env.name }}
                    runSmokeTests: ${{ parameters.runSmokeTests }}
                    smokeTestCommand: ${{ parameters.smokeTestCommand }}
        """;
}
