using System.Text;

namespace InfraFlowSculptor.PipelineGeneration.Infra.Stages;

/// <summary>
/// Emits the <c>ci.pipeline.yml</c> per-configuration CI pipeline file.
/// Always executes regardless of mono-repo mode.
/// </summary>
public sealed class CiPipelineStage : IInfraPipelineStage
{
    /// <inheritdoc />
    public int Order => 100;

    /// <inheritdoc />
    public void Execute(InfraPipelineContext context)
    {
        context.Files["ci.pipeline.yml"] = GenerateConfigCiPipeline(
            context.ConfigName, context.Request.AgentPoolName, context.IsMonoRepo);
    }

    private static string GenerateConfigCiPipeline(string configName, string? agentPoolName, bool isMonoRepo)
    {
        var sharedTemplatePath = isMonoRepo
            ? "../Common/pipelines/ci.pipeline.yml"
            : "../.azuredevops/pipelines/ci.pipeline.yml";

        var sb = new StringBuilder();
        sb.AppendLine("# CI Pipeline — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(date:yyyyMMdd)");
        sb.AppendLine();
        sb.AppendLine("trigger:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        sb.AppendLine("      - release/*");
        sb.AppendLine("  paths:");
        sb.AppendLine("    include:");
        sb.AppendLine($"      - {configName}/*");
        if (isMonoRepo)
        {
            sb.AppendLine("      - .azuredevops/Common/*");
            sb.AppendLine($"      - .azuredevops/{configName}/*");
        }
        sb.AppendLine();
        PipelineGenerationEngine.AppendPool(sb, agentPoolName, string.Empty);
        sb.AppendLine();
        sb.AppendLine("extends:");
        sb.AppendLine($"  template: {sharedTemplatePath}");
        sb.AppendLine("  parameters:");
        sb.AppendLine("    continueOnError: true");
        sb.AppendLine($"    projectName: {configName}");

        return sb.ToString();
    }
}
