using System.Text;

namespace InfraFlowSculptor.PipelineGeneration.Infra.Stages;

/// <summary>
/// Shared builder for per-configuration pipeline files (CI and PR).
/// Extracts the common YAML structure used by both <see cref="CiPipelineStage"/>
/// and <see cref="PrPipelineStage"/>.
/// </summary>
internal static class ConfigPipelineBuilder
{
    /// <summary>
    /// Generates a per-configuration pipeline YAML file.
    /// </summary>
    /// <param name="options">The options specifying the differences between CI and PR pipelines.</param>
    /// <returns>The generated YAML content.</returns>
    internal static string Generate(ConfigPipelineOptions options)
    {
        var sharedTemplatePath = options.IsMonoRepo
            ? $"../Common/pipelines/{options.TemplateFileName}"
            : $"../.azuredevops/pipelines/{options.TemplateFileName}";

        var sb = new StringBuilder();
        sb.AppendLine($"# {options.CommentHeader} — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(date:yyyyMMdd)");
        sb.AppendLine();

        // Trigger section
        sb.AppendLine($"{options.TriggerKeyword}:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        foreach (var branch in options.TriggerBranches)
        {
            sb.AppendLine($"      - {branch}");
        }
        sb.AppendLine("  paths:");
        sb.AppendLine("    include:");
        sb.AppendLine($"      - {options.ConfigName}/*");
        if (options.IsMonoRepo)
        {
            sb.AppendLine("      - .azuredevops/Common/*");
            sb.AppendLine($"      - .azuredevops/{options.ConfigName}/*");
        }
        sb.AppendLine();

        PipelineGenerationEngine.AppendPool(sb, options.AgentPoolName, string.Empty);
        sb.AppendLine();

        sb.AppendLine("extends:");
        sb.AppendLine($"  template: {sharedTemplatePath}");
        sb.AppendLine("  parameters:");
        if (options.ContinueOnError)
        {
            sb.AppendLine("    continueOnError: true");
        }
        sb.AppendLine($"    projectName: {options.ConfigName}");

        return sb.ToString();
    }
}

/// <summary>
/// Options that parameterize the differences between CI and PR pipeline generation.
/// </summary>
internal sealed class ConfigPipelineOptions
{
    /// <summary>The configuration name used for path filters and the projectName parameter.</summary>
    internal required string ConfigName { get; init; }

    /// <summary>The agent pool name (optional).</summary>
    internal required string? AgentPoolName { get; init; }

    /// <summary>Whether this is a mono-repo layout.</summary>
    internal required bool IsMonoRepo { get; init; }

    /// <summary>The template file name (e.g. <c>"ci.pipeline.yml"</c> or <c>"pr.pipeline.yml"</c>).</summary>
    internal required string TemplateFileName { get; init; }

    /// <summary>The comment header (e.g. <c>"CI Pipeline"</c> or <c>"PR Validation Pipeline"</c>).</summary>
    internal required string CommentHeader { get; init; }

    /// <summary>The YAML trigger keyword (<c>"trigger"</c> for CI, <c>"pr"</c> for PR).</summary>
    internal required string TriggerKeyword { get; init; }

    /// <summary>The branches to include in the trigger.</summary>
    internal required IReadOnlyList<string> TriggerBranches { get; init; }

    /// <summary>Whether to include the <c>continueOnError: true</c> parameter.</summary>
    internal bool ContinueOnError { get; init; }
}
