using System.Text;
using InfraFlowSculptor.GenerationCore.Models;

namespace InfraFlowSculptor.PipelineGeneration.Infra.Stages;

/// <summary>
/// Emits the <c>variables/vars.yml</c> config-level variables file.
/// Skipped when <see cref="InfraPipelineContext.IsMonoRepo"/> is <c>true</c>.
/// </summary>
public sealed class ConfigVarsStage : IInfraPipelineStage
{
    /// <inheritdoc />
    public int Order => 400;

    /// <inheritdoc />
    public void Execute(InfraPipelineContext context)
    {
        if (context.IsMonoRepo)
        {
            return;
        }

        context.Files["variables/vars.yml"] = GenerateConfigVarsFile(context.Request.Environments);
    }

    private static string GenerateConfigVarsFile(IReadOnlyList<EnvironmentDefinition> environments)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Config-level variables — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("variables:");

        var armConnection = environments.FirstOrDefault(e => !string.IsNullOrEmpty(e.AzureResourceManagerConnection))?.AzureResourceManagerConnection;
        if (!string.IsNullOrEmpty(armConnection))
        {
            sb.AppendLine($"  azureResourceManagerConnection: '{armConnection}'");
        }

        return sb.ToString();
    }
}
