using System.Text;
using InfraFlowSculptor.GenerationCore.Models;

namespace InfraFlowSculptor.PipelineGeneration.Infra.Stages;

/// <summary>
/// Emits per-environment <c>variables/{env}.yml</c> files.
/// Skipped when <see cref="InfraPipelineContext.IsMonoRepo"/> is <c>true</c>.
/// </summary>
public sealed class EnvironmentVarsStage : IInfraPipelineStage
{
    /// <inheritdoc />
    public int Order => 500;

    /// <inheritdoc />
    public void Execute(InfraPipelineContext context)
    {
        if (context.IsMonoRepo)
        {
            return;
        }

        foreach (var env in context.Request.Environments)
        {
            var envKey = env.ShortName.ToLowerInvariant();
            context.Files[$"variables/{envKey}.yml"] = GenerateEnvironmentVariables(env);
        }
    }

    private static string GenerateEnvironmentVariables(EnvironmentDefinition env)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {env.Name} Variables — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("variables:");

        if (!string.IsNullOrEmpty(env.SubscriptionId))
        {
            sb.AppendLine($"  subscriptionId: '{env.SubscriptionId}'");
        }

        if (!string.IsNullOrEmpty(env.Location))
        {
            sb.AppendLine($"  location: '{env.Location}'");
        }

        return sb.ToString();
    }
}
