using InfraFlowSculptor.GenerationCore.Models;
using InfraFlowSculptor.PipelineGeneration.Infra;
using InfraFlowSculptor.PipelineGeneration.Infra.Stages;

namespace InfraFlowSculptor.PipelineGeneration.Tests.Infra.Stages;

/// <summary>
/// Unit tests for <see cref="ReleasePipelineStage"/>.
/// </summary>
public sealed class ReleasePipelineStageTests
{
    private readonly ReleasePipelineStage _sut = new();

    [Fact]
    public void Order_Is_300()
    {
        _sut.Order.Should().Be(300);
    }

    [Fact]
    public void Given_Context_When_Execute_Then_AddsReleasePipelineFile()
    {
        // Arrange
        var context = CreateContext(isMonoRepo: false);

        // Act
        _sut.Execute(context);

        // Assert
        context.Files.Should().ContainKey("release.pipeline.yml");
        context.Files["release.pipeline.yml"].Should().Contain("# Release Pipeline — Auto-generated by InfraFlowSculptor");
    }

    [Fact]
    public void Given_MonoRepoContext_When_Execute_Then_StillAddsReleasePipelineFile()
    {
        // Arrange
        var context = CreateContext(isMonoRepo: true);

        // Act
        _sut.Execute(context);

        // Assert
        context.Files.Should().ContainKey("release.pipeline.yml");
        context.Files["release.pipeline.yml"].Should().Contain("../Common/jobs/deploy.job.yml");
    }

    [Fact]
    public void Given_ContextWithEnvironments_When_Execute_Then_ContainsEnvironmentList()
    {
        // Arrange
        var context = CreateContext(isMonoRepo: false);

        // Act
        _sut.Execute(context);

        // Assert
        context.Files["release.pipeline.yml"].Should().Contain("value: dev,prd");
    }

    private static InfraPipelineContext CreateContext(bool isMonoRepo) => new()
    {
        Request = new GenerationRequest
        {
            Environments =
            [
                new EnvironmentDefinition { Name = "Development", ShortName = "dev", Location = "westeurope", SubscriptionId = "sub-1", AzureResourceManagerConnection = "arm-dev" },
                new EnvironmentDefinition { Name = "Production", ShortName = "prd", Location = "westeurope", SubscriptionId = "sub-2", AzureResourceManagerConnection = "arm-prd" },
            ],
        },
        ConfigName = "my-config",
        IsMonoRepo = isMonoRepo,
    };
}
