using System.Text;
using InfraFlowSculptor.PipelineGeneration.Models;

namespace InfraFlowSculptor.PipelineGeneration;

/// <summary>
/// Generates a self-contained <c>bootstrap.pipeline.yml</c> for Azure DevOps.
/// When executed once in Azure DevOps, the bootstrap pipeline provisions all pipeline definitions,
/// environments, and variable groups (with empty secret values) using Azure DevOps CLI and REST APIs.
/// All scripts are idempotent — re-running the pipeline will skip already-existing resources.
/// </summary>
public sealed class BootstrapPipelineGenerationEngine
{
    private const string BootstrapFileName = "bootstrap.pipeline.yml";
    private const string StepIndent = "        ";
    private const string StepBodyIndent = "            ";
    private const string StepPropertyIndent = "          ";

    /// <summary>
    /// Generates the bootstrap pipeline YAML file from the provided request.
    /// </summary>
    /// <param name="request">The bootstrap generation request containing pipelines, variable groups, and project metadata.</param>
    /// <returns>
    /// A <see cref="PipelineGenerationResult"/> containing a single file: <c>bootstrap.pipeline.yml</c>.
    /// </returns>
    public PipelineGenerationResult Generate(BootstrapGenerationRequest request)
    {
        var sb = new StringBuilder();

        GenerateHeader(sb, request);

        var hasProvisioningJob = false;

        if (request.Mode == BootstrapMode.ApplicationOnly)
        {
            // Application-only bootstrap: validate that the project-level shared resources owned
            // by the infra bootstrap are already provisioned, then create app pipeline definitions.
            if (request.Environments.Count > 0 || request.VariableGroups.Count > 0)
            {
                GenerateValidateSharedResourcesJob(sb, request);
                hasProvisioningJob = true;
            }

            if (request.Pipelines.Count > 0)
            {
                GeneratePipelineProvisionJob(
                    sb,
                    request,
                    dependsOn: request.Environments.Count > 0 || request.VariableGroups.Count > 0
                        ? "ValidateSharedResources"
                        : null);
                hasProvisioningJob = true;
            }
        }
        else
        {
            if (request.Pipelines.Count > 0)
            {
                GeneratePipelineProvisionJob(sb, request, dependsOn: null);
                hasProvisioningJob = true;
            }

            if (request.Environments.Count > 0)
            {
                GenerateEnvironmentProvisionJob(sb, request);
                hasProvisioningJob = true;
            }

            if (request.VariableGroups.Count > 0)
            {
                GenerateVariableGroupProvisionJob(sb, request);
                hasProvisioningJob = true;
            }
        }

        if (!hasProvisioningJob)
        {
            GenerateNoOpJob(sb, request);
        }

        var files = new Dictionary<string, string>
        {
            [BootstrapFileName] = sb.ToString(),
        };

        return new PipelineGenerationResult { TemplateFiles = files };
    }

    private static void GenerateHeader(StringBuilder sb, BootstrapGenerationRequest request)
    {
        var modeBanner = request.Mode == BootstrapMode.ApplicationOnly
            ? "Application-side bootstrap (SplitInfraCode). Validates shared project resources, then provisions application pipelines only."
            : "Infrastructure-side / standalone bootstrap. Owner of the shared project resources (environments, variable groups).";

        sb.AppendLine("# Bootstrap Pipeline — generated by InfraFlowSculptor");
        sb.AppendLine($"# {modeBanner}");
        sb.AppendLine("# Run this pipeline ONCE in Azure DevOps to provision the resources listed above.");
        sb.AppendLine("# All scripts are idempotent — re-running skips already-existing resources.");
        sb.AppendLine("#");
        sb.AppendLine("# Prerequisites:");
        sb.AppendLine("#   - The pipeline/job must expose $(System.AccessToken) to scripts");
        sb.AppendLine("#   - The build service identity must be allowed to manage pipelines, environments, and variable groups");
        sb.AppendLine("#   - The build service identity must also have Use permission on any agent pool referenced by the generated YAML");
        sb.AppendLine("#   - Service connections configured per environment in Azure DevOps");
        sb.AppendLine("#   - Azure CLI with azure-devops extension available on agent");

        if (request.Mode == BootstrapMode.ApplicationOnly)
        {
            sb.AppendLine("#   - Environments and variable groups must have been provisioned by the infra bootstrap first");
        }
        else
        {
            sb.AppendLine("#   - Approval-required environments are created automatically, but approver identities must still be configured manually in Azure DevOps");
        }

        sb.AppendLine();
        sb.AppendLine("trigger: none");
        sb.AppendLine();

        sb.AppendLine("name: bootstrap-$(Date:yyyyMMdd)$(Rev:.r)");
        sb.AppendLine();

        sb.AppendLine("variables:");
        sb.AppendLine($"  organizationUrl: 'https://dev.azure.com/{EscapeSingleQuotes(request.OrganizationName)}'");
        sb.AppendLine($"  projectName: '{EscapeSingleQuotes(request.ProjectName)}'");
        sb.AppendLine($"  repositoryName: '{EscapeSingleQuotes(request.RepositoryName)}'");
        sb.AppendLine($"  defaultBranch: '{EscapeSingleQuotes(request.DefaultBranch)}'");
        sb.AppendLine();
        sb.AppendLine("stages:");
        sb.AppendLine("- stage: BootstrapAzureDevOps");
        sb.AppendLine("  displayName: 'Bootstrap Azure DevOps'");
        sb.AppendLine("  jobs:");
    }

    private static void GeneratePipelineProvisionJob(StringBuilder sb, BootstrapGenerationRequest request, string? dependsOn)
    {
        AppendJobHeader(sb, "ProvisionPipelineDefinitions", "Provision Pipeline Definitions", request.AgentPoolName, dependsOn);
        GenerateConfigureStep(sb);
        GeneratePipelineCreationSteps(sb, request);
    }

    private static void GenerateEnvironmentProvisionJob(StringBuilder sb, BootstrapGenerationRequest request)
    {
        AppendJobHeader(sb, "ProvisionEnvironments", "Provision Environments", request.AgentPoolName, dependsOn: null);
        GenerateEnvironmentCreationSteps(sb, request);
    }

    private static void GenerateVariableGroupProvisionJob(StringBuilder sb, BootstrapGenerationRequest request)
    {
        AppendJobHeader(sb, "ProvisionVariableGroups", "Provision Variable Groups", request.AgentPoolName, dependsOn: null);
        GenerateConfigureStep(sb);
        GenerateVariableGroupCreationSteps(sb, request);
    }

    private static void GenerateNoOpJob(StringBuilder sb, BootstrapGenerationRequest request)
    {
        AppendJobHeader(sb, "NothingToProvision", "Nothing to Provision", request.AgentPoolName, dependsOn: null);
        sb.AppendLine($"{StepIndent}- powershell: |");
        sb.AppendLine($"{StepBodyIndent}Write-Host 'No pipelines, environments, or variable groups were requested for bootstrap.'");
        sb.AppendLine($"{StepPropertyIndent}displayName: 'No-op'");
        sb.AppendLine();
    }

    private static void GenerateValidateSharedResourcesJob(StringBuilder sb, BootstrapGenerationRequest request)
    {
        AppendJobHeader(sb, "ValidateSharedResources", "Validate Shared Project Resources", request.AgentPoolName, dependsOn: null);
        GenerateConfigureStep(sb);
        GenerateValidateSharedResourcesSteps(sb, request);
    }

    private static void AppendJobHeader(
        StringBuilder sb,
        string jobName,
        string displayName,
        string? agentPoolName,
        string? dependsOn)
    {
        sb.AppendLine($"    - job: {jobName}");
        sb.AppendLine($"      displayName: '{displayName}'");
        if (!string.IsNullOrEmpty(dependsOn))
        {
            sb.AppendLine($"      dependsOn: {dependsOn}");
        }

        PipelineGenerationEngine.AppendPool(sb, agentPoolName, indent: "      ");
        sb.AppendLine("      steps:");
    }

    private static void GenerateConfigureStep(StringBuilder sb)
    {
        sb.AppendLine($"{StepIndent}# ── Configure Azure DevOps CLI ─────────────────────────────────────────");
        sb.AppendLine($"{StepIndent}- powershell: |");
        sb.AppendLine($"{StepBodyIndent}$ErrorActionPreference = 'Stop'");
        sb.AppendLine($"{StepBodyIndent}$null = az config set extension.use_dynamic_install=yes_without_prompt");
        sb.AppendLine($"{StepBodyIndent}$null = az config set extension.dynamic_install_allow_preview=false");
        sb.AppendLine($"{StepBodyIndent}$null = az extension show --name azure-devops 2>$null");
        sb.AppendLine($"{StepBodyIndent}if ($LASTEXITCODE -ne 0) {{");
        sb.AppendLine($"{StepBodyIndent}  $null = az extension add --name azure-devops --yes");
        sb.AppendLine($"{StepBodyIndent}}}");
        sb.AppendLine($"{StepBodyIndent}$null = az devops configure --defaults organization=\"$(organizationUrl)\" project=\"$(projectName)\"");
        sb.AppendLine($"{StepPropertyIndent}displayName: 'Configure Azure DevOps CLI'");
        sb.AppendLine($"{StepPropertyIndent}env:");
        sb.AppendLine($"{StepBodyIndent}AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
        sb.AppendLine($"{StepBodyIndent}SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
        sb.AppendLine();
    }

    private static void GeneratePipelineCreationSteps(StringBuilder sb, BootstrapGenerationRequest request)
    {
        if (request.Pipelines.Count == 0)
            return;

        sb.AppendLine("  # ── Create pipeline definitions ─────────────────────────────────────────");

        foreach (var pipeline in request.Pipelines)
        {
            var sanitizedName = EscapeSingleQuotes(pipeline.Name);
            var sanitizedPath = EscapeSingleQuotes(pipeline.YamlPath);
            var sanitizedFolder = EscapeSingleQuotes(pipeline.Folder);

            sb.AppendLine($"{StepIndent}- powershell: |");
            sb.AppendLine($"{StepBodyIndent}$ErrorActionPreference = 'Stop'");
            sb.AppendLine($"{StepBodyIndent}$existing = az pipelines list --folder-path '{sanitizedFolder}' --query \"[?name=='{sanitizedName}'].id | [0]\" -o tsv --detect false");
            sb.AppendLine($"{StepBodyIndent}if ([string]::IsNullOrWhiteSpace($existing)) {{");
            sb.AppendLine($"{StepBodyIndent}  $previousErrorActionPreference = $ErrorActionPreference");
            sb.AppendLine($"{StepBodyIndent}  try {{");
            sb.AppendLine($"{StepBodyIndent}    $ErrorActionPreference = 'Continue'");
            sb.AppendLine($"{StepBodyIndent}    $createOutput = @(az pipelines create --name '{sanitizedName}' --repository \"$(repositoryName)\" --repository-type tfsgit --branch \"$(defaultBranch)\" --yml-path '{sanitizedPath}' --folder-path '{sanitizedFolder}' --skip-first-run true --query 'id' -o tsv --only-show-errors --detect false 2>&1)");
            sb.AppendLine($"{StepBodyIndent}    $createExitCode = $LASTEXITCODE");
            sb.AppendLine($"{StepBodyIndent}  }}");
            sb.AppendLine($"{StepBodyIndent}  finally {{");
            sb.AppendLine($"{StepBodyIndent}    $ErrorActionPreference = $previousErrorActionPreference");
            sb.AppendLine($"{StepBodyIndent}  }}");
            sb.AppendLine($"{StepBodyIndent}  $createdId = (($createOutput | ForEach-Object {{ $_.ToString().Trim() }} | Where-Object {{ $_ -match '^\\d+$' }} | Select-Object -Last 1) | Out-String).Trim()");
            sb.AppendLine($"{StepBodyIndent}  if ($createExitCode -ne 0 -or [string]::IsNullOrWhiteSpace($createdId)) {{");
            sb.AppendLine($"{StepBodyIndent}    $details = ($createOutput | Out-String).Trim()");
            sb.AppendLine($"{StepBodyIndent}    if ([string]::IsNullOrWhiteSpace($details)) {{");
            sb.AppendLine($"{StepBodyIndent}      $details = 'No output returned by Azure DevOps CLI.'");
            sb.AppendLine($"{StepBodyIndent}    }}");
            sb.AppendLine($"{StepBodyIndent}    throw 'Failed to create pipeline {sanitizedName}. Ensure the Azure DevOps identity used by System.AccessToken has the Create build pipeline permission on path {sanitizedFolder} and Use permission on the agent pool referenced by {sanitizedPath}. Azure DevOps CLI output: ' + $details");
            sb.AppendLine($"{StepBodyIndent}  }}");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Created pipeline: {sanitizedName} (ID: ' + $createdId + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}else {{");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Pipeline already exists: {sanitizedName} (ID: ' + $existing + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepPropertyIndent}displayName: 'Create Pipeline: {sanitizedName}'");
            sb.AppendLine($"{StepPropertyIndent}env:");
            sb.AppendLine($"{StepBodyIndent}AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
            sb.AppendLine($"{StepBodyIndent}SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
            sb.AppendLine();
        }
    }

    private static void GenerateEnvironmentCreationSteps(StringBuilder sb, BootstrapGenerationRequest request)
    {
        if (request.Environments.Count == 0)
            return;

        sb.AppendLine("  # ── Create Azure DevOps environments ───────────────────────────────────");

        foreach (var environment in request.Environments)
        {
            var sanitizedEnvironmentName = EscapeSingleQuotes(environment.Name);
            var sanitizedDescription = EscapeSingleQuotes(BuildEnvironmentDescription(environment));

            sb.AppendLine($"{StepIndent}- powershell: |");
            sb.AppendLine($"{StepBodyIndent}$ErrorActionPreference = 'Stop'");
            sb.AppendLine($"{StepBodyIndent}$encodedProjectName = [Uri]::EscapeDataString(\"$(projectName)\")");
            sb.AppendLine($"{StepBodyIndent}$headers = @{{ Authorization = \"Bearer $(System.AccessToken)\" }}");
            sb.AppendLine($"{StepBodyIndent}$environmentUri = \"$(organizationUrl)/$encodedProjectName/_apis/distributedtask/environments?api-version=7.1\"");
            sb.AppendLine($"{StepBodyIndent}$existingResponse = Invoke-RestMethod -Method Get -Uri $environmentUri -Headers $headers -ContentType 'application/json'");
            sb.AppendLine($"{StepBodyIndent}$existing = @($existingResponse.value | Where-Object {{ $_.name -eq '{sanitizedEnvironmentName}' }} | Select-Object -First 1)");
            sb.AppendLine($"{StepBodyIndent}if ($existing.Count -eq 0) {{");
            sb.AppendLine($"{StepBodyIndent}  $body = @{{");
            sb.AppendLine($"{StepBodyIndent}    name = '{sanitizedEnvironmentName}'");
            sb.AppendLine($"{StepBodyIndent}    description = '{sanitizedDescription}'");
            sb.AppendLine($"{StepBodyIndent}  }} | ConvertTo-Json");
            sb.AppendLine($"{StepBodyIndent}  $created = Invoke-RestMethod -Method Post -Uri $environmentUri -Headers $headers -Body $body -ContentType 'application/json'");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Created environment: {sanitizedEnvironmentName} (ID: ' + $created.id + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}else {{");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Environment already exists: {sanitizedEnvironmentName} (ID: ' + $existing[0].id + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");

            if (environment.RequiresApproval)
            {
                sb.AppendLine($"{StepBodyIndent}Write-Host 'InfraFlowSculptor marks this environment as approval-required. Add the Azure DevOps Approval check manually after bootstrap because approver identities are not stored in the app yet.'");
            }

            sb.AppendLine($"{StepPropertyIndent}displayName: 'Create Environment: {sanitizedEnvironmentName}'");
            sb.AppendLine($"{StepPropertyIndent}env:");
            sb.AppendLine($"{StepBodyIndent}SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
            sb.AppendLine();
        }
    }

    private static void GenerateVariableGroupCreationSteps(StringBuilder sb, BootstrapGenerationRequest request)
    {
        if (request.VariableGroups.Count == 0)
            return;

        sb.AppendLine("  # ── Create variable groups ──────────────────────────────────────────────");

        foreach (var group in request.VariableGroups)
        {
            var sanitizedGroupName = EscapeSingleQuotes(group.GroupName);

            var plainVars = group.Variables.Where(v => !v.IsSecret).ToList();
            var variableTokens = plainVars.Count > 0
                ? plainVars.Select(v => $"{v.Name}={v.Value}").ToList()
                : ["PLACEHOLDER=bootstrap"];
            var secretVars = group.Variables.Where(v => v.IsSecret).ToList();

            sb.AppendLine($"{StepIndent}- powershell: |");
            sb.AppendLine($"{StepBodyIndent}$ErrorActionPreference = 'Stop'");
            sb.AppendLine($"{StepBodyIndent}$existingId = az pipelines variable-group list --query \"[?name=='{sanitizedGroupName}'].id | [0]\" -o tsv --detect false 2>$null");
            sb.AppendLine($"{StepBodyIndent}$groupCreated = $false");
            sb.AppendLine($"{StepBodyIndent}if ([string]::IsNullOrWhiteSpace($existingId)) {{");
            sb.Append($"{StepBodyIndent}  $null = az pipelines variable-group create --name '{sanitizedGroupName}' --variables");
            foreach (var token in variableTokens)
            {
                sb.Append($" '{EscapeSingleQuotes(token)}'");
            }
            sb.AppendLine(" --detect false");
            sb.AppendLine($"{StepBodyIndent}  $vgId = az pipelines variable-group list --query \"[?name=='{sanitizedGroupName}'].id | [0]\" -o tsv --detect false");
            sb.AppendLine($"{StepBodyIndent}  if ([string]::IsNullOrWhiteSpace($vgId)) {{");
            sb.AppendLine($"{StepBodyIndent}    throw 'Unable to resolve variable group id after creation: {sanitizedGroupName}'");
            sb.AppendLine($"{StepBodyIndent}  }}");
            sb.AppendLine($"{StepBodyIndent}  $groupCreated = $true");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}else {{");
            sb.AppendLine($"{StepBodyIndent}  $vgId = $existingId");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}$existingVariablesJson = az pipelines variable-group variable list --group-id $vgId -o json --detect false");
            sb.AppendLine($"{StepBodyIndent}$existingVariableNames = @()");
            sb.AppendLine($"{StepBodyIndent}if (-not [string]::IsNullOrWhiteSpace($existingVariablesJson) -and $existingVariablesJson -ne '{{}}') {{");
            sb.AppendLine($"{StepBodyIndent}  $existingVariables = $existingVariablesJson | ConvertFrom-Json");
            sb.AppendLine($"{StepBodyIndent}  $existingVariableNames = @($existingVariables.PSObject.Properties.Name)");
            sb.AppendLine($"{StepBodyIndent}}}");

            foreach (var plainVar in plainVars)
            {
                var sanitizedVarName = EscapeSingleQuotes(plainVar.Name);
                var sanitizedVarValue = EscapeSingleQuotes(plainVar.Value);
                sb.AppendLine($"{StepBodyIndent}if (-not ($existingVariableNames -contains '{sanitizedVarName}')) {{");
                sb.AppendLine($"{StepBodyIndent}  $null = az pipelines variable-group variable create --group-id $vgId --name '{sanitizedVarName}' --value '{sanitizedVarValue}' --detect false");
                sb.AppendLine($"{StepBodyIndent}  $existingVariableNames += '{sanitizedVarName}'");
                sb.AppendLine($"{StepBodyIndent}}}");
            }

            foreach (var secretVar in secretVars)
            {
                var sanitizedVarName = EscapeSingleQuotes(secretVar.Name);
                sb.AppendLine($"{StepBodyIndent}if (-not ($existingVariableNames -contains '{sanitizedVarName}')) {{");
                sb.AppendLine($"{StepBodyIndent}  $null = az pipelines variable-group variable create --group-id $vgId --name '{sanitizedVarName}' --value ' ' --secret true --detect false");
                sb.AppendLine($"{StepBodyIndent}  $existingVariableNames += '{sanitizedVarName}'");
                sb.AppendLine($"{StepBodyIndent}}}");
            }

            sb.AppendLine($"{StepBodyIndent}if (($existingVariableNames -contains 'PLACEHOLDER') -and $existingVariableNames.Count -gt 1) {{");
            sb.AppendLine($"{StepBodyIndent}  $null = az pipelines variable-group variable delete --group-id $vgId --name PLACEHOLDER --yes --detect false");
            sb.AppendLine($"{StepBodyIndent}  $existingVariableNames = @($existingVariableNames | Where-Object {{ $_ -ne 'PLACEHOLDER' }})");
            sb.AppendLine($"{StepBodyIndent}}}");

            sb.AppendLine($"{StepBodyIndent}if ($groupCreated) {{");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Created variable group: {sanitizedGroupName} (ID: ' + $vgId + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}else {{");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Variable group already exists: {sanitizedGroupName} (ID: ' + $vgId + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}Write-Host ('Ensured variables for group {sanitizedGroupName}: ' + $existingVariableNames.Count)");
            sb.AppendLine($"{StepPropertyIndent}displayName: 'Create Variable Group: {sanitizedGroupName}'");
            sb.AppendLine($"{StepPropertyIndent}env:");
            sb.AppendLine($"{StepBodyIndent}AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
            sb.AppendLine($"{StepBodyIndent}SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
            sb.AppendLine();
        }
    }

    private static string BuildEnvironmentDescription(BootstrapEnvironmentDefinition environment)
    {
        var approvalText = environment.RequiresApproval ? "yes" : "no";
        return $"Generated from InfraFlowSculptor environment '{environment.DisplayName}'. Approval required in app: {approvalText}.";
    }

    private static void GenerateValidateSharedResourcesSteps(StringBuilder sb, BootstrapGenerationRequest request)
    {
        sb.AppendLine("  # ── Validate shared project resources owned by the infra bootstrap ──────");
        sb.AppendLine($"{StepIndent}- powershell: |");
        sb.AppendLine($"{StepBodyIndent}$ErrorActionPreference = 'Stop'");
        sb.AppendLine($"{StepBodyIndent}$missing = @()");

        if (request.Environments.Count > 0)
        {
            sb.AppendLine($"{StepBodyIndent}$encodedProjectName = [Uri]::EscapeDataString(\"$(projectName)\")");
            sb.AppendLine($"{StepBodyIndent}$headers = @{{ Authorization = \"Bearer $(System.AccessToken)\" }}");
            sb.AppendLine($"{StepBodyIndent}$environmentUri = \"$(organizationUrl)/$encodedProjectName/_apis/distributedtask/environments?api-version=7.1\"");
            sb.AppendLine($"{StepBodyIndent}$environmentsResponse = Invoke-RestMethod -Method Get -Uri $environmentUri -Headers $headers -ContentType 'application/json'");
            sb.AppendLine($"{StepBodyIndent}$existingEnvironmentNames = @()");
            sb.AppendLine($"{StepBodyIndent}if ($environmentsResponse.value) {{ $existingEnvironmentNames = @($environmentsResponse.value | ForEach-Object {{ $_.name }}) }}");

            foreach (var environment in request.Environments)
            {
                var sanitizedEnvironmentName = EscapeSingleQuotes(environment.Name);
                sb.AppendLine($"{StepBodyIndent}if (-not ($existingEnvironmentNames -contains '{sanitizedEnvironmentName}')) {{ $missing += 'environment:{sanitizedEnvironmentName}' }}");
            }
        }

        if (request.VariableGroups.Count > 0)
        {
            sb.AppendLine($"{StepBodyIndent}$existingGroupsJson = az pipelines variable-group list -o json --detect false");
            sb.AppendLine($"{StepBodyIndent}$existingGroupNames = @()");
            sb.AppendLine($"{StepBodyIndent}if (-not [string]::IsNullOrWhiteSpace($existingGroupsJson)) {{");
            sb.AppendLine($"{StepBodyIndent}  $existingGroups = $existingGroupsJson | ConvertFrom-Json");
            sb.AppendLine($"{StepBodyIndent}  if ($existingGroups) {{ $existingGroupNames = @($existingGroups | ForEach-Object {{ $_.name }}) }}");
            sb.AppendLine($"{StepBodyIndent}}}");

            foreach (var group in request.VariableGroups)
            {
                var sanitizedGroupName = EscapeSingleQuotes(group.GroupName);
                sb.AppendLine($"{StepBodyIndent}if (-not ($existingGroupNames -contains '{sanitizedGroupName}')) {{ $missing += 'variableGroup:{sanitizedGroupName}' }}");
            }
        }

        sb.AppendLine($"{StepBodyIndent}if ($missing.Count -gt 0) {{");
        sb.AppendLine($"{StepBodyIndent}  Write-Host '##[error]Missing shared project resources: ' ($missing -join ', ')");
        sb.AppendLine($"{StepBodyIndent}  throw 'Shared project resources are missing. Run the infrastructure bootstrap pipeline first to provision the listed environments and variable groups.'");
        sb.AppendLine($"{StepBodyIndent}}}");
        sb.AppendLine($"{StepBodyIndent}Write-Host 'Shared project resources validated.'");
        sb.AppendLine($"{StepPropertyIndent}displayName: 'Validate shared project resources'");
        sb.AppendLine($"{StepPropertyIndent}env:");
        sb.AppendLine($"{StepBodyIndent}AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
        sb.AppendLine($"{StepBodyIndent}SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
        sb.AppendLine();
    }

    private static string EscapeSingleQuotes(string value) =>
        value.Replace("'", "''");
}
