using System.Text;
using InfraFlowSculptor.PipelineGeneration.Models;

namespace InfraFlowSculptor.PipelineGeneration;

/// <summary>
/// Generates a self-contained <c>bootstrap.pipeline.yml</c> for Azure DevOps.
/// When executed once in Azure DevOps, the bootstrap pipeline provisions all pipeline definitions,
/// variable groups (with empty secret values), and variable group authorizations using <c>az devops</c> CLI.
/// All scripts are idempotent — re-running the pipeline will skip already-existing resources.
/// </summary>
public sealed class BootstrapPipelineGenerationEngine
{
    private const string BootstrapFileName = "bootstrap.pipeline.yml";

    /// <summary>
    /// Generates the bootstrap pipeline YAML file from the provided request.
    /// </summary>
    /// <param name="request">The bootstrap generation request containing pipelines, variable groups, and project metadata.</param>
    /// <returns>
    /// A <see cref="PipelineGenerationResult"/> containing a single file: <c>bootstrap.pipeline.yml</c>.
    /// </returns>
    public PipelineGenerationResult Generate(BootstrapGenerationRequest request)
    {
        var sb = new StringBuilder();

        GenerateHeader(sb, request);
        GenerateConfigureStep(sb, request);
        GenerateGetRepoIdStep(sb, request);
        GeneratePipelineCreationSteps(sb, request);
        GenerateVariableGroupCreationSteps(sb, request);
        GenerateAuthorizationSteps(sb, request);

        var files = new Dictionary<string, string>
        {
            [BootstrapFileName] = sb.ToString(),
        };

        return new PipelineGenerationResult { TemplateFiles = files };
    }

    private static void GenerateHeader(StringBuilder sb, BootstrapGenerationRequest request)
    {
        sb.AppendLine("# Bootstrap Pipeline — generated by InfraFlowSculptor");
        sb.AppendLine("# Run this pipeline ONCE in Azure DevOps to provision pipeline definitions,");
        sb.AppendLine("# variable groups, and their authorizations.");
        sb.AppendLine("# All scripts are idempotent — re-running skips already-existing resources.");
        sb.AppendLine("#");
        sb.AppendLine("# Prerequisites:");
        sb.AppendLine("#   - The pipeline/job must expose $(System.AccessToken) to scripts");
        sb.AppendLine("#   - The build service identity must be allowed to manage pipelines and variable groups");
        sb.AppendLine("#   - Service connections configured per environment in Azure DevOps");
        sb.AppendLine("#   - Azure CLI with azure-devops extension available on agent");
        sb.AppendLine();
        sb.AppendLine("trigger: none");
        sb.AppendLine();

        PipelineGenerationEngine.AppendPool(sb, request.AgentPoolName, indent: string.Empty);
        sb.AppendLine();

        sb.AppendLine("variables:");
        sb.AppendLine($"  organizationUrl: 'https://dev.azure.com/{EscapeSingleQuotes(request.OrganizationName)}'");
        sb.AppendLine($"  projectName: '{EscapeSingleQuotes(request.ProjectName)}'");
        sb.AppendLine($"  repositoryName: '{EscapeSingleQuotes(request.RepositoryName)}'");
        sb.AppendLine($"  defaultBranch: '{EscapeSingleQuotes(request.DefaultBranch)}'");
        sb.AppendLine();
        sb.AppendLine("steps:");
    }

    private static void GenerateConfigureStep(StringBuilder sb, BootstrapGenerationRequest request)
    {
        sb.AppendLine("  # ── Step 1: Configure Azure DevOps CLI ──────────────────────────────────");
        sb.AppendLine("  - powershell: |");
        sb.AppendLine("      $ErrorActionPreference = 'Stop'");
        sb.AppendLine("      $null = az config set extension.use_dynamic_install=yes_without_prompt");
        sb.AppendLine("      $null = az config set extension.dynamic_install_allow_preview=false");
        sb.AppendLine("      $null = az extension show --name azure-devops 2>$null");
        sb.AppendLine("      if ($LASTEXITCODE -ne 0) {");
        sb.AppendLine("        $null = az extension add --name azure-devops --yes");
        sb.AppendLine("      }");
        sb.AppendLine("      $null = az devops configure --defaults organization=\"$(organizationUrl)\" project=\"$(projectName)\" --detect false");
        sb.AppendLine("    displayName: 'Configure Azure DevOps CLI'");
        sb.AppendLine("    env:");
        sb.AppendLine("      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
        sb.AppendLine("      SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
        sb.AppendLine();
    }

    private static void GenerateGetRepoIdStep(StringBuilder sb, BootstrapGenerationRequest request)
    {
        sb.AppendLine("  # ── Step 2: Resolve repository ID ───────────────────────────────────────");
        sb.AppendLine("  - powershell: |");
        sb.AppendLine("      $ErrorActionPreference = 'Stop'");
        sb.AppendLine("      $repoId = az repos show --repository \"$(repositoryName)\" --query \"id\" -o tsv --detect false");
        sb.AppendLine("      if ([string]::IsNullOrWhiteSpace($repoId)) {");
        sb.AppendLine("        throw 'Unable to resolve the Azure DevOps repository identifier.'");
        sb.AppendLine("      }");
        sb.AppendLine("      Write-Host \"##vso[task.setvariable variable=repoId]$repoId\"");
        sb.AppendLine("      Write-Host ('Repository ID: ' + $repoId)");
        sb.AppendLine("    displayName: 'Resolve Repository ID'");
        sb.AppendLine("    env:");
        sb.AppendLine("      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
        sb.AppendLine("      SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
        sb.AppendLine();
    }

    private static void GeneratePipelineCreationSteps(StringBuilder sb, BootstrapGenerationRequest request)
    {
        if (request.Pipelines.Count == 0)
            return;

        sb.AppendLine("  # ── Step 3: Create pipeline definitions ─────────────────────────────────");

        foreach (var pipeline in request.Pipelines)
        {
            var sanitizedName = EscapeSingleQuotes(pipeline.Name);
            var sanitizedPath = EscapeSingleQuotes(pipeline.YamlPath);
            var sanitizedFolder = EscapeSingleQuotes(pipeline.Folder);

            sb.AppendLine($"  - powershell: |");
            sb.AppendLine("      $ErrorActionPreference = 'Stop'");
            sb.AppendLine($"      $existing = az pipelines show --name '{sanitizedName}' --folder-path '{sanitizedFolder}' --query 'id' -o tsv --detect false 2>$null");
            sb.AppendLine("      if ([string]::IsNullOrWhiteSpace($existing)) {");
            sb.AppendLine($"        $null = az pipelines create --name '{sanitizedName}' --repository \"$(repositoryName)\" --repository-type tfsgit --branch \"$(defaultBranch)\" --yml-path '{sanitizedPath}' --folder-path '{sanitizedFolder}' --skip-first-run true --detect false");
            sb.AppendLine($"        Write-Host 'Created pipeline: {sanitizedName}'");
            sb.AppendLine("      }");
            sb.AppendLine("      else {");
            sb.AppendLine($"        Write-Host ('Pipeline already exists: {sanitizedName} (ID: ' + $existing + ')')");
            sb.AppendLine("      }");
            sb.AppendLine($"    displayName: 'Create Pipeline: {sanitizedName}'");
            sb.AppendLine($"    env:");
            sb.AppendLine($"      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
            sb.AppendLine($"      SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
            sb.AppendLine();
        }
    }

    private static void GenerateVariableGroupCreationSteps(StringBuilder sb, BootstrapGenerationRequest request)
    {
        if (request.VariableGroups.Count == 0)
            return;

        sb.AppendLine("  # ── Step 4: Create variable groups ──────────────────────────────────────");

        foreach (var group in request.VariableGroups)
        {
            var sanitizedGroupName = EscapeSingleQuotes(group.GroupName);

            var plainVars = group.Variables.Where(v => !v.IsSecret).ToList();
            var variableTokens = plainVars.Count > 0
                ? plainVars.Select(v => $"{v.Name}={v.Value}").ToList()
                : ["PLACEHOLDER=bootstrap"];

            sb.AppendLine($"  - powershell: |");
            sb.AppendLine("      $ErrorActionPreference = 'Stop'");
            sb.AppendLine($"      $existingId = az pipelines variable-group list --query \"[?name=='{sanitizedGroupName}'].id | [0]\" -o tsv --detect false 2>$null");
            sb.AppendLine("      if ([string]::IsNullOrWhiteSpace($existingId)) {");
            sb.Append($"        $null = az pipelines variable-group create --name '{sanitizedGroupName}' --variables");
            foreach (var token in variableTokens)
            {
                sb.Append($" '{EscapeSingleQuotes(token)}'");
            }
            sb.AppendLine(" --detect false");
            sb.AppendLine($"        $vgId = az pipelines variable-group list --query \"[?name=='{sanitizedGroupName}'].id | [0]\" -o tsv --detect false");
            sb.AppendLine("        if ([string]::IsNullOrWhiteSpace($vgId)) {");
            sb.AppendLine($"          throw 'Unable to resolve variable group id after creation: {sanitizedGroupName}'");
            sb.AppendLine("        }");

            if (plainVars.Count == 0)
            {
                sb.AppendLine("        $null = az pipelines variable-group variable delete --group-id $vgId --name PLACEHOLDER --yes --detect false 2>$null");
            }

            var secretVars = group.Variables.Where(v => v.IsSecret).ToList();
            if (secretVars.Count > 0)
            {
                foreach (var secretVar in secretVars)
                {
                    var sanitizedVarName = EscapeSingleQuotes(secretVar.Name);
                    sb.AppendLine($"        $null = az pipelines variable-group variable create --group-id $vgId --name '{sanitizedVarName}' --value ' ' --secret true --detect false");
                }
            }

            sb.AppendLine($"        Write-Host 'Created variable group: {sanitizedGroupName}'");
            sb.AppendLine("      }");
            sb.AppendLine("      else {");
            sb.AppendLine($"        Write-Host ('Variable group already exists: {sanitizedGroupName} (ID: ' + $existingId + ')')");
            sb.AppendLine("      }");
            sb.AppendLine($"    displayName: 'Create Variable Group: {sanitizedGroupName}'");
            sb.AppendLine($"    env:");
            sb.AppendLine($"      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
            sb.AppendLine($"      SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
            sb.AppendLine();
        }
    }

    private static void GenerateAuthorizationSteps(StringBuilder sb, BootstrapGenerationRequest request)
    {
        if (request.VariableGroups.Count == 0 || request.Pipelines.Count == 0)
            return;

        sb.AppendLine("  # ── Step 5: Authorize variable groups on all pipelines ───────────────────");
        sb.AppendLine("  # Uses the Azure DevOps REST API directly (az CLI does not expose this endpoint).");
        sb.AppendLine("  - powershell: |");
        sb.AppendLine("      $ErrorActionPreference = 'Stop'");
        sb.AppendLine("      $baseUrl = \"$(organizationUrl)/$(projectName)/_apis/pipelines/pipelinepermissions\"");
        sb.AppendLine("      $headers = @{ Authorization = \"Bearer $(System.AccessToken)\" }");
        sb.AppendLine("      $body = '{\"allPipelines\":{\"authorized\":true}}'");
        sb.AppendLine();

        foreach (var group in request.VariableGroups)
        {
            var sanitizedGroupName = EscapeSingleQuotes(group.GroupName);
            sb.AppendLine($"      # Authorize '{sanitizedGroupName}' on all pipelines");
            sb.AppendLine($"      $vgId = az pipelines variable-group list --query \"[?name=='{sanitizedGroupName}'].id | [0]\" -o tsv --detect false");
            sb.AppendLine("      if (-not [string]::IsNullOrWhiteSpace($vgId)) {");
            sb.AppendLine("        $uri = \"$baseUrl/variablegroup/$vgId?api-version=7.1\"");
            sb.AppendLine("        $null = Invoke-RestMethod -Method Patch -Uri $uri -Headers $headers -ContentType 'application/json' -Body $body");
            sb.AppendLine($"        Write-Host ('Authorized variable group ''{sanitizedGroupName}'' (ID: ' + $vgId + ') on all pipelines')");
            sb.AppendLine("      }");
            sb.AppendLine("      else {");
            sb.AppendLine($"        Write-Host 'WARNING: Variable group ''{sanitizedGroupName}'' not found — skipping authorization'");
            sb.AppendLine("      }");
            sb.AppendLine();
        }

        sb.AppendLine("    displayName: 'Authorize Variable Groups on All Pipelines'");
        sb.AppendLine("    env:");
        sb.AppendLine("      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
        sb.AppendLine("      SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
    }

    private static string EscapeSingleQuotes(string value) =>
        value.Replace("'", "''");
}
