using System.Text;
using InfraFlowSculptor.PipelineGeneration.Models;

namespace InfraFlowSculptor.PipelineGeneration;

/// <summary>
/// Generates a self-contained <c>bootstrap.pipeline.yml</c> for Azure DevOps.
/// When executed once in Azure DevOps, the bootstrap pipeline provisions all pipeline definitions,
/// environments, and variable groups (with empty secret values) using Azure DevOps CLI and REST APIs.
/// All scripts are idempotent — re-running the pipeline will skip already-existing resources.
/// </summary>
public sealed class BootstrapPipelineGenerationEngine
{
    private const string BootstrapFileName = "bootstrap.pipeline.yml";
    private const string StepIndent = "        ";
    private const string StepBodyIndent = "            ";
    private const string StepPropertyIndent = "          ";

    /// <summary>
    /// Generates the bootstrap pipeline YAML file from the provided request.
    /// </summary>
    /// <param name="request">The bootstrap generation request containing pipelines, variable groups, and project metadata.</param>
    /// <returns>
    /// A <see cref="PipelineGenerationResult"/> containing a single file: <c>bootstrap.pipeline.yml</c>.
    /// </returns>
    public PipelineGenerationResult Generate(BootstrapGenerationRequest request)
    {
        var sb = new StringBuilder();

        GenerateHeader(sb, request);
        GenerateConfigureStep(sb, request);
        GenerateGetRepoIdStep(sb, request);
        GeneratePipelineCreationSteps(sb, request);
        GenerateEnvironmentCreationSteps(sb, request);
        GenerateVariableGroupCreationSteps(sb, request);

        var files = new Dictionary<string, string>
        {
            [BootstrapFileName] = sb.ToString(),
        };

        return new PipelineGenerationResult { TemplateFiles = files };
    }

    private static void GenerateHeader(StringBuilder sb, BootstrapGenerationRequest request)
    {
        sb.AppendLine("# Bootstrap Pipeline — generated by InfraFlowSculptor");
        sb.AppendLine("# Run this pipeline ONCE in Azure DevOps to provision pipeline definitions,");
        sb.AppendLine("# environments, and variable groups.");
        sb.AppendLine("# All scripts are idempotent — re-running skips already-existing resources.");
        sb.AppendLine("#");
        sb.AppendLine("# Prerequisites:");
        sb.AppendLine("#   - The pipeline/job must expose $(System.AccessToken) to scripts");
        sb.AppendLine("#   - The build service identity must be allowed to manage pipelines, environments, and variable groups");
        sb.AppendLine("#   - Service connections configured per environment in Azure DevOps");
        sb.AppendLine("#   - Azure CLI with azure-devops extension available on agent");
        sb.AppendLine("#   - Approval-required environments are created automatically, but approver identities must still be configured manually in Azure DevOps");
        sb.AppendLine();
        sb.AppendLine("trigger: none");
        sb.AppendLine();

        sb.AppendLine("name: bootstrap-$(Date:yyyyMMdd)$(Rev:.r)");
        sb.AppendLine();

        sb.AppendLine("variables:");
        sb.AppendLine($"  organizationUrl: 'https://dev.azure.com/{EscapeSingleQuotes(request.OrganizationName)}'");
        sb.AppendLine($"  projectName: '{EscapeSingleQuotes(request.ProjectName)}'");
        sb.AppendLine($"  repositoryName: '{EscapeSingleQuotes(request.RepositoryName)}'");
        sb.AppendLine($"  defaultBranch: '{EscapeSingleQuotes(request.DefaultBranch)}'");
        sb.AppendLine();
        sb.AppendLine("stages:");
        sb.AppendLine("- stage: BootstrapAzureDevOps");
        sb.AppendLine("  displayName: 'Bootstrap Azure DevOps'");
        sb.AppendLine("  jobs:");
        sb.AppendLine("    - job: ProvisionBootstrapAssets");
        sb.AppendLine("      displayName: 'Provision Pipelines and Variable Groups'");
        PipelineGenerationEngine.AppendPool(sb, request.AgentPoolName, indent: "      ");
        sb.AppendLine("      steps:");
    }

    private static void GenerateConfigureStep(StringBuilder sb, BootstrapGenerationRequest request)
    {
        sb.AppendLine($"{StepIndent}# ── Step 1: Configure Azure DevOps CLI ──────────────────────────────────");
        sb.AppendLine($"{StepIndent}- powershell: |");
        sb.AppendLine($"{StepBodyIndent}$ErrorActionPreference = 'Stop'");
        sb.AppendLine($"{StepBodyIndent}$null = az config set extension.use_dynamic_install=yes_without_prompt");
        sb.AppendLine($"{StepBodyIndent}$null = az config set extension.dynamic_install_allow_preview=false");
        sb.AppendLine($"{StepBodyIndent}$null = az extension show --name azure-devops 2>$null");
        sb.AppendLine($"{StepBodyIndent}if ($LASTEXITCODE -ne 0) {{");
        sb.AppendLine($"{StepBodyIndent}  $null = az extension add --name azure-devops --yes");
        sb.AppendLine($"{StepBodyIndent}}}");
        sb.AppendLine($"{StepBodyIndent}$null = az devops configure --defaults organization=\"$(organizationUrl)\" project=\"$(projectName)\"");
        sb.AppendLine($"{StepPropertyIndent}displayName: 'Configure Azure DevOps CLI'");
        sb.AppendLine($"{StepPropertyIndent}env:");
        sb.AppendLine($"{StepBodyIndent}AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
        sb.AppendLine($"{StepBodyIndent}SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
        sb.AppendLine();
    }

    private static void GenerateGetRepoIdStep(StringBuilder sb, BootstrapGenerationRequest request)
    {
        sb.AppendLine($"{StepIndent}# ── Step 2: Resolve repository ID ───────────────────────────────────────");
        sb.AppendLine($"{StepIndent}- powershell: |");
        sb.AppendLine($"{StepBodyIndent}$ErrorActionPreference = 'Stop'");
        sb.AppendLine($"{StepBodyIndent}$repoId = az repos show --repository \"$(repositoryName)\" --query \"id\" -o tsv --detect false");
        sb.AppendLine($"{StepBodyIndent}if ([string]::IsNullOrWhiteSpace($repoId)) {{");
        sb.AppendLine($"{StepBodyIndent}  throw 'Unable to resolve the Azure DevOps repository identifier.'");
        sb.AppendLine($"{StepBodyIndent}}}");
        sb.AppendLine($"{StepBodyIndent}Write-Host \"##vso[task.setvariable variable=repoId]$repoId\"");
        sb.AppendLine($"{StepBodyIndent}Write-Host ('Repository ID: ' + $repoId)");
        sb.AppendLine($"{StepPropertyIndent}displayName: 'Resolve Repository ID'");
        sb.AppendLine($"{StepPropertyIndent}env:");
        sb.AppendLine($"{StepBodyIndent}AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
        sb.AppendLine($"{StepBodyIndent}SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
        sb.AppendLine();
    }

    private static void GeneratePipelineCreationSteps(StringBuilder sb, BootstrapGenerationRequest request)
    {
        if (request.Pipelines.Count == 0)
            return;

        sb.AppendLine("  # ── Step 3: Create pipeline definitions ─────────────────────────────────");

        foreach (var pipeline in request.Pipelines)
        {
            var sanitizedName = EscapeSingleQuotes(pipeline.Name);
            var sanitizedPath = EscapeSingleQuotes(pipeline.YamlPath);
            var sanitizedFolder = EscapeSingleQuotes(pipeline.Folder);

            sb.AppendLine($"{StepIndent}- powershell: |");
            sb.AppendLine($"{StepBodyIndent}$ErrorActionPreference = 'Stop'");
            sb.AppendLine($"{StepBodyIndent}$existing = az pipelines list --folder-path '{sanitizedFolder}' --query \"[?name=='{sanitizedName}'].id | [0]\" -o tsv --detect false");
            sb.AppendLine($"{StepBodyIndent}if ([string]::IsNullOrWhiteSpace($existing)) {{");
            sb.AppendLine($"{StepBodyIndent}  $createdId = az pipelines create --name '{sanitizedName}' --repository \"$(repositoryName)\" --repository-type tfsgit --branch \"$(defaultBranch)\" --yml-path '{sanitizedPath}' --folder-path '{sanitizedFolder}' --skip-first-run true --query 'id' -o tsv --detect false");
            sb.AppendLine($"{StepBodyIndent}  if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($createdId)) {{");
            sb.AppendLine($"{StepBodyIndent}    throw 'Failed to create pipeline {sanitizedName}. Ensure the Azure DevOps identity used by System.AccessToken has the Create build pipeline permission on path {sanitizedFolder}.'");
            sb.AppendLine($"{StepBodyIndent}  }}");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Created pipeline: {sanitizedName} (ID: ' + $createdId + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}else {{");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Pipeline already exists: {sanitizedName} (ID: ' + $existing + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepPropertyIndent}displayName: 'Create Pipeline: {sanitizedName}'");
            sb.AppendLine($"{StepPropertyIndent}env:");
            sb.AppendLine($"{StepBodyIndent}AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
            sb.AppendLine($"{StepBodyIndent}SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
            sb.AppendLine();
        }
    }

    private static void GenerateEnvironmentCreationSteps(StringBuilder sb, BootstrapGenerationRequest request)
    {
        if (request.Environments.Count == 0)
            return;

        sb.AppendLine("  # ── Step 4: Create Azure DevOps environments ───────────────────────────");

        foreach (var environment in request.Environments)
        {
            var sanitizedEnvironmentName = EscapeSingleQuotes(environment.Name);
            var sanitizedDescription = EscapeSingleQuotes(BuildEnvironmentDescription(environment));

            sb.AppendLine($"{StepIndent}- powershell: |");
            sb.AppendLine($"{StepBodyIndent}$ErrorActionPreference = 'Stop'");
            sb.AppendLine($"{StepBodyIndent}$encodedProjectName = [Uri]::EscapeDataString(\"$(projectName)\")");
            sb.AppendLine($"{StepBodyIndent}$headers = @{{ Authorization = \"Bearer $(System.AccessToken)\" }}");
            sb.AppendLine($"{StepBodyIndent}$environmentUri = \"$(organizationUrl)/$encodedProjectName/_apis/distributedtask/environments?api-version=7.1\"");
            sb.AppendLine($"{StepBodyIndent}$existingResponse = Invoke-RestMethod -Method Get -Uri $environmentUri -Headers $headers -ContentType 'application/json'");
            sb.AppendLine($"{StepBodyIndent}$existing = @($existingResponse.value | Where-Object {{ $_.name -eq '{sanitizedEnvironmentName}' }} | Select-Object -First 1)");
            sb.AppendLine($"{StepBodyIndent}if ($existing.Count -eq 0) {{");
            sb.AppendLine($"{StepBodyIndent}  $body = @{{");
            sb.AppendLine($"{StepBodyIndent}    name = '{sanitizedEnvironmentName}'");
            sb.AppendLine($"{StepBodyIndent}    description = '{sanitizedDescription}'");
            sb.AppendLine($"{StepBodyIndent}  }} | ConvertTo-Json");
            sb.AppendLine($"{StepBodyIndent}  $created = Invoke-RestMethod -Method Post -Uri $environmentUri -Headers $headers -Body $body -ContentType 'application/json'");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Created environment: {sanitizedEnvironmentName} (ID: ' + $created.id + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}else {{");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Environment already exists: {sanitizedEnvironmentName} (ID: ' + $existing[0].id + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");

            if (environment.RequiresApproval)
            {
                sb.AppendLine($"{StepBodyIndent}Write-Host 'InfraFlowSculptor marks this environment as approval-required. Add the Azure DevOps Approval check manually after bootstrap because approver identities are not stored in the app yet.'");
            }

            sb.AppendLine($"{StepPropertyIndent}displayName: 'Create Environment: {sanitizedEnvironmentName}'");
            sb.AppendLine($"{StepPropertyIndent}env:");
            sb.AppendLine($"{StepBodyIndent}SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
            sb.AppendLine();
        }
    }

    private static void GenerateVariableGroupCreationSteps(StringBuilder sb, BootstrapGenerationRequest request)
    {
        if (request.VariableGroups.Count == 0)
            return;

        sb.AppendLine("  # ── Step 5: Create variable groups ──────────────────────────────────────");

        foreach (var group in request.VariableGroups)
        {
            var sanitizedGroupName = EscapeSingleQuotes(group.GroupName);

            var plainVars = group.Variables.Where(v => !v.IsSecret).ToList();
            var variableTokens = plainVars.Count > 0
                ? plainVars.Select(v => $"{v.Name}={v.Value}").ToList()
                : ["PLACEHOLDER=bootstrap"];
            var secretVars = group.Variables.Where(v => v.IsSecret).ToList();

            sb.AppendLine($"{StepIndent}- powershell: |");
            sb.AppendLine($"{StepBodyIndent}$ErrorActionPreference = 'Stop'");
            sb.AppendLine($"{StepBodyIndent}$existingId = az pipelines variable-group list --query \"[?name=='{sanitizedGroupName}'].id | [0]\" -o tsv --detect false 2>$null");
            sb.AppendLine($"{StepBodyIndent}$groupCreated = $false");
            sb.AppendLine($"{StepBodyIndent}if ([string]::IsNullOrWhiteSpace($existingId)) {{");
            sb.Append($"{StepBodyIndent}  $null = az pipelines variable-group create --name '{sanitizedGroupName}' --variables");
            foreach (var token in variableTokens)
            {
                sb.Append($" '{EscapeSingleQuotes(token)}'");
            }
            sb.AppendLine(" --detect false");
            sb.AppendLine($"{StepBodyIndent}  $vgId = az pipelines variable-group list --query \"[?name=='{sanitizedGroupName}'].id | [0]\" -o tsv --detect false");
            sb.AppendLine($"{StepBodyIndent}  if ([string]::IsNullOrWhiteSpace($vgId)) {{");
            sb.AppendLine($"{StepBodyIndent}    throw 'Unable to resolve variable group id after creation: {sanitizedGroupName}'");
            sb.AppendLine($"{StepBodyIndent}  }}");
            sb.AppendLine($"{StepBodyIndent}  $groupCreated = $true");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}else {{");
            sb.AppendLine($"{StepBodyIndent}  $vgId = $existingId");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}$existingVariablesJson = az pipelines variable-group variable list --group-id $vgId -o json --detect false");
            sb.AppendLine($"{StepBodyIndent}$existingVariableNames = @()");
            sb.AppendLine($"{StepBodyIndent}if (-not [string]::IsNullOrWhiteSpace($existingVariablesJson) -and $existingVariablesJson -ne '{{}}') {{");
            sb.AppendLine($"{StepBodyIndent}  $existingVariables = $existingVariablesJson | ConvertFrom-Json");
            sb.AppendLine($"{StepBodyIndent}  $existingVariableNames = @($existingVariables.PSObject.Properties.Name)");
            sb.AppendLine($"{StepBodyIndent}}}");

            foreach (var plainVar in plainVars)
            {
                var sanitizedVarName = EscapeSingleQuotes(plainVar.Name);
                var sanitizedVarValue = EscapeSingleQuotes(plainVar.Value);
                sb.AppendLine($"{StepBodyIndent}if (-not ($existingVariableNames -contains '{sanitizedVarName}')) {{");
                sb.AppendLine($"{StepBodyIndent}  $null = az pipelines variable-group variable create --group-id $vgId --name '{sanitizedVarName}' --value '{sanitizedVarValue}' --detect false");
                sb.AppendLine($"{StepBodyIndent}  $existingVariableNames += '{sanitizedVarName}'");
                sb.AppendLine($"{StepBodyIndent}}}");
            }

            foreach (var secretVar in secretVars)
            {
                var sanitizedVarName = EscapeSingleQuotes(secretVar.Name);
                sb.AppendLine($"{StepBodyIndent}if (-not ($existingVariableNames -contains '{sanitizedVarName}')) {{");
                sb.AppendLine($"{StepBodyIndent}  $null = az pipelines variable-group variable create --group-id $vgId --name '{sanitizedVarName}' --value ' ' --secret true --detect false");
                sb.AppendLine($"{StepBodyIndent}  $existingVariableNames += '{sanitizedVarName}'");
                sb.AppendLine($"{StepBodyIndent}}}");
            }

            sb.AppendLine($"{StepBodyIndent}if (($existingVariableNames -contains 'PLACEHOLDER') -and $existingVariableNames.Count -gt 1) {{");
            sb.AppendLine($"{StepBodyIndent}  $null = az pipelines variable-group variable delete --group-id $vgId --name PLACEHOLDER --yes --detect false");
            sb.AppendLine($"{StepBodyIndent}  $existingVariableNames = @($existingVariableNames | Where-Object {{ $_ -ne 'PLACEHOLDER' }})");
            sb.AppendLine($"{StepBodyIndent}}}");

            sb.AppendLine($"{StepBodyIndent}if ($groupCreated) {{");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Created variable group: {sanitizedGroupName} (ID: ' + $vgId + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}else {{");
            sb.AppendLine($"{StepBodyIndent}  Write-Host ('Variable group already exists: {sanitizedGroupName} (ID: ' + $vgId + ')')");
            sb.AppendLine($"{StepBodyIndent}}}");
            sb.AppendLine($"{StepBodyIndent}Write-Host ('Ensured variables for group {sanitizedGroupName}: ' + $existingVariableNames.Count)");
            sb.AppendLine($"{StepPropertyIndent}displayName: 'Create Variable Group: {sanitizedGroupName}'");
            sb.AppendLine($"{StepPropertyIndent}env:");
            sb.AppendLine($"{StepBodyIndent}AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)");
            sb.AppendLine($"{StepBodyIndent}SYSTEM_ACCESSTOKEN: $(System.AccessToken)");
            sb.AppendLine();
        }
    }

    private static string BuildEnvironmentDescription(BootstrapEnvironmentDefinition environment)
    {
        var approvalText = environment.RequiresApproval ? "yes" : "no";
        return $"Generated from InfraFlowSculptor environment '{environment.DisplayName}'. Approval required in app: {approvalText}.";
    }

    private static string EscapeSingleQuotes(string value) =>
        value.Replace("'", "''");
}
