using System.Text;
using InfraFlowSculptor.GenerationCore.Models;
using InfraFlowSculptor.PipelineGeneration.Models;

namespace InfraFlowSculptor.PipelineGeneration;

/// <summary>
/// Main engine for Azure DevOps pipeline YAML generation.
/// Generates CI and deploy pipelines matching the standard .azuredevops/ folder structure.
/// </summary>
public sealed class PipelineGenerationEngine
{
    /// <summary>
    /// Generates Azure DevOps pipeline YAML files from the given generation request.
    /// </summary>
    /// <param name="request">The shared generation request containing infrastructure configuration data.</param>
    /// <returns>The generated pipeline files.</returns>
    public PipelineGenerationResult Generate(GenerationRequest request)
    {
        var templateFiles = new Dictionary<string, string>();

        // Generate CI pipeline (entry point)
        var ciPipeline = GenerateCiPipeline(request);

        // Generate deploy job template
        templateFiles["jobs/deploy.job.yml"] = GenerateDeployJob(request);

        // Generate deploy step template
        templateFiles["steps/deploy-template.step.yml"] = GenerateDeployStep();

        // Generate common variables
        templateFiles["variables/common.variables.yml"] = GenerateCommonVariables(request);

        // Generate per-environment variables
        foreach (var env in request.Environments)
        {
            var envKey = env.ShortName.ToLowerInvariant();
            templateFiles[$"variables/{envKey}.variables.yml"] = GenerateEnvironmentVariables(env);
        }

        return new PipelineGenerationResult
        {
            MainPipelineYaml = ciPipeline,
            TemplateFiles = templateFiles,
        };
    }

    private static string GenerateCiPipeline(GenerationRequest request)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Azure DevOps CI Pipeline — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("trigger:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        sb.AppendLine("      - main");
        sb.AppendLine();
        sb.AppendLine("pool:");
        sb.AppendLine("  vmImage: 'ubuntu-latest'");
        sb.AppendLine();
        sb.AppendLine("variables:");
        sb.AppendLine("  - template: variables/common.variables.yml");
        sb.AppendLine();
        sb.AppendLine("stages:");

        // Build stage
        sb.AppendLine("  - stage: Build");
        sb.AppendLine("    displayName: 'Build & Publish Bicep Artifacts'");
        sb.AppendLine("    jobs:");
        sb.AppendLine("      - job: BuildBicep");
        sb.AppendLine("        displayName: 'Build Bicep'");
        sb.AppendLine("        steps:");
        sb.AppendLine("          - checkout: self");
        sb.AppendLine();
        sb.AppendLine("          - task: CopyFiles@2");
        sb.AppendLine("            displayName: 'Copy Bicep files'");
        sb.AppendLine("            inputs:");
        sb.AppendLine("              SourceFolder: '$(Build.SourcesDirectory)'");
        sb.AppendLine("              Contents: |");
        sb.AppendLine("                **/*.bicep");
        sb.AppendLine("                **/*.bicepparam");
        sb.AppendLine("                **/*.json");
        sb.AppendLine("              TargetFolder: '$(Build.ArtifactStagingDirectory)'");
        sb.AppendLine();
        sb.AppendLine("          - task: PublishBuildArtifacts@1");
        sb.AppendLine("            displayName: 'Publish Bicep Artifact'");
        sb.AppendLine("            inputs:");
        sb.AppendLine("              PathtoPublish: '$(Build.ArtifactStagingDirectory)'");
        sb.AppendLine("              ArtifactName: 'bicep-$(Build.BuildNumber)'");
        sb.AppendLine("              publishLocation: 'Container'");

        // Deploy stages per environment
        for (var i = 0; i < request.Environments.Count; i++)
        {
            var env = request.Environments[i];
            var envKey = env.ShortName.ToLowerInvariant();
            var envDisplayName = env.Name;
            var dependsOn = i == 0 ? "Build" : request.Environments[i - 1].ShortName;

            sb.AppendLine();
            sb.AppendLine($"  - stage: Deploy_{env.ShortName}");
            sb.AppendLine($"    displayName: 'Deploy {envDisplayName}'");
            sb.AppendLine($"    dependsOn: {dependsOn}");
            sb.AppendLine("    variables:");
            sb.AppendLine($"      - template: variables/{envKey}.variables.yml");
            sb.AppendLine("    jobs:");
            sb.AppendLine("      - template: jobs/deploy.job.yml");
            sb.AppendLine("        parameters:");
            sb.AppendLine($"          environmentName: '{envDisplayName}'");
            sb.AppendLine($"          azureResourceManagerConnection: $(azureResourceManagerConnection)");
            sb.AppendLine($"          subscriptionId: $(subscriptionId)");
            sb.AppendLine($"          location: $(location)");
        }

        return sb.ToString();
    }

    private static string GenerateDeployJob(GenerationRequest request)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Deploy Job Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("parameters:");
        sb.AppendLine("  - name: environmentName");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: azureResourceManagerConnection");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: subscriptionId");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: location");
        sb.AppendLine("    type: string");
        sb.AppendLine();
        sb.AppendLine("jobs:");
        sb.AppendLine("  - job: Deploy");
        sb.AppendLine("    displayName: 'Deploy to ${{ parameters.environmentName }}'");
        sb.AppendLine("    steps:");
        sb.AppendLine("      - download: current");
        sb.AppendLine("        displayName: 'Download Bicep Artifact'");
        sb.AppendLine("        patterns: '**/*'");

        // Generate a deploy step for each resource group
        foreach (var rg in request.ResourceGroups)
        {
            sb.AppendLine();
            sb.AppendLine("      - template: ../steps/deploy-template.step.yml");
            sb.AppendLine("        parameters:");
            sb.AppendLine($"          azureResourceManagerConnection: ${{{{ parameters.azureResourceManagerConnection }}}}");
            sb.AppendLine($"          subscriptionId: ${{{{ parameters.subscriptionId }}}}");
            sb.AppendLine($"          resourceGroupName: '{rg.Name}'");
            sb.AppendLine($"          location: ${{{{ parameters.location }}}}");
            sb.AppendLine($"          templateFile: '$(Pipeline.Workspace)/**/main.bicep'");
            sb.AppendLine($"          parametersFile: '$(Pipeline.Workspace)/**/parameters/main.${{{{ parameters.environmentName }}}}.bicepparam'");
        }

        return sb.ToString();
    }

    private static string GenerateDeployStep()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Deploy Step Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("parameters:");
        sb.AppendLine("  - name: azureResourceManagerConnection");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: subscriptionId");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: resourceGroupName");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: location");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: templateFile");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: parametersFile");
        sb.AppendLine("    type: string");
        sb.AppendLine();
        sb.AppendLine("steps:");
        sb.AppendLine("  - task: AzureResourceManagerTemplateDeployment@3");
        sb.AppendLine("    displayName: 'Validate ARM Deployment - ${{ parameters.resourceGroupName }}'");
        sb.AppendLine("    inputs:");
        sb.AppendLine("      deploymentScope: 'Resource Group'");
        sb.AppendLine("      azureResourceManagerConnection: '${{ parameters.azureResourceManagerConnection }}'");
        sb.AppendLine("      subscriptionId: '${{ parameters.subscriptionId }}'");
        sb.AppendLine("      action: 'Create Or Update Resource Group'");
        sb.AppendLine("      resourceGroupName: '${{ parameters.resourceGroupName }}'");
        sb.AppendLine("      location: '${{ parameters.location }}'");
        sb.AppendLine("      templateLocation: 'Linked artifact'");
        sb.AppendLine("      csmFile: '${{ parameters.templateFile }}'");
        sb.AppendLine("      csmParametersFile: '${{ parameters.parametersFile }}'");
        sb.AppendLine("      deploymentMode: 'Validation'");
        sb.AppendLine();
        sb.AppendLine("  - task: AzureResourceManagerTemplateDeployment@3");
        sb.AppendLine("    displayName: 'Deploy ARM Template - ${{ parameters.resourceGroupName }}'");
        sb.AppendLine("    inputs:");
        sb.AppendLine("      deploymentScope: 'Resource Group'");
        sb.AppendLine("      azureResourceManagerConnection: '${{ parameters.azureResourceManagerConnection }}'");
        sb.AppendLine("      subscriptionId: '${{ parameters.subscriptionId }}'");
        sb.AppendLine("      action: 'Create Or Update Resource Group'");
        sb.AppendLine("      resourceGroupName: '${{ parameters.resourceGroupName }}'");
        sb.AppendLine("      location: '${{ parameters.location }}'");
        sb.AppendLine("      templateLocation: 'Linked artifact'");
        sb.AppendLine("      csmFile: '${{ parameters.templateFile }}'");
        sb.AppendLine("      csmParametersFile: '${{ parameters.parametersFile }}'");
        sb.AppendLine("      deploymentMode: 'Incremental'");
        sb.AppendLine("      deploymentOutputs: 'armOutputs'");
        sb.AppendLine();
        sb.AppendLine("  - pwsh: |");
        sb.AppendLine("      $outputs = '$(armOutputs)' | ConvertFrom-Json");
        sb.AppendLine("      foreach ($key in $outputs.PSObject.Properties.Name) {");
        sb.AppendLine("        $value = $outputs.$key.value");
        sb.AppendLine("        Write-Host \"##vso[task.setvariable variable=$key;isOutput=true]$value\"");
        sb.AppendLine("      }");
        sb.AppendLine("    displayName: 'Parse ARM Deployment Outputs'");
        sb.AppendLine("    name: armOutput");

        return sb.ToString();
    }

    private static string GenerateCommonVariables(GenerationRequest request)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Common Variables — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("variables:");

        // Use the location from the first environment as default, or "westeurope"
        var defaultLocation = request.Environments.Count > 0
            ? request.Environments[0].Location
            : "westeurope";
        sb.AppendLine($"  location: '{defaultLocation}'");

        return sb.ToString();
    }

    private static string GenerateEnvironmentVariables(EnvironmentDefinition env)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {env.Name} Variables — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("variables:");

        if (!string.IsNullOrEmpty(env.AzureResourceManagerConnection))
        {
            sb.AppendLine($"  azureResourceManagerConnection: '{env.AzureResourceManagerConnection}'");
        }

        if (!string.IsNullOrEmpty(env.SubscriptionId))
        {
            sb.AppendLine($"  subscriptionId: '{env.SubscriptionId}'");
        }

        if (!string.IsNullOrEmpty(env.Location))
        {
            sb.AppendLine($"  location: '{env.Location}'");
        }

        return sb.ToString();
    }
}
