using System.Text;
using InfraFlowSculptor.GenerationCore.Models;
using InfraFlowSculptor.PipelineGeneration.Models;

namespace InfraFlowSculptor.PipelineGeneration;

/// <summary>
/// Main engine for Azure DevOps pipeline YAML generation.
/// Generates shared templates and per-configuration pipeline files.
/// </summary>
public sealed class PipelineGenerationEngine
{
    /// <summary>
    /// Generates per-configuration pipeline files (ci.pipeline.yml, release.pipeline.yml, variables/).
    /// </summary>
    /// <param name="request">The shared generation request containing infrastructure configuration data.</param>
    /// <param name="configName">The name of the infrastructure configuration.</param>
    /// <returns>The generated per-config pipeline files.</returns>
    public PipelineGenerationResult Generate(GenerationRequest request, string configName)
    {
        var files = new Dictionary<string, string>
        {
            ["ci.pipeline.yml"] = GenerateConfigCiPipeline(configName),
            ["release.pipeline.yml"] = GenerateConfigReleasePipeline(request, configName),
            ["variables/vars.yml"] = GenerateConfigVarsFile(configName, request.Environments),
        };

        foreach (var env in request.Environments)
        {
            var envKey = env.ShortName.ToLowerInvariant();
            files[$"variables/{envKey}.yml"] = GenerateEnvironmentVariables(env);
        }

        return new PipelineGenerationResult { TemplateFiles = files };
    }

    /// <summary>
    /// Generates the shared template files for the .azuredevops/ directory.
    /// These are common across all configurations.
    /// </summary>
    /// <param name="configNames">The list of configuration names in the project.</param>
    /// <returns>Dictionary of relative path → YAML content for shared templates.</returns>
    public static IReadOnlyDictionary<string, string> GenerateSharedTemplates(IReadOnlyList<string> configNames)
    {
        return new Dictionary<string, string>
        {
            ["pipelines/ci.pipeline.yml"] = GenerateSharedCiTemplate(configNames),
            ["jobs/deploy.job.yml"] = GenerateSharedDeployJob(),
            ["steps/deploy-template.step.yml"] = GenerateSharedDeployStep(),
        };
    }

    // ── Per-config files ────────────────────────────────────────────────────

    private static string GenerateConfigCiPipeline(string configName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# CI Pipeline — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(date:yyyyMMdd)");
        sb.AppendLine();
        sb.AppendLine("trigger:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        sb.AppendLine("      - release/*");
        sb.AppendLine("  paths:");
        sb.AppendLine("    include:");
        sb.AppendLine($"      - {configName}/*");
        sb.AppendLine();
        sb.AppendLine("extends:");
        sb.AppendLine("  template: ../.azuredevops/pipelines/ci.pipeline.yml");
        sb.AppendLine("  parameters:");
        sb.AppendLine("    continueOnError: true");
        sb.AppendLine($"    projectName: {configName}");
        sb.AppendLine("    buildVersion: $(Build.SourceBranchName)");

        return sb.ToString();
    }

    private static string GenerateConfigReleasePipeline(GenerationRequest request, string configName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Release Pipeline — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(date:yyyyMMdd)");
        sb.AppendLine();
        sb.AppendLine("trigger: none");
        sb.AppendLine();
        sb.AppendLine("variables:");

        // Environment list
        var envList = string.Join(",", request.Environments.Select(e => e.ShortName.ToLowerInvariant()));
        sb.AppendLine($"  - name: environments");
        sb.AppendLine($"    value: {envList}");
        sb.AppendLine("  - name: artifactsPath");
        sb.AppendLine("    value: $(Pipeline.Workspace)/artifacts");
        sb.AppendLine();
        sb.AppendLine("stages:");
        sb.AppendLine("  - ${{ each environment in split(variables.environments, ',') }}:");
        sb.AppendLine("      - stage: \"Deploy_${{ environment }}\"");
        sb.AppendLine("        displayName: \"Deploy ${{ environment }}\"");
        sb.AppendLine("        variables:");
        sb.AppendLine("          - template: variables/${{ environment }}.yml");
        sb.AppendLine("          - template: variables/vars.yml");
        sb.AppendLine();
        sb.AppendLine("        jobs:");
        sb.AppendLine("          - template: ../.azuredevops/jobs/deploy.job.yml");
        sb.AppendLine("            parameters:");
        sb.AppendLine($"              projectName: {configName}");
        sb.AppendLine("              buildVersion: $(Build.SourceBranchName)");
        sb.AppendLine("              buildPipeline: $(buildPipeline)");
        sb.AppendLine("              environment: ${{ environment }}");
        sb.AppendLine("              deployments:");

        // One deployment entry — the main Bicep subscription-level deployment
        sb.AppendLine($"                - displayName: \"Deploy {configName} Infrastructure\"");
        sb.AppendLine("                  resourceGroupName: ${{ variables.resourceGroupName }}");
        sb.AppendLine($"                  deploymentName: {configName.ToLowerInvariant()}-infra-$(Build.BuildNumber)");
        sb.AppendLine($"                  templateFile: {configName}/main.bicep");
        sb.AppendLine($"                  templateParametersFile: {configName}/parameters/main.${{{{environment}}}}.bicepparam");

        return sb.ToString();
    }

    private static string GenerateConfigVarsFile(string configName, IReadOnlyList<EnvironmentDefinition> environments)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Config-level variables — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("variables:");
        sb.AppendLine($"  buildPipeline: '{configName}-CI'");

        var armConnection = environments.FirstOrDefault(e => !string.IsNullOrEmpty(e.AzureResourceManagerConnection))?.AzureResourceManagerConnection;
        if (!string.IsNullOrEmpty(armConnection))
        {
            sb.AppendLine($"  azureResourceManagerConnection: '{armConnection}'");
        }

        return sb.ToString();
    }

    private static string GenerateEnvironmentVariables(EnvironmentDefinition env)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {env.Name} Variables — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("variables:");

        if (!string.IsNullOrEmpty(env.SubscriptionId))
        {
            sb.AppendLine($"  subscriptionId: '{env.SubscriptionId}'");
        }

        if (!string.IsNullOrEmpty(env.Location))
        {
            sb.AppendLine($"  location: '{env.Location}'");
        }

        return sb.ToString();
    }

    // ── Shared templates (.azuredevops/) ─────────────────────────────────

    private static string GenerateSharedCiTemplate(IReadOnlyList<string> configNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Shared CI Pipeline Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("parameters:");
        sb.AppendLine("  - name: continueOnError");
        sb.AppendLine("    type: boolean");
        sb.AppendLine("    default: false");
        sb.AppendLine("  - name: projectName");
        sb.AppendLine("    type: string");
        sb.AppendLine("    values:");
        foreach (var name in configNames)
        {
            sb.AppendLine($"      - {name}");
        }
        sb.AppendLine("  - name: buildVersion");
        sb.AppendLine("    type: string");
        sb.AppendLine();
        sb.AppendLine("stages:");
        sb.AppendLine("  - stage: Build");
        sb.AppendLine("    displayName: 'Build & Publish Artifacts'");
        sb.AppendLine("    jobs:");
        sb.AppendLine("      - job: BuildBicep");
        sb.AppendLine("        displayName: 'Build Bicep'");
        sb.AppendLine("        pool:");
        sb.AppendLine("          vmImage: 'ubuntu-latest'");
        sb.AppendLine("        continueOnError: ${{ parameters.continueOnError }}");
        sb.AppendLine("        steps:");
        sb.AppendLine("          - checkout: self");
        sb.AppendLine();
        sb.AppendLine("          - task: CopyFiles@2");
        sb.AppendLine("            displayName: 'Copy Bicep files'");
        sb.AppendLine("            inputs:");
        sb.AppendLine("              SourceFolder: '$(Build.SourcesDirectory)'");
        sb.AppendLine("              Contents: |");
        sb.AppendLine("                **/*.bicep");
        sb.AppendLine("                **/*.bicepparam");
        sb.AppendLine("                **/*.json");
        sb.AppendLine("              TargetFolder: '$(Build.ArtifactStagingDirectory)'");
        sb.AppendLine();
        sb.AppendLine("          - task: PublishBuildArtifacts@1");
        sb.AppendLine("            displayName: 'Publish Artifact'");
        sb.AppendLine("            inputs:");
        sb.AppendLine("              PathtoPublish: '$(Build.ArtifactStagingDirectory)'");
        sb.AppendLine("              ArtifactName: '${{ parameters.projectName }}-${{ parameters.buildVersion }}'");
        sb.AppendLine("              publishLocation: 'Container'");

        return sb.ToString();
    }

    private static string GenerateSharedDeployJob()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Shared Deploy Job Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("parameters:");
        sb.AppendLine("  - name: projectName");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: buildVersion");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: buildPipeline");
        sb.AppendLine("    type: string");
        sb.AppendLine("    default: ''");
        sb.AppendLine("  - name: environment");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: deployments");
        sb.AppendLine("    type: object");
        sb.AppendLine("    default: []");
        sb.AppendLine();
        sb.AppendLine("jobs:");
        sb.AppendLine("  - job: Deploy");
        sb.AppendLine("    displayName: 'Deploy to ${{ parameters.environment }}'");
        sb.AppendLine("    pool:");
        sb.AppendLine("      vmImage: 'ubuntu-latest'");
        sb.AppendLine("    steps:");
        sb.AppendLine("      - download: current");
        sb.AppendLine("        displayName: 'Download Artifacts'");
        sb.AppendLine("        patterns: '**/*'");
        sb.AppendLine();
        sb.AppendLine("      - ${{ each deployment in parameters.deployments }}:");
        sb.AppendLine("          - template: ../steps/deploy-template.step.yml");
        sb.AppendLine("            parameters:");
        sb.AppendLine("              azureResourceManagerConnection: $(azureResourceManagerConnection)");
        sb.AppendLine("              subscriptionId: $(subscriptionId)");
        sb.AppendLine("              resourceGroupName: ${{ deployment.resourceGroupName }}");
        sb.AppendLine("              location: $(location)");
        sb.AppendLine("              deploymentName: ${{ deployment.deploymentName }}");
        sb.AppendLine("              templateFile: '$(Pipeline.Workspace)/**/${{ deployment.templateFile }}'");
        sb.AppendLine("              templateParametersFile: '$(Pipeline.Workspace)/**/${{ deployment.templateParametersFile }}'");

        return sb.ToString();
    }

    private static string GenerateSharedDeployStep()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Shared Deploy Step Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("parameters:");
        sb.AppendLine("  - name: azureResourceManagerConnection");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: subscriptionId");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: resourceGroupName");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: location");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: deploymentName");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: templateFile");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: templateParametersFile");
        sb.AppendLine("    type: string");
        sb.AppendLine();
        sb.AppendLine("steps:");
        sb.AppendLine("  - task: AzureResourceManagerTemplateDeployment@3");
        sb.AppendLine("    displayName: 'Validate - ${{ parameters.deploymentName }}'");
        sb.AppendLine("    inputs:");
        sb.AppendLine("      deploymentScope: 'Resource Group'");
        sb.AppendLine("      azureResourceManagerConnection: '${{ parameters.azureResourceManagerConnection }}'");
        sb.AppendLine("      subscriptionId: '${{ parameters.subscriptionId }}'");
        sb.AppendLine("      action: 'Create Or Update Resource Group'");
        sb.AppendLine("      resourceGroupName: '${{ parameters.resourceGroupName }}'");
        sb.AppendLine("      location: '${{ parameters.location }}'");
        sb.AppendLine("      templateLocation: 'Linked artifact'");
        sb.AppendLine("      csmFile: '${{ parameters.templateFile }}'");
        sb.AppendLine("      csmParametersFile: '${{ parameters.templateParametersFile }}'");
        sb.AppendLine("      deploymentMode: 'Validation'");
        sb.AppendLine();
        sb.AppendLine("  - task: AzureResourceManagerTemplateDeployment@3");
        sb.AppendLine("    displayName: 'Deploy - ${{ parameters.deploymentName }}'");
        sb.AppendLine("    inputs:");
        sb.AppendLine("      deploymentScope: 'Resource Group'");
        sb.AppendLine("      azureResourceManagerConnection: '${{ parameters.azureResourceManagerConnection }}'");
        sb.AppendLine("      subscriptionId: '${{ parameters.subscriptionId }}'");
        sb.AppendLine("      action: 'Create Or Update Resource Group'");
        sb.AppendLine("      resourceGroupName: '${{ parameters.resourceGroupName }}'");
        sb.AppendLine("      location: '${{ parameters.location }}'");
        sb.AppendLine("      templateLocation: 'Linked artifact'");
        sb.AppendLine("      csmFile: '${{ parameters.templateFile }}'");
        sb.AppendLine("      csmParametersFile: '${{ parameters.templateParametersFile }}'");
        sb.AppendLine("      deploymentMode: 'Incremental'");
        sb.AppendLine("      deploymentOutputs: 'armOutputs'");
        sb.AppendLine();
        sb.AppendLine("  - pwsh: |");
        sb.AppendLine("      $outputs = '$(armOutputs)' | ConvertFrom-Json");
        sb.AppendLine("      foreach ($key in $outputs.PSObject.Properties.Name) {");
        sb.AppendLine("        $value = $outputs.$key.value");
        sb.AppendLine("        Write-Host \"##vso[task.setvariable variable=$key;isOutput=true]$value\"");
        sb.AppendLine("      }");
        sb.AppendLine("    displayName: 'Parse ARM Deployment Outputs'");
        sb.AppendLine("    name: armOutput");

        return sb.ToString();
    }
}
