using System.Text;
using InfraFlowSculptor.GenerationCore.Models;
using InfraFlowSculptor.PipelineGeneration.Models;

namespace InfraFlowSculptor.PipelineGeneration;

/// <summary>
/// Main engine for Azure DevOps pipeline YAML generation.
/// Generates shared templates and per-configuration pipeline files.
/// </summary>
public sealed class PipelineGenerationEngine
{
    /// <summary>
    /// Appends the pool section to the YAML builder.
    /// When <paramref name="agentPoolName"/> is set, uses <c>pool: name: 'value'</c> (self-hosted).
    /// Otherwise, uses <c>pool: vmImage: 'ubuntu-latest'</c> (Microsoft-hosted).
    /// </summary>
    internal static void AppendPool(StringBuilder sb, string? agentPoolName, string indent = "        ")
    {
        sb.AppendLine($"{indent}pool:");
        if (!string.IsNullOrEmpty(agentPoolName))
        {
            sb.AppendLine($"{indent}  name: '{agentPoolName}'");
        }
        else
        {
            sb.AppendLine($"{indent}  vmImage: 'ubuntu-latest'");
        }
    }

    /// <summary>
    /// Generates per-configuration pipeline files (ci.pipeline.yml, release.pipeline.yml, variables/).
    /// </summary>
    /// <param name="request">The shared generation request containing infrastructure configuration data.</param>
    /// <param name="configName">The name of the infrastructure configuration.</param>
    /// <param name="isMonoRepo">When <c>true</c>, skips per-config variables folder (variables are shared at root level).</param>
    /// <returns>The generated per-config pipeline files.</returns>
    public PipelineGenerationResult Generate(GenerationRequest request, string configName, bool isMonoRepo = false)
    {
        var files = new Dictionary<string, string>
        {
            ["ci.pipeline.yml"] = GenerateConfigCiPipeline(configName),
            ["pr.pipeline.yml"] = GenerateConfigPrPipeline(configName),
            ["release.pipeline.yml"] = GenerateConfigReleasePipeline(request, configName, isMonoRepo),
        };

        if (!isMonoRepo)
        {
            files["variables/vars.yml"] = GenerateConfigVarsFile(configName, request.Environments);

            foreach (var env in request.Environments)
            {
                var envKey = env.ShortName.ToLowerInvariant();
                files[$"variables/{envKey}.yml"] = GenerateEnvironmentVariables(env);
            }
        }

        return new PipelineGenerationResult { TemplateFiles = files };
    }

    /// <summary>
    /// Generates the shared template files for the .azuredevops/ directory.
    /// These are common across all configurations.
    /// </summary>
    /// <param name="configNames">The list of configuration names in the project.</param>
    /// <param name="environments">The deduplicated environment definitions across all configurations.</param>
    /// <returns>Dictionary of relative path → YAML content for shared templates.</returns>
    public static IReadOnlyDictionary<string, string> GenerateSharedTemplates(
        IReadOnlyList<string> configNames,
        IReadOnlyList<EnvironmentDefinition> environments,
        string? agentPoolName = null,
        string? bicepBasePath = null,
        string? pipelineBasePath = null)
    {
        var environmentNames = environments.Select(e => e.ShortName.ToLowerInvariant()).ToList();

        var files = new Dictionary<string, string>
        {
            ["pipelines/ci.pipeline.yml"] = GenerateSharedCiTemplate(configNames, agentPoolName, bicepBasePath, pipelineBasePath),
            ["pipelines/pr.pipeline.yml"] = GenerateSharedPrTemplate(configNames, agentPoolName, bicepBasePath, pipelineBasePath),
            ["jobs/deploy.job.yml"] = GenerateSharedDeployJob(configNames, environmentNames, agentPoolName),
            ["steps/checkout.step.yml"] = GenerateSharedCheckoutStep(),
            ["steps/deploy-template.step.yml"] = GenerateSharedDeployStep(),
        };

        foreach (var env in environments)
        {
            var envKey = env.ShortName.ToLowerInvariant();
            files[$"variables/{envKey}.variables.yml"] = GenerateRootEnvironmentVariables(env);
        }

        return files;
    }

    // ── Per-config files ────────────────────────────────────────────────────

    private static string GenerateConfigPrPipeline(string configName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# PR Validation Pipeline — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(date:yyyyMMdd)");
        sb.AppendLine();
        sb.AppendLine("pr:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        sb.AppendLine("      - main");
        sb.AppendLine("      - develop");
        sb.AppendLine("      - release/*");
        sb.AppendLine("  paths:");
        sb.AppendLine("    include:");
        sb.AppendLine($"      - {configName}/*");
        sb.AppendLine();
        sb.AppendLine("extends:");
        sb.AppendLine("  template: ../.azuredevops/pipelines/pr.pipeline.yml");
        sb.AppendLine("  parameters:");
        sb.AppendLine($"    projectName: {configName}");

        return sb.ToString();
    }

    private static string GenerateConfigCiPipeline(string configName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# CI Pipeline — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(date:yyyyMMdd)");
        sb.AppendLine();
        sb.AppendLine("trigger:");
        sb.AppendLine("  branches:");
        sb.AppendLine("    include:");
        sb.AppendLine("      - release/*");
        sb.AppendLine("  paths:");
        sb.AppendLine("    include:");
        sb.AppendLine($"      - {configName}/*");
        sb.AppendLine();
        sb.AppendLine("extends:");
        sb.AppendLine("  template: ../.azuredevops/pipelines/ci.pipeline.yml");
        sb.AppendLine("  parameters:");
        sb.AppendLine("    continueOnError: true");
        sb.AppendLine($"    projectName: {configName}");

        return sb.ToString();
    }

    private static string GenerateConfigReleasePipeline(GenerationRequest request, string configName, bool isMonoRepo = false)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Release Pipeline — Auto-generated by InfraFlowSculptor");
        sb.AppendLine("name: $(date:yyyyMMdd)");
        sb.AppendLine();
        sb.AppendLine("trigger: none");
        sb.AppendLine();

        // Reference the CI pipeline to download its published artifact
        sb.AppendLine("resources:");
        sb.AppendLine("  pipelines:");
        sb.AppendLine("    - pipeline: ci");
        sb.AppendLine($"      source: '{configName}-CI'");
        sb.AppendLine("      trigger: none");
        sb.AppendLine();

        sb.AppendLine("variables:");

        // Environment list
        var envList = string.Join(",", request.Environments.Select(e => e.ShortName.ToLowerInvariant()));
        sb.AppendLine($"  - name: environments");
        sb.AppendLine($"    value: {envList}");

        sb.AppendLine();
        sb.AppendLine("stages:");
        sb.AppendLine("  - ${{ each environment in split(variables.environments, ',') }}:");
        sb.AppendLine("      - stage: \"Deploy_${{ environment }}\"");
        sb.AppendLine("        displayName: \"Deploy ${{ environment }}\"");

        var hasStageVariables = !isMonoRepo || request.PipelineVariableGroups.Count > 0;

        if (hasStageVariables)
        {
            sb.AppendLine("        variables:");
        }

        if (!isMonoRepo)
        {
            // Reference config-local variables (single-config mode)
            sb.AppendLine("          - template: variables/${{ environment }}.yml");
            sb.AppendLine("          - template: variables/vars.yml");
        }

        // Emit variable group references (expand {env} placeholder to Azure DevOps template expression)
        foreach (var group in request.PipelineVariableGroups)
        {
            var resolvedName = group.GroupName.Replace("{env}", "${{ environment }}", StringComparison.OrdinalIgnoreCase);
            sb.AppendLine($"          - group: {resolvedName}");
        }
        sb.AppendLine();
        sb.AppendLine("        jobs:");
        sb.AppendLine("          - template: ../.azuredevops/jobs/deploy.job.yml");
        sb.AppendLine("            parameters:");
        sb.AppendLine($"              projectName: {configName}");
        sb.AppendLine("              environment: ${{ environment }}");
        sb.AppendLine("              deployments:");

        // One deployment entry — the main Bicep subscription-level deployment
        sb.AppendLine($"                - displayName: \"Deploy {configName} Infrastructure\"");
        sb.AppendLine($"                  deploymentName: {configName.ToLowerInvariant()}-infra-$(Build.BuildNumber)");
        sb.AppendLine($"                  templateFile: $(Pipeline.Workspace)/ci/drop/{configName}/main.bicep");
        sb.AppendLine($"                  templateParametersFile: $(Pipeline.Workspace)/ci/drop/{configName}/parameters/main.${{{{environment}}}}.bicepparam");

        // Emit overrideParameters from variable group mappings
        var overrideParams = BuildOverrideParameters(request.PipelineVariableGroups);
        if (!string.IsNullOrEmpty(overrideParams))
        {
            sb.AppendLine($"                  overrideParameters: {overrideParams}");
        }

        return sb.ToString();
    }

    private static string GenerateConfigVarsFile(string configName, IReadOnlyList<EnvironmentDefinition> environments)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Config-level variables — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("variables:");

        var armConnection = environments.FirstOrDefault(e => !string.IsNullOrEmpty(e.AzureResourceManagerConnection))?.AzureResourceManagerConnection;
        if (!string.IsNullOrEmpty(armConnection))
        {
            sb.AppendLine($"  azureResourceManagerConnection: '{armConnection}'");
        }

        return sb.ToString();
    }

    private static string GenerateEnvironmentVariables(EnvironmentDefinition env)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {env.Name} Variables — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("variables:");

        if (!string.IsNullOrEmpty(env.SubscriptionId))
        {
            sb.AppendLine($"  subscriptionId: '{env.SubscriptionId}'");
        }

        if (!string.IsNullOrEmpty(env.Location))
        {
            sb.AppendLine($"  location: '{env.Location}'");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generates a root-level environment variables file for mono-repo shared usage.
    /// Placed under <c>.azuredevops/variables/{env}.variables.yml</c>.
    /// </summary>
    private static string GenerateRootEnvironmentVariables(EnvironmentDefinition env)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {env.Name} Variables — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("variables:");

        if (!string.IsNullOrEmpty(env.AzureResourceManagerConnection))
        {
            sb.AppendLine($"  azureResourceManagerConnection: '{env.AzureResourceManagerConnection}'");
        }

        if (!string.IsNullOrEmpty(env.SubscriptionId))
        {
            sb.AppendLine($"  subscriptionId: '{env.SubscriptionId}'");
        }

        if (!string.IsNullOrEmpty(env.Location))
        {
            sb.AppendLine($"  location: '{env.Location}'");
        }

        return sb.ToString();
    }

    // ── Shared templates (.azuredevops/) ─────────────────────────────────

    private static string GenerateSharedPrTemplate(
        IReadOnlyList<string> configNames,
        string? agentPoolName,
        string? bicepBasePath,
        string? pipelineBasePath)
    {
        var checkoutDirectories = new[]
        {
            BuildRepoRelativePath(pipelineBasePath, ".azuredevops"),
            BuildRepoRelativePath(bicepBasePath, "${{ parameters.projectName }}"),
        }.Distinct().ToList();

        var sb = new StringBuilder();
        sb.AppendLine("# Shared PR Validation Pipeline Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("parameters:");
        sb.AppendLine("  - name: projectName");
        sb.AppendLine("    type: string");
        sb.AppendLine("    values:");
        foreach (var name in configNames)
        {
            sb.AppendLine($"      - {name}");
        }
        sb.AppendLine("  - name: bicepFiles");
        sb.AppendLine("    type: object");
        sb.AppendLine("    default: [ main.bicep ]");
        sb.AppendLine("  - name: preparationSteps");
        sb.AppendLine("    type: stepList");
        sb.AppendLine("    default: []");
        sb.AppendLine("  - name: additionalSteps");
        sb.AppendLine("    type: stepList");
        sb.AppendLine("    default: []");
        sb.AppendLine();
        sb.AppendLine("variables:");
        sb.AppendLine("  - name: workingDirectory");
        sb.AppendLine($"    value: {BuildSourcesDirectoryPath(BuildRepoRelativePath(bicepBasePath, "${{ parameters.projectName }}"))}");
        sb.AppendLine();
        sb.AppendLine("stages:");
        sb.AppendLine("  - stage: validate");
        sb.AppendLine("    displayName: Validate");
        sb.AppendLine();
        sb.AppendLine("    jobs:");
        sb.AppendLine("      - job: validate");
        sb.AppendLine("        displayName: Validate");
        AppendPool(sb, agentPoolName);
        sb.AppendLine();
        sb.AppendLine("        steps:");
        sb.AppendLine("          - ${{ parameters.preparationSteps }}");
        sb.AppendLine();
        sb.AppendLine("          - template: ../steps/checkout.step.yml");
        sb.AppendLine("            parameters:");
        sb.AppendLine("              directories:");
        foreach (var directory in checkoutDirectories)
        {
            sb.AppendLine($"                - {directory}");
        }
        sb.AppendLine();
        sb.AppendLine("          - pwsh: |");
        sb.AppendLine($"              $configPath = \"{BuildSourcesDirectoryPath(BuildRepoRelativePath(bicepBasePath, "bicepconfig.json"))}\"");
        sb.AppendLine("              if (Test-Path $configPath) {");
        sb.AppendLine("                $config = Get-Content -Path $configPath | ConvertFrom-Json");
        sb.AppendLine("                $config.analyzers.core.rules.'use-recent-api-versions'.level = \"warning\"");
        sb.AppendLine("                $config | ConvertTo-Json -Depth 99 | Set-Content -Path $configPath");
        sb.AppendLine("              }");
        sb.AppendLine("            displayName: Update Bicep Config");
        sb.AppendLine("            name: UpdateBicepConfig");
        sb.AppendLine();
        sb.AppendLine("          - ${{ each bicepFile in parameters.bicepFiles }}:");
        sb.AppendLine("            - script: |");
        sb.AppendLine("                az bicep build --file \"$(workingDirectory)/${{ bicepFile }}\"");
        sb.AppendLine("              displayName: Lint ${{ bicepFile }}");
        sb.AppendLine();
        sb.AppendLine("          - ${{ parameters.additionalSteps }}");

        return sb.ToString();
    }

    private static string GenerateSharedCheckoutStep()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Shared Checkout Step Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("parameters:");
        sb.AppendLine("  - name: directories");
        sb.AppendLine("    type: object");
        sb.AppendLine("    default: []");
        sb.AppendLine();
        sb.AppendLine("steps:");
        sb.AppendLine();
        sb.AppendLine("  - ${{ if gt(length(parameters.directories), 0) }}:");
        sb.AppendLine("    - checkout: self");
        sb.AppendLine("      sparseCheckoutDirectories: ${{ join(' ', parameters.directories) }}");
        sb.AppendLine();
        sb.AppendLine("  - ${{ if eq(length(parameters.directories), 0) }}:");
        sb.AppendLine("    - checkout: self");
        sb.AppendLine("      clean: true");

        return sb.ToString();
    }

    private static string GenerateSharedCiTemplate(
        IReadOnlyList<string> configNames,
        string? agentPoolName,
        string? bicepBasePath,
        string? pipelineBasePath)
    {
        var checkoutDirectories = new[]
        {
            BuildRepoRelativePath(pipelineBasePath, ".azuredevops"),
            BuildRepoRelativePath(bicepBasePath, "Common"),
            BuildRepoRelativePath(bicepBasePath, "${{ parameters.projectName }}"),
        }.Distinct().ToList();

        var sb = new StringBuilder();
        sb.AppendLine("# Shared CI Pipeline Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("parameters:");
        sb.AppendLine("  - name: continueOnError");
        sb.AppendLine("    type: boolean");
        sb.AppendLine("    default: false");
        sb.AppendLine("  - name: projectName");
        sb.AppendLine("    type: string");
        sb.AppendLine("    values:");
        foreach (var name in configNames)
        {
            sb.AppendLine($"      - {name}");
        }
        sb.AppendLine();
        sb.AppendLine("stages:");
        sb.AppendLine("  - stage: Build");
        sb.AppendLine("    displayName: 'Build & Publish Artifacts'");
        sb.AppendLine("    jobs:");
        sb.AppendLine("      - job: BuildBicep");
        sb.AppendLine("        displayName: 'Build Bicep'");
        AppendPool(sb, agentPoolName);
        sb.AppendLine("        continueOnError: ${{ parameters.continueOnError }}");
        sb.AppendLine("        steps:");
        sb.AppendLine("          - template: ../steps/checkout.step.yml");
        sb.AppendLine("            parameters:");
        sb.AppendLine("              directories:");
        foreach (var directory in checkoutDirectories)
        {
            sb.AppendLine($"                - {directory}");
        }
        sb.AppendLine();
        sb.AppendLine("          - task: CopyFiles@2");
        sb.AppendLine("            displayName: 'Copy Bicep files'");
        sb.AppendLine("            inputs:");
        sb.AppendLine($"              SourceFolder: '{BuildSourcesDirectoryPath(bicepBasePath)}'");
        sb.AppendLine("              Contents: |");
        sb.AppendLine("                **/*.bicep");
        sb.AppendLine("                **/*.bicepparam");
        sb.AppendLine("                **/*.json");
        sb.AppendLine("              TargetFolder: '$(Build.ArtifactStagingDirectory)'");
        sb.AppendLine();
        sb.AppendLine("          - pwsh: |");
        sb.AppendLine("              $artifactRoot = '$(Build.ArtifactStagingDirectory)'");
        sb.AppendLine("              $commonPath = Join-Path $artifactRoot 'Common'");
        sb.AppendLine("              $projectPath = Join-Path $artifactRoot '${{ parameters.projectName }}'");
        sb.AppendLine("              $mainBicepPath = Join-Path $projectPath 'main.bicep'");
        sb.AppendLine();
        sb.AppendLine("              if (-not (Test-Path -LiteralPath $artifactRoot)) {");
        sb.AppendLine("                throw \"Artifact staging directory not found: $artifactRoot\"");
        sb.AppendLine("              }");
        sb.AppendLine();
        sb.AppendLine("              Write-Host \"Artifact staging contents:\"");
        sb.AppendLine("              Get-ChildItem -LiteralPath $artifactRoot -Recurse | Select-Object FullName | Format-Table -AutoSize | Out-String | Write-Host");
        sb.AppendLine();
        sb.AppendLine("              if (-not (Test-Path -LiteralPath $commonPath)) {");
        sb.AppendLine("                throw \"Common artifact folder not found: $commonPath\"");
        sb.AppendLine("              }");
        sb.AppendLine();
        sb.AppendLine("              if (-not (Test-Path -LiteralPath $projectPath)) {");
        sb.AppendLine("                throw \"Project artifact folder not found: $projectPath\"");
        sb.AppendLine("              }");
        sb.AppendLine();
        sb.AppendLine("              if (-not (Test-Path -LiteralPath $mainBicepPath)) {");
        sb.AppendLine("                throw \"Main Bicep file not found in artifact: $mainBicepPath\"");
        sb.AppendLine("              }");
        sb.AppendLine("            displayName: 'Validate artifact contents'");
        sb.AppendLine();
        sb.AppendLine("          - task: PublishBuildArtifacts@1");
        sb.AppendLine("            displayName: 'Publish Artifact'");
        sb.AppendLine("            inputs:");
        sb.AppendLine("              PathtoPublish: '$(Build.ArtifactStagingDirectory)'");
        sb.AppendLine("              ArtifactName: 'drop'");
        sb.AppendLine("              publishLocation: 'Container'");

        return sb.ToString();
    }

    private static string BuildRepoRelativePath(string? basePath, string relativePath)
    {
        if (string.IsNullOrWhiteSpace(basePath))
        {
            return relativePath;
        }

        return $"{basePath.Trim('/')}/{relativePath}";
    }

    private static string BuildSourcesDirectoryPath(string? relativePath)
    {
        if (string.IsNullOrWhiteSpace(relativePath))
        {
            return "$(Build.SourcesDirectory)";
        }

        return $"$(Build.SourcesDirectory)/{relativePath.Trim('/')}";
    }

    /// <summary>
    /// Builds the overrideParameters string from all variable group mappings.
    /// Format: <c>-bicepParam $(PIPELINE_VAR) -bicepParam2 $(PIPELINE_VAR2)</c>
    /// </summary>
    private static string BuildOverrideParameters(
        IReadOnlyList<GenerationCore.Models.PipelineVariableGroupDefinition> variableGroups)
    {
        var allMappings = variableGroups
            .SelectMany(g => g.Mappings)
            .ToList();

        if (allMappings.Count == 0)
            return string.Empty;

        return string.Join(" ", allMappings.Select(m => $"-{m.BicepParameterName} $({m.PipelineVariableName})"));
    }

    private static string GenerateSharedDeployJob(
        IReadOnlyList<string> configNames,
        IReadOnlyList<string> environmentNames,
        string? agentPoolName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Shared Deploy Job Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("parameters:");
        sb.AppendLine("  - name: projectName");
        sb.AppendLine("    type: string");
        sb.AppendLine("    values:");
        foreach (var name in configNames)
        {
            sb.AppendLine($"      - {name}");
        }
        sb.AppendLine("  - name: environment");
        sb.AppendLine("    type: string");
        sb.AppendLine("    values:");
        foreach (var env in environmentNames)
        {
            sb.AppendLine($"      - {env}");
        }
        sb.AppendLine("  - name: deployments");
        sb.AppendLine("    type: object");
        sb.AppendLine("    default: []");
        sb.AppendLine();
        sb.AppendLine("jobs:");
        sb.AppendLine("  - job: Deploy");
        sb.AppendLine("    displayName: 'Deploy to ${{ parameters.environment }}'");
        AppendPool(sb, agentPoolName, "    ");
        sb.AppendLine("    variables:");
        sb.AppendLine("      - template: ../variables/${{ parameters.environment }}.variables.yml");
        sb.AppendLine("    steps:");
        sb.AppendLine("      - checkout: none");
        sb.AppendLine("      - download: ci");
        sb.AppendLine("        artifact: drop");
        sb.AppendLine("        displayName: 'Download CI Artifacts'");
        sb.AppendLine();
        sb.AppendLine("      - ${{ each deployment in parameters.deployments }}:");
        sb.AppendLine("          - template: ../steps/deploy-template.step.yml");
        sb.AppendLine("            parameters:");
        sb.AppendLine("              azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}");
        sb.AppendLine("              subscriptionId: ${{ variables.subscriptionId }}");
        sb.AppendLine("              location: ${{ variables.location }}");
        sb.AppendLine("              deploymentName: ${{ deployment.deploymentName }}");
        sb.AppendLine("              templateFile: '${{ deployment.templateFile }}'");
        sb.AppendLine("              templateParametersFile: '${{ deployment.templateParametersFile }}'");
        sb.AppendLine("              overrideParameters: ${{ deployment.overrideParameters }}");

        return sb.ToString();
    }

    private static string GenerateSharedDeployStep()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Shared Deploy Step Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        sb.AppendLine("parameters:");
        sb.AppendLine("  - name: azureResourceManagerConnection");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: subscriptionId");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: location");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: deploymentName");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: templateFile");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: templateParametersFile");
        sb.AppendLine("    type: string");
        sb.AppendLine("  - name: overrideParameters");
        sb.AppendLine("    type: string");
        sb.AppendLine("    default: ''");
        sb.AppendLine();
        sb.AppendLine("steps:");
        sb.AppendLine("  - pwsh: |");
        sb.AppendLine("      $templateFile = '${{ parameters.templateFile }}'");
        sb.AppendLine("      $parametersFile = '${{ parameters.templateParametersFile }}'");
        sb.AppendLine();
        sb.AppendLine("      if (-not (Test-Path -LiteralPath $templateFile)) {");
        sb.AppendLine("        $templateDirectory = Split-Path -Path $templateFile -Parent");
        sb.AppendLine("        if (Test-Path -LiteralPath $templateDirectory) {");
        sb.AppendLine("          Write-Host \"Template directory contents:\"");
        sb.AppendLine("          Get-ChildItem -LiteralPath $templateDirectory -Recurse | Select-Object FullName | Format-Table -AutoSize | Out-String | Write-Host");
        sb.AppendLine("        }");
        sb.AppendLine("        throw \"Template file not found: $templateFile\"");
        sb.AppendLine("      }");
        sb.AppendLine();
        sb.AppendLine("      if (-not (Test-Path -LiteralPath $parametersFile)) {");
        sb.AppendLine("        $parametersDirectory = Split-Path -Path $parametersFile -Parent");
        sb.AppendLine("        $fallbackFiles = @()");
        sb.AppendLine("        if (Test-Path -LiteralPath $parametersDirectory) {");
        sb.AppendLine("          Write-Host \"Parameters directory contents:\"");
        sb.AppendLine("          Get-ChildItem -LiteralPath $parametersDirectory -Recurse | Select-Object FullName | Format-Table -AutoSize | Out-String | Write-Host");
        sb.AppendLine("          $fallbackFiles = @(Get-ChildItem -LiteralPath $parametersDirectory -Filter 'main.*.bicepparam' -File)");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if ($fallbackFiles.Count -eq 1) {");
        sb.AppendLine("          $parametersFile = $fallbackFiles[0].FullName");
        sb.AppendLine("          Write-Warning \"Expected parameters file not found. Falling back to: $parametersFile\"");
        sb.AppendLine("        }");
        sb.AppendLine("        else {");
        sb.AppendLine("          throw \"Parameters file not found: $parametersFile\"");
        sb.AppendLine("        }");
        sb.AppendLine("      }");
        sb.AppendLine();
        sb.AppendLine("      $resolvedTemplateFile = (Resolve-Path -LiteralPath $templateFile).Path");
        sb.AppendLine("      $resolvedParametersFile = (Resolve-Path -LiteralPath $parametersFile).Path");
        sb.AppendLine("      $compiledTemplateFile = $resolvedTemplateFile");
        sb.AppendLine("      $compiledParametersFile = $resolvedParametersFile");
        sb.AppendLine("      $parametersFileForCompilation = $resolvedParametersFile");
        sb.AppendLine();
        sb.AppendLine("      if ([System.IO.Path]::GetExtension($resolvedTemplateFile).Equals('.bicep', [System.StringComparison]::OrdinalIgnoreCase)) {");
        sb.AppendLine("        $compiledTemplateFile = [System.IO.Path]::ChangeExtension($resolvedTemplateFile, '.json')");
        sb.AppendLine("        az bicep build --file $resolvedTemplateFile --outfile $compiledTemplateFile");
        sb.AppendLine("        if ($LASTEXITCODE -ne 0) {");
        sb.AppendLine("          throw \"Failed to compile template file: $resolvedTemplateFile\"");
        sb.AppendLine("        }");
        sb.AppendLine("      }");
        sb.AppendLine();
        sb.AppendLine("      if ([System.IO.Path]::GetExtension($resolvedParametersFile).Equals('.bicepparam', [System.StringComparison]::OrdinalIgnoreCase)) {");
        sb.AppendLine("        $parametersDirectory = Split-Path -Path $resolvedParametersFile -Parent");
        sb.AppendLine("        $legacyMainPath = Join-Path $parametersDirectory 'main.bicep'");
        sb.AppendLine("        $actualMainPath = Join-Path (Split-Path -Path $parametersDirectory -Parent) 'main.bicep'");
        sb.AppendLine("        $parametersContent = Get-Content -LiteralPath $resolvedParametersFile -Raw");
        sb.AppendLine();
        sb.AppendLine("        if (-not (Test-Path -LiteralPath $legacyMainPath) -and (Test-Path -LiteralPath $actualMainPath) -and $parametersContent.Contains(\"using 'main.bicep'\")) {");
        sb.AppendLine("          $patchedParametersFile = Join-Path $parametersDirectory (([System.IO.Path]::GetFileNameWithoutExtension($resolvedParametersFile)) + '.autofix.bicepparam')");
        sb.AppendLine("          $patchedParametersContent = $parametersContent.Replace(\"using 'main.bicep'\", \"using '../main.bicep'\")");
        sb.AppendLine("          Set-Content -LiteralPath $patchedParametersFile -Value $patchedParametersContent -NoNewline");
        sb.AppendLine("          $parametersFileForCompilation = $patchedParametersFile");
        sb.AppendLine("          Write-Warning \"Patched legacy parameters file using-path for compilation: $patchedParametersFile\"");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        $compiledParametersFile = Join-Path (Split-Path -Path $resolvedParametersFile -Parent) (([System.IO.Path]::GetFileNameWithoutExtension($resolvedParametersFile)) + '.parameters.json')");
        sb.AppendLine("        az bicep build-params --file $parametersFileForCompilation --outfile $compiledParametersFile");
        sb.AppendLine("        if ($LASTEXITCODE -ne 0) {");
        sb.AppendLine("          throw \"Failed to compile parameters file: $parametersFileForCompilation\"");
        sb.AppendLine("        }");
        sb.AppendLine("      }");
        sb.AppendLine();
        sb.AppendLine("      Write-Host \"Using template file: $resolvedTemplateFile\"");
        sb.AppendLine("      Write-Host \"Using parameters file: $resolvedParametersFile\"");
        sb.AppendLine("      Write-Host \"Using compiled template file: $compiledTemplateFile\"");
        sb.AppendLine("      Write-Host \"Using compiled parameters file: $compiledParametersFile\"");
        sb.AppendLine("      Write-Host \"##vso[task.setvariable variable=ResolvedTemplateFile]$compiledTemplateFile\"");
        sb.AppendLine("      Write-Host \"##vso[task.setvariable variable=ResolvedParametersFile]$compiledParametersFile\"");
        sb.AppendLine("    displayName: 'Resolve deployment files'");
        sb.AppendLine();
        sb.AppendLine("  - task: AzureResourceManagerTemplateDeployment@3");
        sb.AppendLine("    displayName: 'Validate - ${{ parameters.deploymentName }}'");
        sb.AppendLine("    inputs:");
        sb.AppendLine("      deploymentScope: 'Subscription'");
        sb.AppendLine("      azureResourceManagerConnection: '${{ parameters.azureResourceManagerConnection }}'");
        sb.AppendLine("      subscriptionId: '${{ parameters.subscriptionId }}'");
        sb.AppendLine("      location: '${{ parameters.location }}'");
        sb.AppendLine("      templateLocation: 'Linked artifact'");
        sb.AppendLine("      csmFile: '$(ResolvedTemplateFile)'");
        sb.AppendLine("      csmParametersFile: '$(ResolvedParametersFile)'");
        sb.AppendLine("      overrideParameters: '${{ parameters.overrideParameters }}'");
        sb.AppendLine("      deploymentMode: 'Validation'");
        sb.AppendLine();
        sb.AppendLine("  - task: AzureResourceManagerTemplateDeployment@3");
        sb.AppendLine("    displayName: 'Deploy - ${{ parameters.deploymentName }}'");
        sb.AppendLine("    inputs:");
        sb.AppendLine("      deploymentScope: 'Subscription'");
        sb.AppendLine("      azureResourceManagerConnection: '${{ parameters.azureResourceManagerConnection }}'");
        sb.AppendLine("      subscriptionId: '${{ parameters.subscriptionId }}'");
        sb.AppendLine("      location: '${{ parameters.location }}'");
        sb.AppendLine("      templateLocation: 'Linked artifact'");
        sb.AppendLine("      csmFile: '$(ResolvedTemplateFile)'");
        sb.AppendLine("      csmParametersFile: '$(ResolvedParametersFile)'");
        sb.AppendLine("      overrideParameters: '${{ parameters.overrideParameters }}'");
        sb.AppendLine("      deploymentMode: 'Incremental'");
        sb.AppendLine("      deploymentOutputs: 'armOutputs'");
        sb.AppendLine();
        sb.AppendLine("  - pwsh: |");
        sb.AppendLine("      $raw = '$(armOutputs)'");
        sb.AppendLine("      if ([string]::IsNullOrWhiteSpace($raw) -or $raw -eq '$(armOutputs)') {");
        sb.AppendLine("        Write-Host 'No ARM deployment outputs to parse — skipping.'");
        sb.AppendLine("        return");
        sb.AppendLine("      }");
        sb.AppendLine("      $outputs = $raw | ConvertFrom-Json");
        sb.AppendLine("      foreach ($key in $outputs.PSObject.Properties.Name) {");
        sb.AppendLine("        $value = $outputs.$key.value");
        sb.AppendLine("        Write-Host \"##vso[task.setvariable variable=$key;isOutput=true]$value\"");
        sb.AppendLine("      }");
        sb.AppendLine("    displayName: 'Parse ARM Deployment Outputs'");
        sb.AppendLine("    name: armOutput");

        return sb.ToString();
    }
}
