using System.Text;
using static InfraFlowSculptor.PipelineGeneration.PipelineGenerationEngine;

namespace InfraFlowSculptor.PipelineGeneration.SharedTemplates;

/// <summary>
/// Builds the shared infrastructure Azure DevOps YAML templates emitted by <see cref="PipelineGenerationEngine"/>.
/// </summary>
internal static class InfraPipelineSharedTemplateBuilder
{
    private const string AzureDevOpsDirectory = ".azuredevops";
    private const string CommonDirectory = "Common";
    private const string ProjectNameParameterExpression = "${{ parameters.projectName }}";
    private const string MainBicepFileName = "main.bicep";
    private const string LegacyMainBicepUsingStatement = "using 'main.bicep'";
    private const string ParentMainBicepUsingStatement = "using '../main.bicep'";
    private const string ResolvedTemplateFileVariable = "$(ResolvedTemplateFile)";
    private const string ResolvedParametersFileVariable = "$(ResolvedParametersFile)";
    private const string SubscriptionDeploymentScope = "Subscription";
    private const string ValidationDeploymentMode = "Validation";
    private const string IncrementalDeploymentMode = "Incremental";
    private const string StringParameterType = "string";
    private const string ClosingBraceIndentedSix = "              }";
    private const string ClosingBraceIndentedFour = "        }";
    private const string ClosingBraceIndentedThree = "      }";

    internal static string GenerateSharedPrTemplate(
        IReadOnlyList<string> configNames,
        string? agentPoolName,
        string? bicepBasePath,
        string? pipelineBasePath)
    {
        var checkoutDirectories = new[]
        {
            BuildRepoRelativePath(pipelineBasePath, AzureDevOpsDirectory),
            BuildRepoRelativePath(bicepBasePath, CommonDirectory),
            BuildRepoRelativePath(bicepBasePath, ProjectNameParameterExpression),
        }.Distinct().ToList();

        var sb = new StringBuilder();
        sb.AppendLine("# Shared PR Validation Pipeline Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        AppendParametersHeader(sb);
        AppendStringParameterWithValues(sb, "projectName", configNames);
        AppendParameterWithDefault(sb, "bicepFiles", "object", "[ main.bicep ]");
        AppendParameterWithDefault(sb, "preparationSteps", "stepList", "[]");
        AppendParameterWithDefault(sb, "additionalSteps", "stepList", "[]");
        sb.AppendLine();
        sb.AppendLine("variables:");
        sb.AppendLine("  - name: workingDirectory");
        sb.AppendLine($"    value: {BuildSourcesDirectoryPath(BuildRepoRelativePath(bicepBasePath, ProjectNameParameterExpression))}");
        sb.AppendLine();
        sb.AppendLine("stages:");
        sb.AppendLine("  - stage: validate");
        sb.AppendLine("    displayName: Validate");
        sb.AppendLine();
        sb.AppendLine("    jobs:");
        sb.AppendLine("      - job: validate");
        sb.AppendLine("        displayName: Validate");
        AppendPool(sb, agentPoolName);
        sb.AppendLine();
        sb.AppendLine("        steps:");
        sb.AppendLine("          - ${{ parameters.preparationSteps }}");
        sb.AppendLine();
        sb.AppendLine("          - template: ../steps/checkout.step.yml");
        sb.AppendLine("            parameters:");
        sb.AppendLine("              directories:");
        foreach (var directory in checkoutDirectories)
        {
            sb.AppendLine($"                - {directory}");
        }
        sb.AppendLine();
        sb.AppendLine("          - powershell: |");
        sb.AppendLine($"              $configPath = \"{BuildSourcesDirectoryPath(BuildRepoRelativePath(bicepBasePath, "bicepconfig.json"))}\"");
        sb.AppendLine("              if (Test-Path $configPath) {");
        sb.AppendLine("                $config = Get-Content -Path $configPath | ConvertFrom-Json");
        sb.AppendLine("                $config.analyzers.core.rules.'use-recent-api-versions'.level = \"warning\"");
        sb.AppendLine("                $config | ConvertTo-Json -Depth 99 | Set-Content -Path $configPath");
        sb.AppendLine(ClosingBraceIndentedSix);
        sb.AppendLine("            displayName: Update Bicep Config");
        sb.AppendLine("            name: UpdateBicepConfig");
        sb.AppendLine();
        sb.AppendLine("          - ${{ each bicepFile in parameters.bicepFiles }}:");
        sb.AppendLine("            - script: |");
        sb.AppendLine("                az bicep build --file \"$(workingDirectory)/${{ bicepFile }}\"");
        sb.AppendLine("              displayName: Lint ${{ bicepFile }}");
        sb.AppendLine();
        sb.AppendLine("          - ${{ parameters.additionalSteps }}");

        return sb.ToString();
    }

    internal static string GenerateSharedCheckoutStep()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Shared Checkout Step Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        AppendParametersHeader(sb);
        AppendParameterWithDefault(sb, "directories", "object", "[]");
        sb.AppendLine();
        sb.AppendLine("steps:");
        sb.AppendLine();
        sb.AppendLine("  - ${{ if gt(length(parameters.directories), 0) }}:");
        sb.AppendLine("    - checkout: self");
        sb.AppendLine("      sparseCheckoutDirectories: ${{ join(' ', parameters.directories) }}");
        sb.AppendLine();
        sb.AppendLine("  - ${{ if eq(length(parameters.directories), 0) }}:");
        sb.AppendLine("    - checkout: self");
        sb.AppendLine("      clean: true");

        return sb.ToString();
    }

    internal static string GenerateSharedCiTemplate(
        IReadOnlyList<string> configNames,
        string? agentPoolName,
        string? bicepBasePath,
        string? pipelineBasePath)
    {
        var checkoutDirectories = new[]
        {
            BuildRepoRelativePath(pipelineBasePath, AzureDevOpsDirectory),
            BuildRepoRelativePath(bicepBasePath, CommonDirectory),
            BuildRepoRelativePath(bicepBasePath, ProjectNameParameterExpression),
        }.Distinct().ToList();

        var sb = new StringBuilder();
        sb.AppendLine("# Shared CI Pipeline Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        AppendParametersHeader(sb);
        AppendParameterWithDefault(sb, "continueOnError", "boolean", "false");
        AppendStringParameterWithValues(sb, "projectName", configNames);
        sb.AppendLine();
        sb.AppendLine("stages:");
        sb.AppendLine("  - stage: Build");
        sb.AppendLine("    displayName: 'Build & Publish Artifacts'");
        sb.AppendLine("    jobs:");
        sb.AppendLine("      - job: BuildBicep");
        sb.AppendLine("        displayName: 'Build Bicep'");
        AppendPool(sb, agentPoolName);
        sb.AppendLine("        continueOnError: ${{ parameters.continueOnError }}");
        sb.AppendLine("        steps:");
        sb.AppendLine("          - template: ../steps/checkout.step.yml");
        sb.AppendLine("            parameters:");
        sb.AppendLine("              directories:");
        foreach (var directory in checkoutDirectories)
        {
            sb.AppendLine($"                - {directory}");
        }
        sb.AppendLine();
        sb.AppendLine("          - task: CopyFiles@2");
        sb.AppendLine("            displayName: 'Copy Bicep files'");
        sb.AppendLine("            inputs:");
        sb.AppendLine($"              SourceFolder: '{BuildSourcesDirectoryPath(bicepBasePath)}'");
        sb.AppendLine("              Contents: |");
        sb.AppendLine("                **/*.bicep");
        sb.AppendLine("                **/*.bicepparam");
        sb.AppendLine("                **/*.json");
        sb.AppendLine("              TargetFolder: '$(Build.ArtifactStagingDirectory)'");
        sb.AppendLine();
        sb.AppendLine("          - powershell: |");
        sb.AppendLine("              $artifactRoot = '$(Build.ArtifactStagingDirectory)'");
        sb.AppendLine("              $commonPath = Join-Path $artifactRoot 'Common'");
        sb.AppendLine("              $projectPath = Join-Path $artifactRoot '${{ parameters.projectName }}'");
        sb.AppendLine("              $mainBicepPath = Join-Path $projectPath 'main.bicep'");
        sb.AppendLine();
        sb.AppendLine("              if (-not (Test-Path -LiteralPath $artifactRoot)) {");
        sb.AppendLine("                throw \"Artifact staging directory not found: $artifactRoot\"");
        sb.AppendLine(ClosingBraceIndentedSix);
        sb.AppendLine();
        sb.AppendLine("              Write-Host \"Artifact staging contents:\"");
        sb.AppendLine("              Get-ChildItem -LiteralPath $artifactRoot -Recurse | Select-Object FullName | Format-Table -AutoSize | Out-String | Write-Host");
        sb.AppendLine();
        sb.AppendLine("              if (-not (Test-Path -LiteralPath $commonPath)) {");
        sb.AppendLine("                throw \"Common artifact folder not found: $commonPath\"");
        sb.AppendLine(ClosingBraceIndentedSix);
        sb.AppendLine();
        sb.AppendLine("              if (-not (Test-Path -LiteralPath $projectPath)) {");
        sb.AppendLine("                throw \"Project artifact folder not found: $projectPath\"");
        sb.AppendLine(ClosingBraceIndentedSix);
        sb.AppendLine();
        sb.AppendLine("              if (-not (Test-Path -LiteralPath $mainBicepPath)) {");
        sb.AppendLine("                throw \"Main Bicep file not found in artifact: $mainBicepPath\"");
        sb.AppendLine(ClosingBraceIndentedSix);
        sb.AppendLine("            displayName: 'Validate artifact contents'");
        sb.AppendLine();
        sb.AppendLine("          - task: PublishBuildArtifacts@1");
        sb.AppendLine("            displayName: 'Publish Artifact'");
        sb.AppendLine("            inputs:");
        sb.AppendLine("              PathtoPublish: '$(Build.ArtifactStagingDirectory)'");
        sb.AppendLine("              ArtifactName: 'drop'");
        sb.AppendLine("              publishLocation: 'Container'");

        return sb.ToString();
    }

    internal static string GenerateSharedDeployJob(
        IReadOnlyList<string> configNames,
        IReadOnlyList<string> environmentNames,
        string? agentPoolName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Shared Deploy Job Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        AppendParametersHeader(sb);
        AppendStringParameterWithValues(sb, "projectName", configNames);
        AppendStringParameterWithValues(sb, "environment", environmentNames);
        AppendParameterWithDefault(sb, "deployments", "object", "[]");
        sb.AppendLine();
        sb.AppendLine("jobs:");
        sb.AppendLine("  - job: Deploy");
        sb.AppendLine("    displayName: 'Deploy to ${{ parameters.environment }}'");
        AppendPool(sb, agentPoolName, "    ");
        sb.AppendLine("    variables:");
        sb.AppendLine("      - template: ../variables/${{ parameters.environment }}.variables.yml");
        sb.AppendLine("    steps:");
        sb.AppendLine("      - checkout: none");
        sb.AppendLine("      - download: ci");
        sb.AppendLine("        artifact: drop");
        sb.AppendLine("        displayName: 'Download CI Artifacts'");
        sb.AppendLine();
        sb.AppendLine("      - ${{ each deployment in parameters.deployments }}:");
        sb.AppendLine("          - template: ../steps/deploy-template.step.yml");
        sb.AppendLine("            parameters:");
        sb.AppendLine("              azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}");
        sb.AppendLine("              subscriptionId: ${{ variables.subscriptionId }}");
        sb.AppendLine("              location: ${{ variables.location }}");
        sb.AppendLine("              deploymentName: ${{ deployment.deploymentName }}");
        sb.AppendLine("              templateFile: '${{ deployment.templateFile }}'");
        sb.AppendLine("              templateParametersFile: '${{ deployment.templateParametersFile }}'");
        sb.AppendLine("              overrideParameters: ${{ deployment.overrideParameters }}");

        return sb.ToString();
    }

    internal static string GenerateSharedDeployStep()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Shared Deploy Step Template — Auto-generated by InfraFlowSculptor");
        sb.AppendLine();
        AppendParametersHeader(sb);
        AppendParameter(sb, "azureResourceManagerConnection", StringParameterType);
        AppendParameter(sb, "subscriptionId", StringParameterType);
        AppendParameter(sb, "location", StringParameterType);
        AppendParameter(sb, "deploymentName", StringParameterType);
        AppendParameter(sb, "templateFile", StringParameterType);
        AppendParameter(sb, "templateParametersFile", StringParameterType);
        AppendParameterWithDefault(sb, "overrideParameters", StringParameterType, "''");
        sb.AppendLine();
        sb.AppendLine("steps:");
        sb.AppendLine("  - powershell: |");
        sb.AppendLine("      $templateFile = '${{ parameters.templateFile }}'");
        sb.AppendLine("      $parametersFile = '${{ parameters.templateParametersFile }}'");
        sb.AppendLine();
        sb.AppendLine("      if (-not (Test-Path -LiteralPath $templateFile)) {");
        sb.AppendLine("        $templateDirectory = Split-Path -Path $templateFile -Parent");
        sb.AppendLine("        if (Test-Path -LiteralPath $templateDirectory) {");
        sb.AppendLine("          Write-Host \"Template directory contents:\"");
        sb.AppendLine("          Get-ChildItem -LiteralPath $templateDirectory -Recurse | Select-Object FullName | Format-Table -AutoSize | Out-String | Write-Host");
        sb.AppendLine(ClosingBraceIndentedFour);
        sb.AppendLine("        throw \"Template file not found: $templateFile\"");
        sb.AppendLine(ClosingBraceIndentedThree);
        sb.AppendLine();
        sb.AppendLine("      if (-not (Test-Path -LiteralPath $parametersFile)) {");
        sb.AppendLine("        $parametersDirectory = Split-Path -Path $parametersFile -Parent");
        sb.AppendLine("        $fallbackFiles = @()");
        sb.AppendLine("        if (Test-Path -LiteralPath $parametersDirectory) {");
        sb.AppendLine("          Write-Host \"Parameters directory contents:\"");
        sb.AppendLine("          Get-ChildItem -LiteralPath $parametersDirectory -Recurse | Select-Object FullName | Format-Table -AutoSize | Out-String | Write-Host");
        sb.AppendLine("          $fallbackFiles = @(Get-ChildItem -LiteralPath $parametersDirectory -Filter 'main.*.bicepparam' -File)");
        sb.AppendLine(ClosingBraceIndentedFour);
        sb.AppendLine();
        sb.AppendLine("        if ($fallbackFiles.Count -eq 1) {");
        sb.AppendLine("          $parametersFile = $fallbackFiles[0].FullName");
        sb.AppendLine("          Write-Warning \"Expected parameters file not found. Falling back to: $parametersFile\"");
        sb.AppendLine(ClosingBraceIndentedFour);
        sb.AppendLine("        else {");
        sb.AppendLine("          throw \"Parameters file not found: $parametersFile\"");
        sb.AppendLine(ClosingBraceIndentedFour);
        sb.AppendLine(ClosingBraceIndentedThree);
        sb.AppendLine();
        sb.AppendLine("      $resolvedTemplateFile = (Resolve-Path -LiteralPath $templateFile).Path");
        sb.AppendLine("      $resolvedParametersFile = (Resolve-Path -LiteralPath $parametersFile).Path");
        sb.AppendLine("      $compiledTemplateFile = $resolvedTemplateFile");
        sb.AppendLine("      $compiledParametersFile = $resolvedParametersFile");
        sb.AppendLine("      $parametersFileForCompilation = $resolvedParametersFile");
        sb.AppendLine();
        sb.AppendLine("      if ([System.IO.Path]::GetExtension($resolvedTemplateFile).Equals('.bicep', [System.StringComparison]::OrdinalIgnoreCase)) {");
        sb.AppendLine("        $compiledTemplateFile = [System.IO.Path]::ChangeExtension($resolvedTemplateFile, '.json')");
        sb.AppendLine("        az bicep build --file $resolvedTemplateFile --outfile $compiledTemplateFile");
        sb.AppendLine("        if ($LASTEXITCODE -ne 0) {");
        sb.AppendLine("          throw \"Failed to compile template file: $resolvedTemplateFile\"");
        sb.AppendLine(ClosingBraceIndentedFour);
        sb.AppendLine(ClosingBraceIndentedThree);
        sb.AppendLine();
        sb.AppendLine("      if ([System.IO.Path]::GetExtension($resolvedParametersFile).Equals('.bicepparam', [System.StringComparison]::OrdinalIgnoreCase)) {");
        sb.AppendLine("        $parametersDirectory = Split-Path -Path $resolvedParametersFile -Parent");
        sb.AppendLine($"        $legacyMainPath = Join-Path $parametersDirectory '{MainBicepFileName}'");
        sb.AppendLine($"        $actualMainPath = Join-Path (Split-Path -Path $parametersDirectory -Parent) '{MainBicepFileName}'");
        sb.AppendLine("        $parametersContent = Get-Content -LiteralPath $resolvedParametersFile -Raw");
        sb.AppendLine();
        sb.AppendLine($"        if (-not (Test-Path -LiteralPath $legacyMainPath) -and (Test-Path -LiteralPath $actualMainPath) -and $parametersContent.Contains(\"{LegacyMainBicepUsingStatement}\")) {{");
        sb.AppendLine("          $patchedParametersFile = Join-Path $parametersDirectory (([System.IO.Path]::GetFileNameWithoutExtension($resolvedParametersFile)) + '.autofix.bicepparam')");
        sb.AppendLine($"          $patchedParametersContent = $parametersContent.Replace(\"{LegacyMainBicepUsingStatement}\", \"{ParentMainBicepUsingStatement}\")");
        sb.AppendLine("          Set-Content -LiteralPath $patchedParametersFile -Value $patchedParametersContent -NoNewline");
        sb.AppendLine("          $parametersFileForCompilation = $patchedParametersFile");
        sb.AppendLine("          Write-Warning \"Patched legacy parameters file using-path for compilation: $patchedParametersFile\"");
        sb.AppendLine(ClosingBraceIndentedFour);
        sb.AppendLine();
        sb.AppendLine("        $compiledParametersFile = Join-Path (Split-Path -Path $resolvedParametersFile -Parent) (([System.IO.Path]::GetFileNameWithoutExtension($resolvedParametersFile)) + '.parameters.json')");
        sb.AppendLine("        az bicep build-params --file $parametersFileForCompilation --outfile $compiledParametersFile");
        sb.AppendLine("        if ($LASTEXITCODE -ne 0) {");
        sb.AppendLine("          throw \"Failed to compile parameters file: $parametersFileForCompilation\"");
        sb.AppendLine(ClosingBraceIndentedFour);
        sb.AppendLine(ClosingBraceIndentedThree);
        sb.AppendLine();
        sb.AppendLine("      Write-Host \"Using template file: $resolvedTemplateFile\"");
        sb.AppendLine("      Write-Host \"Using parameters file: $resolvedParametersFile\"");
        sb.AppendLine("      Write-Host \"Using compiled template file: $compiledTemplateFile\"");
        sb.AppendLine("      Write-Host \"Using compiled parameters file: $compiledParametersFile\"");
        sb.AppendLine("      Write-Host \"##vso[task.setvariable variable=ResolvedTemplateFile]$compiledTemplateFile\"");
        sb.AppendLine("      Write-Host \"##vso[task.setvariable variable=ResolvedParametersFile]$compiledParametersFile\"");
        sb.AppendLine("    displayName: 'Resolve deployment files'");
        sb.AppendLine();
        AppendArmDeploymentTask(
            sb,
            "Validate - ${{ parameters.deploymentName }}",
            ValidationDeploymentMode);
        AppendArmDeploymentTask(
            sb,
            "Deploy - ${{ parameters.deploymentName }}",
            IncrementalDeploymentMode,
            includeDeploymentOutputs: true);
        sb.AppendLine("  - powershell: |");
        sb.AppendLine("      $raw = '$(armOutputs)'");
        sb.AppendLine("      if ([string]::IsNullOrWhiteSpace($raw) -or $raw -eq '$(armOutputs)') {");
        sb.AppendLine("        Write-Host 'No ARM deployment outputs to parse — skipping.'");
        sb.AppendLine("        return");
        sb.AppendLine(ClosingBraceIndentedThree);
        sb.AppendLine("      $outputs = $raw | ConvertFrom-Json");
        sb.AppendLine("      foreach ($key in $outputs.PSObject.Properties.Name) {");
        sb.AppendLine("        $value = $outputs.$key.value");
        sb.AppendLine("        Write-Host \"##vso[task.setvariable variable=$key;isOutput=true]$value\"");
        sb.AppendLine(ClosingBraceIndentedThree);
        sb.AppendLine("    displayName: 'Parse ARM Deployment Outputs'");
        sb.AppendLine("    name: armOutput");

        return sb.ToString();
    }

    private static void AppendParametersHeader(StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine("parameters:");
    }

    private static void AppendParameter(StringBuilder stringBuilder, string name, string type)
    {
        stringBuilder.AppendLine($"  - name: {name}");
        stringBuilder.AppendLine($"    type: {type}");
    }

    private static void AppendParameterWithDefault(
        StringBuilder stringBuilder,
        string name,
        string type,
        string defaultValue)
    {
        AppendParameter(stringBuilder, name, type);
        stringBuilder.AppendLine($"    default: {defaultValue}");
    }

    private static void AppendStringParameterWithValues(
        StringBuilder stringBuilder,
        string name,
        IReadOnlyList<string> values)
    {
        AppendParameter(stringBuilder, name, StringParameterType);
        stringBuilder.AppendLine("    values:");
        foreach (var value in values)
        {
            stringBuilder.AppendLine($"      - {value}");
        }
    }

    private static void AppendArmDeploymentTask(
        StringBuilder stringBuilder,
        string displayName,
        string deploymentMode,
        bool includeDeploymentOutputs = false)
    {
        stringBuilder.AppendLine("  - task: AzureResourceManagerTemplateDeployment@3");
        stringBuilder.AppendLine($"    displayName: '{displayName}'");
        stringBuilder.AppendLine("    inputs:");
        stringBuilder.AppendLine($"      deploymentScope: '{SubscriptionDeploymentScope}'");
        stringBuilder.AppendLine("      azureResourceManagerConnection: '${{ parameters.azureResourceManagerConnection }}'");
        stringBuilder.AppendLine("      subscriptionId: '${{ parameters.subscriptionId }}'");
        stringBuilder.AppendLine("      location: '${{ parameters.location }}'");
        stringBuilder.AppendLine("      templateLocation: 'Linked artifact'");
        stringBuilder.AppendLine($"      csmFile: '{ResolvedTemplateFileVariable}'");
        stringBuilder.AppendLine($"      csmParametersFile: '{ResolvedParametersFileVariable}'");
        stringBuilder.AppendLine("      overrideParameters: '${{ parameters.overrideParameters }}'");
        stringBuilder.AppendLine($"      deploymentMode: '{deploymentMode}'");
        if (includeDeploymentOutputs)
        {
            stringBuilder.AppendLine("      deploymentOutputs: 'armOutputs'");
        }

        stringBuilder.AppendLine();
    }

    private static string BuildRepoRelativePath(string? basePath, string relativePath)
    {
        if (string.IsNullOrWhiteSpace(basePath))
        {
            return relativePath;
        }

        return $"{basePath.Trim('/')}/{relativePath}";
    }

    private static string BuildSourcesDirectoryPath(string? relativePath)
    {
        if (string.IsNullOrWhiteSpace(relativePath))
        {
            return "$(Build.SourcesDirectory)";
        }

        return $"$(Build.SourcesDirectory)/{relativePath.Trim('/')}";
    }
}
