using InfraFlowSculptor.PipelineGeneration.Models;

namespace InfraFlowSculptor.PipelineGeneration.Bootstrap.Stages;

/// <summary>
/// Emits the YAML header: banner comments, trigger, variables, and stages preamble.
/// Always runs (no skip condition).
/// </summary>
public sealed class HeaderEmissionStage : IBootstrapPipelineStage
{
    /// <inheritdoc />
    public int Order => 100;

    /// <inheritdoc />
    public void Execute(BootstrapPipelineContext context)
    {
        var sb = context.Builder;
        var request = context.Request;

        var modeBanner = request.Mode == BootstrapMode.ApplicationOnly
            ? "Application-side bootstrap (SplitInfraCode). Validates shared project resources, then provisions application pipelines only."
            : "Infrastructure-side / standalone bootstrap. Owner of the shared project resources (environments, variable groups).";

        sb.AppendLine("# Bootstrap Pipeline — generated by InfraFlowSculptor");
        sb.AppendLine($"# {modeBanner}");
        sb.AppendLine("# Run this pipeline ONCE in Azure DevOps to provision the resources listed above.");
        sb.AppendLine("# All scripts are idempotent — re-running skips already-existing resources.");
        sb.AppendLine("#");
        sb.AppendLine("# Prerequisites:");
        sb.AppendLine("#   - The pipeline/job must expose $(System.AccessToken) to scripts");
        sb.AppendLine("#   - The build service identity must be allowed to manage pipelines, environments, and variable groups");
        sb.AppendLine("#   - The build service identity must also have Use permission on any agent pool referenced by the generated YAML");
        sb.AppendLine("#   - Service connections configured per environment in Azure DevOps");
        sb.AppendLine("#   - Azure CLI with azure-devops extension available on agent");

        if (request.Mode == BootstrapMode.ApplicationOnly)
        {
            sb.AppendLine("#   - Environments and variable groups must have been provisioned by the infra bootstrap first");
        }
        else
        {
            sb.AppendLine("#   - Approval-required environments are created automatically, but approver identities must still be configured manually in Azure DevOps");
        }

        sb.AppendLine();
        sb.AppendLine("trigger: none");
        sb.AppendLine();

        sb.AppendLine("name: bootstrap-$(Date:yyyyMMdd)$(Rev:.r)");
        sb.AppendLine();

        sb.AppendLine("variables:");
        sb.AppendLine($"  organizationUrl: 'https://dev.azure.com/{BootstrapYamlHelpers.EscapeSingleQuotes(request.OrganizationName)}'");
        sb.AppendLine($"  projectName: '{BootstrapYamlHelpers.EscapeSingleQuotes(request.ProjectName)}'");
        sb.AppendLine($"  repositoryName: '{BootstrapYamlHelpers.EscapeSingleQuotes(request.RepositoryName)}'");
        sb.AppendLine($"  defaultBranch: '{BootstrapYamlHelpers.EscapeSingleQuotes(request.DefaultBranch)}'");
        sb.AppendLine();
        sb.AppendLine("stages:");
        sb.AppendLine("- stage: BootstrapAzureDevOps");
        sb.AppendLine("  displayName: 'Bootstrap Azure DevOps'");
        sb.AppendLine("  jobs:");
    }
}
