// <auto-generated />
using System;
using System.Collections.Generic;
using InfraFlowSculptor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfraFlowSculptor.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20251220124340_Environments")]
    partial class Environments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AzureResourceDependencies", b =>
                {
                    b.Property<Guid>("DependsOnId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("DependsOnId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("AzureResourceDependencies");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceGroupId");

                    b.ToTable("AzureResource", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.Models.ResourceParameterUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AzureResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AzureResourceId");

                    b.HasIndex("ParameterId");

                    b.HasIndex("ResourceId", "ParameterId", "Purpose")
                        .IsUnique();

                    b.ToTable("ResourceParameterUsages", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InfraConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InfraConfigId", "UserId")
                        .IsUnique();

                    b.ToTable("infrastructureconfig_members", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.ParameterDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<Guid>("InfraConfigId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InfraConfigId");

                    b.ToTable("ParameterDefinitions", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InfrastructureConfigs", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ResourceGroupAggregate.ResourceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InfraConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InfraConfigId");

                    b.ToTable("ResourceGroup", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntraId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "InfraFlowSculptor.Domain.UserAggregate.User.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EntraId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.KeyVaultAggregate.KeyVault", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("KeyVaults", (string)null);
                });

            modelBuilder.Entity("AzureResourceDependencies", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany()
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ResourceGroupAggregate.ResourceGroup", "ResourceGroup")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceGroup");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.Models.ResourceParameterUsage", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany("ParameterUsages")
                        .HasForeignKey("AzureResourceId");

                    b.HasOne("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.ParameterDefinition", null)
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.Member", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", "InfraConfig")
                        .WithMany("Members")
                        .HasForeignKey("InfraConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfraConfig");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.ParameterDefinition", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", null)
                        .WithMany("ParameterDefinitions")
                        .HasForeignKey("InfraConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", b =>
                {
                    b.OwnsMany("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.EnvironmentDefinition", "EnvironmentDefinitions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("InfraConfigId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("RequiresApproval")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Suffix")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("InfraConfigId");

                            b1.ToTable("Environments", (string)null);

                            b1.WithOwner("InfraConfig")
                                .HasForeignKey("InfraConfigId");

                            b1.OwnsMany("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.EnvironmentParameterValue", "ParameterValues", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("EnvironmentDefinitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("EnvironmentId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("ParameterId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .HasColumnType("text");

                                    b2.HasKey("Id");

                                    b2.HasIndex("EnvironmentDefinitionId");

                                    b2.ToTable("EnvironmentParameterValues", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EnvironmentDefinitionId");
                                });

                            b1.OwnsMany("InfraFlowSculptor.Domain.UserAggregate.ValueObjects.Tag", "Tags", b2 =>
                                {
                                    b2.Property<Guid>("EnvironmentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)");

                                    b2.HasKey("EnvironmentId", "Name");

                                    b2.ToTable("EnvironmentTags", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EnvironmentId");
                                });

                            b1.Navigation("InfraConfig");

                            b1.Navigation("ParameterValues");

                            b1.Navigation("Tags");
                        });

                    b.Navigation("EnvironmentDefinitions");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ResourceGroupAggregate.ResourceGroup", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", "InfraConfig")
                        .WithMany("ResourceGroups")
                        .HasForeignKey("InfraConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfraConfig");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.KeyVaultAggregate.KeyVault", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.KeyVaultAggregate.KeyVault", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", b =>
                {
                    b.Navigation("ParameterUsages");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("ParameterDefinitions");

                    b.Navigation("ResourceGroups");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ResourceGroupAggregate.ResourceGroup", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
