// <auto-generated />
using System;
using System.Collections.Generic;
using InfraFlowSculptor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfraFlowSculptor.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260329083140_GenerationPipeline")]
    partial class GenerationPipeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AzureResourceDependencies", b =>
                {
                    b.Property<Guid>("DependsOnId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("DependsOnId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("AzureResourceDependencies");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.AppConfigurationAggregate.Entities.AppConfigurationEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("DisableLocalAuth")
                        .HasColumnType("boolean");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PublicNetworkAccess")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("PurgeProtectionEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SoftDeleteRetentionInDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppConfigurationId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("AppConfigurationEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.AppServicePlanAggregate.Entities.AppServicePlanEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppServicePlanId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppServicePlanId");

                    b.ToTable("AppServicePlanEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ApplicationInsightsAggregate.Entities.ApplicationInsightsEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationInsightsId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("DisableIpMasking")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DisableLocalAuth")
                        .HasColumnType("boolean");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IngestionMode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RetentionInDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SamplingPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationInsightsId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("ApplicationInsightsEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomNameOverride")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceGroupId");

                    b.ToTable("AzureResource", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.Entites.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("KeyVaultResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecretName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SecretValueAssignment")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceOutputName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("SourceResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyVaultResourceId");

                    b.HasIndex("SourceResourceId");

                    b.HasIndex("ResourceId", "Name")
                        .IsUnique();

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.Entites.AppSettingEnvironmentValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AppSettingId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("AppSettingEnvironmentValues", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.Entites.InputOutputLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("InputType")
                        .HasColumnType("integer");

                    b.Property<int>("OutputType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetResourceId");

                    b.HasIndex("SourceResourceId", "TargetResourceId", "OutputType", "InputType")
                        .IsUnique();

                    b.ToTable("ResourceLinks", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.Entites.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ManagedIdentityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleDefinitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserAssignedIdentityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceResourceId");

                    b.HasIndex("TargetResourceId");

                    b.HasIndex("UserAssignedIdentityId");

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.Models.ResourceParameterUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AzureResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AzureResourceId");

                    b.HasIndex("ParameterId");

                    b.HasIndex("ResourceId", "ParameterId", "Purpose")
                        .IsUnique();

                    b.ToTable("ResourceParameterUsages", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ContainerAppAggregate.Entities.ContainerAppEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContainerAppId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContainerImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CpuCores")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IngressEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IngressExternal")
                        .HasColumnType("boolean");

                    b.Property<int?>("IngressTargetPort")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxReplicas")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryGi")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("MinReplicas")
                        .HasColumnType("integer");

                    b.Property<string>("TransportMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerAppId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("ContainerAppEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ContainerAppEnvironmentAggregate.Entities.ContainerAppEnvironmentEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContainerAppEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("InternalLoadBalancerEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LogAnalyticsWorkspaceId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WorkloadProfileType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("ZoneRedundancyEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ContainerAppEnvironmentId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("ContainerAppEnvironmentEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.CosmosDbAggregate.Entities.CosmosDbEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BackupPolicyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsistencyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CosmosDbId")
                        .HasColumnType("uuid");

                    b.Property<string>("DatabaseApiType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("EnableAutomaticFailover")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EnableFreeTier")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EnableMultipleWriteLocations")
                        .HasColumnType("boolean");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MaxIntervalInSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxStalenessPrefix")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CosmosDbId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("CosmosDbEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.FunctionAppAggregate.Entities.FunctionAppEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FunctionAppId")
                        .HasColumnType("uuid");

                    b.Property<string>("FunctionsWorkerRuntime")
                        .HasColumnType("text");

                    b.Property<bool?>("HttpsOnly")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxInstanceCount")
                        .HasColumnType("integer");

                    b.Property<string>("RuntimeStack")
                        .HasColumnType("text");

                    b.Property<string>("RuntimeVersion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FunctionAppId");

                    b.ToTable("FunctionAppEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.CrossConfigResourceReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InfraConfigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetConfigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InfraConfigId", "TargetResourceId")
                        .IsUnique();

                    b.ToTable("CrossConfigResourceReferences", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.ParameterDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<Guid>("InfraConfigId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InfraConfigId");

                    b.ToTable("ParameterDefinitions", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.ResourceNamingTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InfraConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InfraConfigId", "ResourceType")
                        .IsUnique();

                    b.ToTable("ResourceNamingTemplates", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultNamingTemplate")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UseProjectNamingConventions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("InfrastructureConfigs", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.KeyVaultAggregate.Entities.KeyVaultEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("KeyVaultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyVaultId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("KeyVaultEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.LogAnalyticsWorkspaceAggregate.Entities.LogAnalyticsWorkspaceEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DailyQuotaGb")
                        .HasColumnType("numeric");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LogAnalyticsWorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RetentionInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("LogAnalyticsWorkspaceId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("LogAnalyticsWorkspaceEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ProjectAggregate.Entities.GitRepositoryConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BasePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("main");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PipelineBasePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("GitRepositoryConfigurations", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ProjectAggregate.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ProjectAggregate.Entities.ProjectResourceNamingTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "ResourceType")
                        .IsUnique();

                    b.ToTable("ProjectResourceNamingTemplates", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ProjectAggregate.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultNamingTemplate")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("MultiRepo");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.RedisCacheAggregate.Entities.RedisCacheEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaxMemoryPolicy")
                        .HasColumnType("text");

                    b.Property<Guid>("RedisCacheId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RedisCacheId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("RedisCacheEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ResourceGroupAggregate.ResourceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InfraConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InfraConfigId");

                    b.ToTable("ResourceGroup", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.Entities.ServiceBusNamespaceEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool?>("DisableLocalAuth")
                        .HasColumnType("boolean");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MinimumTlsVersion")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("ServiceBusNamespaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("ZoneRedundant")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ServiceBusNamespaceId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("ServiceBusNamespaceEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.Entities.ServiceBusQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("ServiceBusNamespaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceBusNamespaceId", "Name")
                        .IsUnique();

                    b.ToTable("ServiceBusQueues", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.Entities.ServiceBusTopicSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceBusNamespaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceBusNamespaceId", "TopicName", "SubscriptionName")
                        .IsUnique();

                    b.ToTable("ServiceBusTopicSubscriptions", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.SqlDatabaseAggregate.Entities.SqlDatabaseEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaxSizeGb")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<Guid>("SqlDatabaseId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("ZoneRedundant")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SqlDatabaseId");

                    b.ToTable("SqlDatabaseEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.SqlServerAggregate.Entities.SqlServerEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinimalTlsVersion")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("SqlServerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SqlServerId");

                    b.ToTable("SqlServerEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.BlobContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicAccess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StorageAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StorageAccountId");

                    b.ToTable("BlobContainers", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.BlobLifecycleRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("ContainerNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("StorageAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeToLiveInDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageAccountId");

                    b.ToTable("BlobLifecycleRules", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.CorsRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AllowedHeaders")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("AllowedMethods")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("AllowedOrigins")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("ExposedHeaders")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("MaxAgeInSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StorageAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StorageAccountId");

                    b.ToTable("StorageAccountCorsRules", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.StorageAccountEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<Guid>("StorageAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StorageAccountId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("StorageAccountEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.StorageQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StorageAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StorageAccountId");

                    b.ToTable("StorageQueues", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.StorageTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StorageAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StorageAccountId");

                    b.ToTable("StorageTables", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntraId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "InfraFlowSculptor.Domain.UserAggregate.User.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EntraId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.WebAppAggregate.Entities.WebAppEnvironmentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool?>("AlwaysOn")
                        .HasColumnType("boolean");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("HttpsOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("RuntimeStack")
                        .HasColumnType("text");

                    b.Property<string>("RuntimeVersion")
                        .HasColumnType("text");

                    b.Property<Guid>("WebAppId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebAppId");

                    b.ToTable("WebAppEnvironmentSettings", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.AppConfigurationAggregate.AppConfiguration", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.ToTable("AppConfigurations", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.AppServicePlanAggregate.AppServicePlan", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<string>("OsType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("AppServicePlans", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ApplicationInsightsAggregate.ApplicationInsights", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<Guid>("LogAnalyticsWorkspaceId")
                        .HasColumnType("uuid");

                    b.ToTable("ApplicationInsights", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ContainerAppAggregate.ContainerApp", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<Guid>("ContainerAppEnvironmentId")
                        .HasColumnType("uuid");

                    b.ToTable("ContainerApps", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ContainerAppEnvironmentAggregate.ContainerAppEnvironment", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.ToTable("ContainerAppEnvironments", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.CosmosDbAggregate.CosmosDb", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.ToTable("CosmosDbAccounts", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.FunctionAppAggregate.FunctionApp", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<Guid>("AppServicePlanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HttpsOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("RuntimeStack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuntimeVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("FunctionApps", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.KeyVaultAggregate.KeyVault", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<bool>("EnablePurgeProtection")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableRbacAuthorization")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableSoftDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnabledForDeployment")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnabledForDiskEncryption")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnabledForTemplateDeployment")
                        .HasColumnType("boolean");

                    b.ToTable("KeyVaults", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.LogAnalyticsWorkspaceAggregate.LogAnalyticsWorkspace", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.ToTable("LogAnalyticsWorkspaces", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.RedisCacheAggregate.RedisCache", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<bool>("DisableAccessKeyAuthentication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableAadAuth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableNonSslPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MinimumTlsVersion")
                        .HasColumnType("text");

                    b.Property<int?>("RedisVersion")
                        .HasColumnType("integer");

                    b.ToTable("RedisCaches", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.ServiceBusNamespace", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.ToTable("ServiceBusNamespaces", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.SqlDatabaseAggregate.SqlDatabase", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<string>("Collation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SqlServerId")
                        .HasColumnType("uuid");

                    b.ToTable("SqlDatabases", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.SqlServerAggregate.SqlServer", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<string>("AdministratorLogin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("SqlServers", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.StorageAccount", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<string>("AccessTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AllowBlobPublicAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableHttpsTrafficOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinimumTlsVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("StorageAccounts", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.UserAssignedIdentityAggregate.UserAssignedIdentity", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.ToTable("UserAssignedIdentities", (string)null);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.WebAppAggregate.WebApp", b =>
                {
                    b.HasBaseType("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource");

                    b.Property<bool>("AlwaysOn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AppServicePlanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HttpsOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("RuntimeStack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuntimeVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("WebApps", (string)null);
                });

            modelBuilder.Entity("AzureResourceDependencies", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany()
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.AppConfigurationAggregate.Entities.AppConfigurationEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.AppConfigurationAggregate.AppConfiguration", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("AppConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.AppServicePlanAggregate.Entities.AppServicePlanEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.AppServicePlanAggregate.AppServicePlan", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("AppServicePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ApplicationInsightsAggregate.Entities.ApplicationInsightsEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ApplicationInsightsAggregate.ApplicationInsights", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("ApplicationInsightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ResourceGroupAggregate.ResourceGroup", "ResourceGroup")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceGroup");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.Entites.AppSetting", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany()
                        .HasForeignKey("KeyVaultResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany("AppSettings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany()
                        .HasForeignKey("SourceResourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.Entites.AppSettingEnvironmentValue", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.Entites.AppSetting", null)
                        .WithMany("EnvironmentValues")
                        .HasForeignKey("AppSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.Entites.InputOutputLink", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", "SourceResource")
                        .WithMany("Outputs")
                        .HasForeignKey("SourceResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", "TargetResource")
                        .WithMany("Inputs")
                        .HasForeignKey("TargetResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceResource");

                    b.Navigation("TargetResource");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.Entites.RoleAssignment", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany("RoleAssignments")
                        .HasForeignKey("SourceResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany()
                        .HasForeignKey("TargetResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany()
                        .HasForeignKey("UserAssignedIdentityId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.Models.ResourceParameterUsage", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany("ParameterUsages")
                        .HasForeignKey("AzureResourceId");

                    b.HasOne("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.ParameterDefinition", null)
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ContainerAppAggregate.Entities.ContainerAppEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ContainerAppAggregate.ContainerApp", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("ContainerAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ContainerAppEnvironmentAggregate.Entities.ContainerAppEnvironmentEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ContainerAppEnvironmentAggregate.ContainerAppEnvironment", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("ContainerAppEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.CosmosDbAggregate.Entities.CosmosDbEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.CosmosDbAggregate.CosmosDb", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("CosmosDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.FunctionAppAggregate.Entities.FunctionAppEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.FunctionAppAggregate.FunctionApp", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("FunctionAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.CrossConfigResourceReference", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", null)
                        .WithMany("CrossConfigReferences")
                        .HasForeignKey("InfraConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.ParameterDefinition", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", null)
                        .WithMany("ParameterDefinitions")
                        .HasForeignKey("InfraConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.Entities.ResourceNamingTemplate", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", "InfraConfig")
                        .WithMany("ResourceNamingTemplates")
                        .HasForeignKey("InfraConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfraConfig");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ProjectAggregate.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.KeyVaultAggregate.Entities.KeyVaultEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.KeyVaultAggregate.KeyVault", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("KeyVaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.LogAnalyticsWorkspaceAggregate.Entities.LogAnalyticsWorkspaceEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.LogAnalyticsWorkspaceAggregate.LogAnalyticsWorkspace", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("LogAnalyticsWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ProjectAggregate.Entities.GitRepositoryConfiguration", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ProjectAggregate.Project", null)
                        .WithOne("GitRepositoryConfiguration")
                        .HasForeignKey("InfraFlowSculptor.Domain.ProjectAggregate.Entities.GitRepositoryConfiguration", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ProjectAggregate.Entities.ProjectMember", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ProjectAggregate.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfraFlowSculptor.Domain.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ProjectAggregate.Entities.ProjectResourceNamingTemplate", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ProjectAggregate.Project", "Project")
                        .WithMany("ResourceNamingTemplates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ProjectAggregate.Project", b =>
                {
                    b.OwnsMany("InfraFlowSculptor.Domain.ProjectAggregate.Entities.ProjectEnvironmentDefinition", "EnvironmentDefinitions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("RequiresApproval")
                                .HasColumnType("boolean");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Suffix")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjectId");

                            b1.ToTable("ProjectEnvironments", (string)null);

                            b1.WithOwner("Project")
                                .HasForeignKey("ProjectId");

                            b1.OwnsMany("InfraFlowSculptor.Domain.UserAggregate.ValueObjects.Tag", "Tags", b2 =>
                                {
                                    b2.Property<Guid>("EnvironmentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)");

                                    b2.HasKey("EnvironmentId", "Name");

                                    b2.ToTable("ProjectEnvironmentTags", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EnvironmentId");
                                });

                            b1.Navigation("Project");

                            b1.Navigation("Tags");
                        });

                    b.Navigation("EnvironmentDefinitions");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.RedisCacheAggregate.Entities.RedisCacheEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.RedisCacheAggregate.RedisCache", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("RedisCacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ResourceGroupAggregate.ResourceGroup", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", "InfraConfig")
                        .WithMany("ResourceGroups")
                        .HasForeignKey("InfraConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfraConfig");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.Entities.ServiceBusNamespaceEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.ServiceBusNamespace", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("ServiceBusNamespaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.Entities.ServiceBusQueue", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.ServiceBusNamespace", null)
                        .WithMany("Queues")
                        .HasForeignKey("ServiceBusNamespaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.Entities.ServiceBusTopicSubscription", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.ServiceBusNamespace", null)
                        .WithMany("TopicSubscriptions")
                        .HasForeignKey("ServiceBusNamespaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.SqlDatabaseAggregate.Entities.SqlDatabaseEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.SqlDatabaseAggregate.SqlDatabase", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("SqlDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.SqlServerAggregate.Entities.SqlServerEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.SqlServerAggregate.SqlServer", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("SqlServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.BlobContainer", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.StorageAccountAggregate.StorageAccount", null)
                        .WithMany("BlobContainers")
                        .HasForeignKey("StorageAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.BlobLifecycleRule", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.StorageAccountAggregate.StorageAccount", null)
                        .WithMany("LifecycleRules")
                        .HasForeignKey("StorageAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.CorsRule", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.StorageAccountAggregate.StorageAccount", null)
                        .WithMany("AllCorsRules")
                        .HasForeignKey("StorageAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.StorageAccountEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.StorageAccountAggregate.StorageAccount", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("StorageAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.StorageQueue", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.StorageAccountAggregate.StorageAccount", null)
                        .WithMany("Queues")
                        .HasForeignKey("StorageAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.Entities.StorageTable", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.StorageAccountAggregate.StorageAccount", null)
                        .WithMany("Tables")
                        .HasForeignKey("StorageAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.WebAppAggregate.Entities.WebAppEnvironmentSettings", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.WebAppAggregate.WebApp", null)
                        .WithMany("EnvironmentSettings")
                        .HasForeignKey("WebAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.AppConfigurationAggregate.AppConfiguration", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.AppConfigurationAggregate.AppConfiguration", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.AppServicePlanAggregate.AppServicePlan", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.AppServicePlanAggregate.AppServicePlan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ApplicationInsightsAggregate.ApplicationInsights", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.ApplicationInsightsAggregate.ApplicationInsights", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ContainerAppAggregate.ContainerApp", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.ContainerAppAggregate.ContainerApp", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ContainerAppEnvironmentAggregate.ContainerAppEnvironment", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.ContainerAppEnvironmentAggregate.ContainerAppEnvironment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.CosmosDbAggregate.CosmosDb", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.CosmosDbAggregate.CosmosDb", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.FunctionAppAggregate.FunctionApp", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.FunctionAppAggregate.FunctionApp", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.KeyVaultAggregate.KeyVault", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.KeyVaultAggregate.KeyVault", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.LogAnalyticsWorkspaceAggregate.LogAnalyticsWorkspace", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.LogAnalyticsWorkspaceAggregate.LogAnalyticsWorkspace", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.RedisCacheAggregate.RedisCache", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.RedisCacheAggregate.RedisCache", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.ServiceBusNamespace", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.ServiceBusNamespace", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.SqlDatabaseAggregate.SqlDatabase", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.SqlDatabaseAggregate.SqlDatabase", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.SqlServerAggregate.SqlServer", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.SqlServerAggregate.SqlServer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.StorageAccount", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.StorageAccountAggregate.StorageAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.UserAssignedIdentityAggregate.UserAssignedIdentity", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.UserAssignedIdentityAggregate.UserAssignedIdentity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.WebAppAggregate.WebApp", b =>
                {
                    b.HasOne("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", null)
                        .WithOne()
                        .HasForeignKey("InfraFlowSculptor.Domain.WebAppAggregate.WebApp", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.AzureResource", b =>
                {
                    b.Navigation("AppSettings");

                    b.Navigation("Inputs");

                    b.Navigation("Outputs");

                    b.Navigation("ParameterUsages");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.Common.BaseModels.Entites.AppSetting", b =>
                {
                    b.Navigation("EnvironmentValues");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.InfrastructureConfigAggregate.InfrastructureConfig", b =>
                {
                    b.Navigation("CrossConfigReferences");

                    b.Navigation("ParameterDefinitions");

                    b.Navigation("ResourceGroups");

                    b.Navigation("ResourceNamingTemplates");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ProjectAggregate.Project", b =>
                {
                    b.Navigation("GitRepositoryConfiguration");

                    b.Navigation("Members");

                    b.Navigation("ResourceNamingTemplates");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ResourceGroupAggregate.ResourceGroup", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.AppConfigurationAggregate.AppConfiguration", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.AppServicePlanAggregate.AppServicePlan", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ApplicationInsightsAggregate.ApplicationInsights", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ContainerAppAggregate.ContainerApp", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ContainerAppEnvironmentAggregate.ContainerAppEnvironment", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.CosmosDbAggregate.CosmosDb", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.FunctionAppAggregate.FunctionApp", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.KeyVaultAggregate.KeyVault", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.LogAnalyticsWorkspaceAggregate.LogAnalyticsWorkspace", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.RedisCacheAggregate.RedisCache", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.ServiceBusNamespaceAggregate.ServiceBusNamespace", b =>
                {
                    b.Navigation("EnvironmentSettings");

                    b.Navigation("Queues");

                    b.Navigation("TopicSubscriptions");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.SqlDatabaseAggregate.SqlDatabase", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.SqlServerAggregate.SqlServer", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.StorageAccountAggregate.StorageAccount", b =>
                {
                    b.Navigation("AllCorsRules");

                    b.Navigation("BlobContainers");

                    b.Navigation("EnvironmentSettings");

                    b.Navigation("LifecycleRules");

                    b.Navigation("Queues");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("InfraFlowSculptor.Domain.WebAppAggregate.WebApp", b =>
                {
                    b.Navigation("EnvironmentSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
